// This file is auto-generated by oagen. Do not edit.

export interface ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemPropertyAttributes {
  label?: string;
  /** Coupon code, present only for a store-verified coupon modifier. */
  code?: string;
  [key: string]: unknown;
}

export interface ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemPropertyAttributesResponse {
  label?: string;
  code?: string;
  [key: string]: unknown;
}
