// This file is auto-generated by oagen. Do not edit.

import type { SearchOrdersRequestApplicationJsonPropertyPagination, SearchOrdersRequestApplicationJsonPropertyPaginationResponse } from '../../orders/interfaces/search-orders-request-application-json-property-pagination.interface';

export type SearchOrderSLineItemsRequestApplicationJsonPropertyPagination = SearchOrdersRequestApplicationJsonPropertyPagination;
export type SearchOrderSLineItemsRequestApplicationJsonPropertyPaginationResponse = SearchOrdersRequestApplicationJsonPropertyPaginationResponse;
