// This file is auto-generated by oagen. Do not edit.

import type { SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemPropertyAttributes, SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemPropertyAttributesResponse } from './search-order-line-items-response-value-200-application-json-property-data-item-property-discounts-property-modifiers-item-property-attributes.interface';

export interface SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem {
  type: string;
  key?: string;
  amountCents?: number;
  attributes?: SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemPropertyAttributes;
  [key: string]: unknown;
}

export interface SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemResponse {
  type: string;
  key?: string;
  amount_cents?: number;
  attributes?: SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemPropertyAttributesResponse;
  [key: string]: unknown;
}
