// This file is auto-generated by oagen. Do not edit.

export const SearchOrderLineItemsRequestApplicationJsonPropertySortItemField = {
  CreatedAt: 'created_at',
  Total: 'total',
  Revenue: 'revenue',
  Quantity: 'quantity',
} as const;

export type SearchOrderLineItemsRequestApplicationJsonPropertySortItemField =
  | (typeof SearchOrderLineItemsRequestApplicationJsonPropertySortItemField)[keyof typeof SearchOrderLineItemsRequestApplicationJsonPropertySortItemField]
  | (string & Record<never, never>);
