// This file is auto-generated by oagen. Do not edit.

import type { SdkReplaceProductSAddOnsResponseValue200ApplicationJson, SdkReplaceProductSAddOnsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-replace-product-s-add-ons-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItem } from './replace-product-s-add-ons-response-value-200-application-json-property-data-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceProductSAddOnsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceProductSAddOnsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const deserializeSdkReplaceProductSAddOnsResponseValue200ApplicationJson = (
  response: SdkReplaceProductSAddOnsResponseValue200ApplicationJsonResponse,
): SdkReplaceProductSAddOnsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: response.data.map(deserializeReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItem),
  };
};
