// This file is auto-generated by oagen. Do not edit.

import type { SearchAddOnsRequestApplicationJsonPropertyFiltersItem, SearchAddOnsRequestApplicationJsonPropertyFiltersItemResponse } from '../interfaces/search-add-ons-request-application-json-property-filters-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { serializeSearchAddOnsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem } from './search-add-ons-request-application-json-property-filters-item-property-nested-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SearchAddOnsRequestApplicationJsonPropertyFiltersItem","required":[],"properties":{"field":{"kind":"primitive","type":"string"},"operator":{"kind":"primitive","type":"string"},"value":{"kind":"primitive","type":"unknown"},"type":{"kind":"enum","values":["and","or"]},"nested":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SearchAddOnsRequestApplicationJsonPropertyFiltersItem","required":[],"properties":{"field":{"kind":"primitive","type":"string"},"operator":{"kind":"primitive","type":"string"},"value":{"kind":"primitive","type":"unknown"},"type":{"kind":"enum","values":["and","or"]},"nested":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const serializeSearchAddOnsRequestApplicationJsonPropertyFiltersItem = (
  model: SearchAddOnsRequestApplicationJsonPropertyFiltersItem,
): SearchAddOnsRequestApplicationJsonPropertyFiltersItemResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["field","operator","value","type","nested"]),
    field: model.field,
    operator: model.operator,
    value: model.value,
    type: model.type,
    nested: model.nested != null ? model.nested.map(serializeSearchAddOnsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem) : undefined,
  };
};
