// This file is auto-generated by oagen. Do not edit.

import type { SellApp } from '../sellapp';
import type { GetOptions as RequestOptions } from '../common/interfaces/get-options.interface';
import { AutoPaginatable } from '../common/utils/pagination';
import { fetchAndDeserialize } from '../common/utils/fetch-and-deserialize';
import type { CoursesListOptions } from './interfaces/courses-list-options.interface';
import type { SearchOptions } from './interfaces/search-options.interface';
import type { GetOptions } from './interfaces/get-options.interface';
import type { ReplaceOptions } from './interfaces/replace-options.interface';
import type { UpdateOptions } from './interfaces/update-options.interface';
import type { SdkListCoursesResponseValue200ApplicationJson, SdkListCoursesResponseValue200ApplicationJsonResponse } from './interfaces/sdk-list-courses-response-value-200-application-json.interface';
import type { SdkSearchCoursesResponseValue200ApplicationJson, SdkSearchCoursesResponseValue200ApplicationJsonResponse } from './interfaces/sdk-search-courses-response-value-200-application-json.interface';
import type { SdkGetCourseResponseValue200ApplicationJson, SdkGetCourseResponseValue200ApplicationJsonResponse } from './interfaces/sdk-get-course-response-value-200-application-json.interface';
import type { SdkReplaceCourseResponseValue200ApplicationJson, SdkReplaceCourseResponseValue200ApplicationJsonResponse } from './interfaces/sdk-replace-course-response-value-200-application-json.interface';
import type { SdkUpdateCourseResponseValue200ApplicationJson, SdkUpdateCourseResponseValue200ApplicationJsonResponse } from './interfaces/sdk-update-course-response-value-200-application-json.interface';
import type { SdkSearchRewardRulesRequestApplicationJsonResponse } from '../reward-rules/interfaces/sdk-search-reward-rules-request-application-json.interface';
import type { SdkReplaceCourseRequestApplicationJsonResponse } from './interfaces/sdk-replace-course-request-application-json.interface';
import type { SdkUpdateCourseRequestApplicationJsonResponse } from './interfaces/sdk-update-course-request-application-json.interface';
import { deserializeSdkListCoursesResponseValue200ApplicationJson } from './serializers/sdk-list-courses-response-value-200-application-json.serializer';
import { deserializeSdkSearchCoursesResponseValue200ApplicationJson } from './serializers/sdk-search-courses-response-value-200-application-json.serializer';
import { deserializeSdkGetCourseResponseValue200ApplicationJson } from './serializers/sdk-get-course-response-value-200-application-json.serializer';
import { deserializeSdkReplaceCourseResponseValue200ApplicationJson } from './serializers/sdk-replace-course-response-value-200-application-json.serializer';
import { deserializeSdkUpdateCourseResponseValue200ApplicationJson } from './serializers/sdk-update-course-response-value-200-application-json.serializer';
import { serializeSdkSearchRewardRulesRequestApplicationJson } from '../reward-rules/serializers/sdk-search-reward-rules-request-application-json.serializer';
import { serializeSdkReplaceCourseRequestApplicationJson } from './serializers/sdk-replace-course-request-application-json.serializer';
import { serializeSdkUpdateCourseRequestApplicationJson } from './serializers/sdk-update-course-request-application-json.serializer';

interface SellAppResponseEnvelope<T> { data: T; status: number; headers: Headers; requestId?: string }
type SellAppWithResponse<T extends object> = {
  [K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never]:
    T[K] extends (...args: infer A) => Promise<infer R> ? (...args: A) => Promise<SellAppResponseEnvelope<R>> : never;
};
function createResourceWithResponse<T extends object>(resource: T, client: SellApp): SellAppWithResponse<T> {
  return new Proxy({} as SellAppWithResponse<T>, {
    get: (_target, property) => (...args: unknown[]) => client.captureResponse(
      () => (resource[property as keyof T] as (...values: unknown[]) => Promise<unknown>).apply(resource, args),
    ),
  }) as SellAppWithResponse<T>;
}

export class Courses {
  constructor(private readonly sellApp: SellApp) {}
  get withResponse(): SellAppWithResponse<this> { return createResourceWithResponse(this, this.sellApp); }

  /**
   * List courses
   *
   * List course products and their complete ordered curriculum for the authenticated store. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<SdkListCoursesResponseValue200ApplicationJson>>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async list(options?: CoursesListOptions): Promise<AutoPaginatable<SdkListCoursesResponseValue200ApplicationJson, CoursesListOptions>> {
    const paginationOptions = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<SdkListCoursesResponseValue200ApplicationJsonResponse, SdkListCoursesResponseValue200ApplicationJson>(
        this.sellApp,
        '/v2/courses',
        deserializeSdkListCoursesResponseValue200ApplicationJson,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<SdkListCoursesResponseValue200ApplicationJsonResponse, SdkListCoursesResponseValue200ApplicationJson>(
          this.sellApp,
          '/v2/courses',
          deserializeSdkListCoursesResponseValue200ApplicationJson,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * Search courses
   *
   * Search courses by title, slug, or description and compose supported filters and sort instructions. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<SdkSearchCoursesResponseValue200ApplicationJson>>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async search(options: SearchOptions): Promise<SdkSearchCoursesResponseValue200ApplicationJson> {
    const { page, pagination, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.post<SdkSearchCoursesResponseValue200ApplicationJsonResponse, SdkSearchRewardRulesRequestApplicationJsonResponse>(
      '/v2/courses/search',
      serializeSdkSearchRewardRulesRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'searchCourses', query: { ...(options.page !== undefined && { page: options.page }), ...(options.pagination !== undefined && { pagination: options.pagination }) } },
    );
    return deserializeSdkSearchCoursesResponseValue200ApplicationJson(data);
  }

  /**
   * Retrieve a course
   *
   * Retrieve one store-scoped course by listing ID or slug with its ordered curriculum. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.course - The course path parameter.
   * @returns {Promise<SdkGetCourseResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async get(options: GetOptions): Promise<SdkGetCourseResponseValue200ApplicationJson> {
    const { course } = options;
    const { data } = await this.sellApp.get<SdkGetCourseResponseValue200ApplicationJsonResponse>(`/v2/courses/${encodeURIComponent(course)}`, { ...options.requestOptions, operationId: 'getCourse' });
    return deserializeSdkGetCourseResponseValue200ApplicationJson(data);
  }

  /**
   * Update a course
   *
   * Update course metadata, access configuration, delivery copy, or publication visibility. Public visibility requires a ready promotional video and at least one published lesson. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.course - The course path parameter.
   * @returns {Promise<SdkReplaceCourseResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async replace(options: ReplaceOptions): Promise<SdkReplaceCourseResponseValue200ApplicationJson> {
    const { course, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.put<SdkReplaceCourseResponseValue200ApplicationJsonResponse, SdkReplaceCourseRequestApplicationJsonResponse>(
      `/v2/courses/${encodeURIComponent(course)}`,
      serializeSdkReplaceCourseRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'replaceCourse' },
    );
    return deserializeSdkReplaceCourseResponseValue200ApplicationJson(data);
  }

  /**
   * Update a course
   *
   * Update course metadata, access configuration, delivery copy, or publication visibility. Public visibility requires a ready promotional video and at least one published lesson. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.course - The course path parameter.
   * @returns {Promise<SdkUpdateCourseResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async update(options: UpdateOptions): Promise<SdkUpdateCourseResponseValue200ApplicationJson> {
    const { course, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.patch<SdkUpdateCourseResponseValue200ApplicationJsonResponse, SdkUpdateCourseRequestApplicationJsonResponse>(
      `/v2/courses/${encodeURIComponent(course)}`,
      serializeSdkUpdateCourseRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'updateCourse' },
    );
    return deserializeSdkUpdateCourseResponseValue200ApplicationJson(data);
  }
}
