// This file is auto-generated by oagen. Do not edit.

import type { SdkGetBundleItemResponseValue200ApplicationJson, SdkGetBundleItemResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-get-bundle-item-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeGetBundleItemResponseValue200ApplicationJsonPropertyData } from './get-bundle-item-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkGetBundleItemResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkGetBundleItemResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkGetBundleItemResponseValue200ApplicationJson = (
  response: SdkGetBundleItemResponseValue200ApplicationJsonResponse,
): SdkGetBundleItemResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeGetBundleItemResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
