// This file is auto-generated by oagen. Do not edit.

import type { ListVariantDeliverableFoldersResponseValue200ApplicationJsonPropertyDataItem, ListVariantDeliverableFoldersResponseValue200ApplicationJsonPropertyDataItemResponse } from '../interfaces/list-variant-deliverable-folders-response-value-200-application-json-property-data-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListVariantDeliverableFoldersResponseValue200ApplicationJsonPropertyDataItem","required":["id","name","variantId","sortOrder"],"properties":{"id":{"kind":"primitive","type":"integer"},"name":{"kind":"primitive","type":"string","constraints":{"maxLength":255}},"description":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":255}}},"parentId":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"variantId":{"kind":"primitive","type":"integer"},"sortOrder":{"kind":"primitive","type":"integer","constraints":{"minimum":0}},"createdAt":{"kind":"primitive","type":"string","format":"date-time"},"updatedAt":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListVariantDeliverableFoldersResponseValue200ApplicationJsonPropertyDataItem","required":["id","name","variant_id","sort_order"],"properties":{"id":{"kind":"primitive","type":"integer"},"name":{"kind":"primitive","type":"string","constraints":{"maxLength":255}},"description":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":255}}},"parent_id":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"variant_id":{"kind":"primitive","type":"integer"},"sort_order":{"kind":"primitive","type":"integer","constraints":{"minimum":0}},"created_at":{"kind":"primitive","type":"string","format":"date-time"},"updated_at":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};

export const deserializeListVariantDeliverableFoldersResponseValue200ApplicationJsonPropertyDataItem = (
  response: ListVariantDeliverableFoldersResponseValue200ApplicationJsonPropertyDataItemResponse,
): ListVariantDeliverableFoldersResponseValue200ApplicationJsonPropertyDataItem => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["id","name","description","parent_id","variant_id","sort_order","created_at","updated_at"]),
    id: response.id,
    name: response.name,
    description: response.description ?? null,
    parentId: response.parent_id ?? null,
    variantId: response.variant_id,
    sortOrder: response.sort_order,
    createdAt: response.created_at != null ? new Date(response.created_at) : undefined,
    updatedAt: response.updated_at != null ? new Date(response.updated_at) : undefined,
  };
};
