// This file is auto-generated by oagen. Do not edit.

import type { SdkReplaceVariantDeliverableFolderSettingsResponseValue200ApplicationJson, SdkReplaceVariantDeliverableFolderSettingsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-replace-variant-deliverable-folder-settings-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeReplaceVariantDeliverableFolderSettingsResponseValue200ApplicationJsonPropertyData } from './replace-variant-deliverable-folder-settings-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceVariantDeliverableFolderSettingsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceVariantDeliverableFolderSettingsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkReplaceVariantDeliverableFolderSettingsResponseValue200ApplicationJson = (
  response: SdkReplaceVariantDeliverableFolderSettingsResponseValue200ApplicationJsonResponse,
): SdkReplaceVariantDeliverableFolderSettingsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeReplaceVariantDeliverableFolderSettingsResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
