// This file is auto-generated by oagen. Do not edit.

export { serializeSdkReplaceVariantDeliverableFolderSettingsRequestApplicationJson as serializeSdkUpdateVariantDeliverableFolderRequestApplicationJson } from './sdk-replace-variant-deliverable-folder-settings-request-application-json.serializer';
