// This file is auto-generated by oagen. Do not edit.

export const BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingVideoProvider = {
  None: 'none',
  GoogleMeet: 'google_meet',
  Zoom: 'zoom',
} as const;

export type BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingVideoProvider =
  | (typeof BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingVideoProvider)[keyof typeof BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingVideoProvider]
  | (string & Record<never, never>);
