// This file is auto-generated by oagen. Do not edit.

import type { BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyData, BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataResponse } from './batch-create-product-variants-request-application-json-property-resources-item-property-deliverable-property-data.interface';
import type { BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverableTypes } from './batch-create-product-variants-request-application-json-property-resources-item-property-deliverable-types.interface';

export interface BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverable {
  types: (BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverableTypes | (string & Record<never, never>))[];
  data: BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyData;
  [key: string]: unknown;
}

export interface BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverableResponse {
  types: (BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverableTypes | (string & Record<never, never>))[];
  data: BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataResponse;
  [key: string]: unknown;
}
