// This file is auto-generated by oagen. Do not edit.

import type { GetOptions as RequestOptions } from '../../common/interfaces/get-options.interface';
import type { BatchUpdateProductVariantsRequestApplicationJsonPropertyResources } from './batch-update-product-variants-request-application-json-property-resources.interface';

export interface BatchUpdateOptions {
  /** Per-call timeout, retry, headers, cancellation, and lifecycle metadata. */
  requestOptions?: RequestOptions;
  /** The product path parameter. */
  product: number;
  resources: BatchUpdateProductVariantsRequestApplicationJsonPropertyResources;
}
