// This file is auto-generated by oagen. Do not edit.

import type { ListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData, ListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyDataResponse } from './list-product-variants-response-value-200-application-json-property-data-item-property-deliverable-property-data.interface';

export interface ListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable {
  data: ListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData;
  types: string[];
  [key: string]: unknown;
}

export interface ListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableResponse {
  data: ListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyDataResponse;
  types: string[];
  [key: string]: unknown;
}
