// This file is auto-generated by oagen. Do not edit.

import type { PaginationOptions } from '../../common/interfaces/pagination-options.interface';

export interface ProductVariantsListOptions extends PaginationOptions {
  /** The product path parameter. */
  product: number;
  /** Page number to return. */
  page?: number;
  /** Include draft variants alongside published variants. */
  withDrafts?: boolean;
  /** Return only draft variants. */
  onlyDrafts?: boolean;
}
