// This file is auto-generated by oagen. Do not edit.

export const ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency = {
  Aud: 'AUD',
  Brl: 'BRL',
  Cad: 'CAD',
  Cny: 'CNY',
  Czk: 'CZK',
  Dkk: 'DKK',
  Eur: 'EUR',
  Ghs: 'GHS',
  Hkd: 'HKD',
  Huf: 'HUF',
  Ils: 'ILS',
  Inr: 'INR',
  Jpy: 'JPY',
  Myr: 'MYR',
  Mxn: 'MXN',
  Ngn: 'NGN',
  Twd: 'TWD',
  Nzd: 'NZD',
  Nok: 'NOK',
  Php: 'PHP',
  Pln: 'PLN',
  Gbp: 'GBP',
  Rub: 'RUB',
  Sgd: 'SGD',
  Sek: 'SEK',
  Chf: 'CHF',
  Thb: 'THB',
  Usd: 'USD',
  Zar: 'ZAR',
} as const;

export type ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency =
  | (typeof ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency)[keyof typeof ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency]
  | (string & Record<never, never>);
