// This file is auto-generated by oagen. Do not edit.

import type { CreateProductVariantResponseValue201ApplicationJsonPropertyData, CreateProductVariantResponseValue201ApplicationJsonPropertyDataResponse } from './create-product-variant-response-value-201-application-json-property-data.interface';

export interface SdkCreateProductVariantResponseValue201ApplicationJson {
  data: CreateProductVariantResponseValue201ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkCreateProductVariantResponseValue201ApplicationJsonResponse {
  data: CreateProductVariantResponseValue201ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
