// This file is auto-generated by oagen. Do not edit.

import type { UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyData, UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataResponse } from './update-product-variant-pricing-response-value-200-application-json-property-data.interface';

export interface SdkUpdateProductVariantPricingResponseValue200ApplicationJson {
  data: UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkUpdateProductVariantPricingResponseValue200ApplicationJsonResponse {
  data: UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
