// This file is auto-generated by oagen. Do not edit.

import type { BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem, BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemResponse } from './batch-create-product-variants-request-application-json-property-resources-item.interface';

export interface SdkBatchCreateProductVariantsRequestApplicationJson {
  resources: BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem[];
  [key: string]: unknown;
}

export interface SdkBatchCreateProductVariantsRequestApplicationJsonResponse {
  resources: BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemResponse[];
  [key: string]: unknown;
}
