// This file is auto-generated by oagen. Do not edit.

import type { SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable, SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableResponse } from './search-product-variants-response-value-200-application-json-property-data-item-property-deliverable.interface';
import type { SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricing, SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingResponse } from './search-product-variants-response-value-200-application-json-property-data-item-property-pricing.interface';
import type { SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyBulkDiscountItem, SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyBulkDiscountItemResponse } from './search-product-variants-response-value-200-application-json-property-data-item-property-bulk-discount-item.interface';
import type { SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings, SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettingsResponse } from './search-product-variants-response-value-200-application-json-property-data-item-property-other-settings.interface';
import type { SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct, SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProductResponse } from './search-product-variants-response-value-200-application-json-property-data-item-property-product.interface';

export interface SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem {
  id: number;
  productId: number;
  title: string;
  description: string;
  deliverable: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable;
  pricing: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricing;
  minimumPurchaseQuantity: number;
  maximumPurchaseQuantity: number | null;
  bulkDiscount: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyBulkDiscountItem[] | null;
  paymentMethods: string[];
  otherSettings: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings;
  order: number | null;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  product: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct;
  [key: string]: unknown;
}

export interface SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemResponse {
  id: number;
  product_id: number;
  title: string;
  description: string;
  deliverable: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableResponse;
  pricing: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingResponse;
  minimum_purchase_quantity: number;
  maximum_purchase_quantity: number | null;
  bulk_discount: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyBulkDiscountItemResponse[] | null;
  payment_methods: string[];
  other_settings: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettingsResponse;
  order: number | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  product: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProductResponse;
  [key: string]: unknown;
}
