// This file is auto-generated by oagen. Do not edit.

export const SearchProductVariantsRequestApplicationJsonPropertyFiltersItemType = {
  And: 'and',
  Or: 'or',
} as const;

export type SearchProductVariantsRequestApplicationJsonPropertyFiltersItemType =
  | (typeof SearchProductVariantsRequestApplicationJsonPropertyFiltersItemType)[keyof typeof SearchProductVariantsRequestApplicationJsonPropertyFiltersItemType]
  | (string & Record<never, never>);
