// This file is auto-generated by oagen. Do not edit.

import type { GetRewardRuleResponseValue200ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayload, GetRewardRuleResponseValue200ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayloadResponse } from '../interfaces/get-reward-rule-response-value-200-application-json-property-data-property-outputs-item-property-payload.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"GetRewardRuleResponseValue200ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayload","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"GetRewardRuleResponseValue200ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayload","required":[],"properties":{},"additionalProperties":true};

export const deserializeGetRewardRuleResponseValue200ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayload = (
  _response: GetRewardRuleResponseValue200ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayloadResponse,
): GetRewardRuleResponseValue200ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayload => {
  assertValidModel(_response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_response, []),
  };
};
