// This file is auto-generated by oagen. Do not edit.

import type { SdkListRewardRulesResponseValue200ApplicationJson, SdkListRewardRulesResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-list-reward-rules-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkListRewardRulesResponseValue200ApplicationJson","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkListRewardRulesResponseValue200ApplicationJson","required":[],"properties":{},"additionalProperties":true};

export const deserializeSdkListRewardRulesResponseValue200ApplicationJson = (
  _response: SdkListRewardRulesResponseValue200ApplicationJsonResponse,
): SdkListRewardRulesResponseValue200ApplicationJson => {
  assertValidModel(_response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_response, []),
  };
};
