// This file is auto-generated by oagen. Do not edit.

import type { ListSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem, ListSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItemResponse } from '../interfaces/list-sections-response-value-200-application-json-property-data-item-property-groups-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem","required":["id","title","groupProducts"],"properties":{"id":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"groupProducts":{"kind":"primitive","type":"integer"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem","required":["id","title","group_products"],"properties":{"id":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"group_products":{"kind":"primitive","type":"integer"}},"additionalProperties":true};

export const deserializeListSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem = (
  response: ListSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItemResponse,
): ListSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["id","title","group_products"]),
    id: response.id,
    title: response.title,
    groupProducts: response.group_products,
  };
};
