// This file is auto-generated by oagen. Do not edit.

export { deserializeListGroupsResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItem as deserializeReplaceSectionOrderResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItem } from '../../groups/serializers/list-groups-response-value-200-application-json-property-data-item-property-products-item.serializer';
