// This file is auto-generated by oagen. Do not edit.

import type { SdkV2BatchCreateSectionsRequestApplicationJson, SdkV2BatchCreateSectionsRequestApplicationJsonResponse } from '../interfaces/sdk-v-2-batch-create-sections-request-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { serializeV2BatchCreateSectionsRequestApplicationJsonPropertyResourcesItem } from './v-2-batch-create-sections-request-application-json-property-resources-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2BatchCreateSectionsRequestApplicationJson","required":["resources"],"properties":{"resources":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2BatchCreateSectionsRequestApplicationJson","required":["resources"],"properties":{"resources":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const serializeSdkV2BatchCreateSectionsRequestApplicationJson = (
  model: SdkV2BatchCreateSectionsRequestApplicationJson,
): SdkV2BatchCreateSectionsRequestApplicationJsonResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["resources"]),
    resources: model.resources.map(serializeV2BatchCreateSectionsRequestApplicationJsonPropertyResourcesItem),
  };
};
