// This file is auto-generated by oagen. Do not edit.

import type { SdkV2ReplyToTicketResponseValue201ApplicationJson, SdkV2ReplyToTicketResponseValue201ApplicationJsonResponse } from '../interfaces/sdk-v-2-reply-to-ticket-response-value-201-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeV2ReplyToTicketResponseValue201ApplicationJsonPropertyData } from './v-2-reply-to-ticket-response-value-201-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2ReplyToTicketResponseValue201ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2ReplyToTicketResponseValue201ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkV2ReplyToTicketResponseValue201ApplicationJson = (
  response: SdkV2ReplyToTicketResponseValue201ApplicationJsonResponse,
): SdkV2ReplyToTicketResponseValue201ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeV2ReplyToTicketResponseValue201ApplicationJsonPropertyData(response.data),
  };
};
