// This file is auto-generated by oagen. Do not edit.

import type { SdkReplyToTicketRequestApplicationJson, SdkReplyToTicketRequestApplicationJsonResponse } from '../interfaces/sdk-reply-to-ticket-request-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplyToTicketRequestApplicationJson","required":["content"],"properties":{"content":{"kind":"primitive","type":"string"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplyToTicketRequestApplicationJson","required":["content"],"properties":{"content":{"kind":"primitive","type":"string"}},"additionalProperties":true};

export const serializeSdkReplyToTicketRequestApplicationJson = (
  model: SdkReplyToTicketRequestApplicationJson,
): SdkReplyToTicketRequestApplicationJsonResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["content"]),
    content: model.content,
  };
};
