// This file is auto-generated by oagen. Do not edit.

import type { SdkSearchTicketsResponseValue200ApplicationJson, SdkSearchTicketsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-search-tickets-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeSearchTicketsResponseValue200ApplicationJsonPropertyDataItem } from './search-tickets-response-value-200-application-json-property-data-item.serializer';
import { deserializeSearchTicketsResponseValue200ApplicationJsonPropertyLinks } from './search-tickets-response-value-200-application-json-property-links.serializer';
import { deserializeSearchTicketsResponseValue200ApplicationJsonPropertyMeta } from './search-tickets-response-value-200-application-json-property-meta.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkSearchTicketsResponseValue200ApplicationJson","required":["data","links","meta"],"properties":{"data":{"kind":"array","items":{"kind":"any"}},"links":{"kind":"any"},"meta":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkSearchTicketsResponseValue200ApplicationJson","required":["data","links","meta"],"properties":{"data":{"kind":"array","items":{"kind":"any"}},"links":{"kind":"any"},"meta":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkSearchTicketsResponseValue200ApplicationJson = (
  response: SdkSearchTicketsResponseValue200ApplicationJsonResponse,
): SdkSearchTicketsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data","links","meta"]),
    data: response.data.map(deserializeSearchTicketsResponseValue200ApplicationJsonPropertyDataItem),
    links: deserializeSearchTicketsResponseValue200ApplicationJsonPropertyLinks(response.links),
    meta: deserializeSearchTicketsResponseValue200ApplicationJsonPropertyMeta(response.meta),
  };
};
