// This file is auto-generated by oagen. Do not edit.

import type { SdkV2GetFeedbackResponseValue200ApplicationJson, SdkV2GetFeedbackResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-v-2-get-feedback-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeV2GetFeedbackResponseValue200ApplicationJsonPropertyData } from './v-2-get-feedback-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2GetFeedbackResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2GetFeedbackResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkV2GetFeedbackResponseValue200ApplicationJson = (
  response: SdkV2GetFeedbackResponseValue200ApplicationJsonResponse,
): SdkV2GetFeedbackResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeV2GetFeedbackResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
