// This file is auto-generated by oagen. Do not edit.

export { serializeSdkReplaceSectionOrderRequestApplicationJson as serializeSdkV2ReplaceSectionOrderRequestApplicationJson } from './sdk-replace-section-order-request-application-json.serializer';
