// This file is auto-generated by oagen. Do not edit.

import type { SdkV2SearchCouponsResponseValue200ApplicationJson, SdkV2SearchCouponsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-v-2-search-coupons-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeV2SearchCouponsResponseValue200ApplicationJsonPropertyDataItem } from './v-2-search-coupons-response-value-200-application-json-property-data-item.serializer';
import { deserializeV2SearchCouponsResponseValue200ApplicationJsonPropertyLinks } from './v-2-search-coupons-response-value-200-application-json-property-links.serializer';
import { deserializeV2SearchCouponsResponseValue200ApplicationJsonPropertyMeta } from './v-2-search-coupons-response-value-200-application-json-property-meta.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2SearchCouponsResponseValue200ApplicationJson","required":["data","links","meta"],"properties":{"data":{"kind":"array","items":{"kind":"any"}},"links":{"kind":"any"},"meta":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2SearchCouponsResponseValue200ApplicationJson","required":["data","links","meta"],"properties":{"data":{"kind":"array","items":{"kind":"any"}},"links":{"kind":"any"},"meta":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkV2SearchCouponsResponseValue200ApplicationJson = (
  response: SdkV2SearchCouponsResponseValue200ApplicationJsonResponse,
): SdkV2SearchCouponsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data","links","meta"]),
    data: response.data.map(deserializeV2SearchCouponsResponseValue200ApplicationJsonPropertyDataItem),
    links: deserializeV2SearchCouponsResponseValue200ApplicationJsonPropertyLinks(response.links),
    meta: deserializeV2SearchCouponsResponseValue200ApplicationJsonPropertyMeta(response.meta),
  };
};
