// This file is auto-generated by oagen. Do not edit.

export { serializeSdkReplyToFeedbackRequestApplicationJson as serializeSdkV2ReplyToFeedbackRequestApplicationJson } from './sdk-reply-to-feedback-request-application-json.serializer';
