// This file is auto-generated by oagen. Do not edit.

import type { SdkV2SearchTicketsResponseValue200ApplicationJson, SdkV2SearchTicketsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-v-2-search-tickets-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeV2SearchTicketsResponseValue200ApplicationJsonPropertyDataItem } from './v-2-search-tickets-response-value-200-application-json-property-data-item.serializer';
import { deserializeV2SearchTicketsResponseValue200ApplicationJsonPropertyLinks } from './v-2-search-tickets-response-value-200-application-json-property-links.serializer';
import { deserializeV2SearchTicketsResponseValue200ApplicationJsonPropertyMeta } from './v-2-search-tickets-response-value-200-application-json-property-meta.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2SearchTicketsResponseValue200ApplicationJson","required":["data","links","meta"],"properties":{"data":{"kind":"array","items":{"kind":"any"}},"links":{"kind":"any"},"meta":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkV2SearchTicketsResponseValue200ApplicationJson","required":["data","links","meta"],"properties":{"data":{"kind":"array","items":{"kind":"any"}},"links":{"kind":"any"},"meta":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkV2SearchTicketsResponseValue200ApplicationJson = (
  response: SdkV2SearchTicketsResponseValue200ApplicationJsonResponse,
): SdkV2SearchTicketsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data","links","meta"]),
    data: response.data.map(deserializeV2SearchTicketsResponseValue200ApplicationJsonPropertyDataItem),
    links: deserializeV2SearchTicketsResponseValue200ApplicationJsonPropertyLinks(response.links),
    meta: deserializeV2SearchTicketsResponseValue200ApplicationJsonPropertyMeta(response.meta),
  };
};
