// This file is auto-generated by oagen. Do not edit.

export { serializeSearchGroupsRequestApplicationJsonPropertyIncludesItem as serializeSearchTicketMessagesRequestApplicationJsonPropertyIncludesItem } from '../../groups/serializers/search-groups-request-application-json-property-includes-item.serializer';
