// This file is auto-generated by oagen. Do not edit.

import type { V2SearchSectionsRequestApplicationJsonPropertySortItem, V2SearchSectionsRequestApplicationJsonPropertySortItemResponse } from '../interfaces/v-2-search-sections-request-application-json-property-sort-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"V2SearchSectionsRequestApplicationJsonPropertySortItem","required":["field"],"properties":{"field":{"kind":"primitive","type":"string"},"direction":{"kind":"enum","values":["asc","desc"]}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"V2SearchSectionsRequestApplicationJsonPropertySortItem","required":["field"],"properties":{"field":{"kind":"primitive","type":"string"},"direction":{"kind":"enum","values":["asc","desc"]}},"additionalProperties":true};

export const serializeV2SearchSectionsRequestApplicationJsonPropertySortItem = (
  model: V2SearchSectionsRequestApplicationJsonPropertySortItem,
): V2SearchSectionsRequestApplicationJsonPropertySortItemResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["field","direction"]),
    field: model.field,
    direction: model.direction,
  };
};
