// This file is auto-generated by oagen. Do not edit.

export { deserializeV2ListTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReadStatus as deserializeV2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyReadStatus } from './v-2-list-tickets-response-value-200-application-json-property-data-item-property-read-status.serializer';
