// This file is auto-generated by oagen. Do not edit.

import type { V2SearchTicketsRequestApplicationJsonPropertyFiltersItem, V2SearchTicketsRequestApplicationJsonPropertyFiltersItemResponse } from '../interfaces/v-2-search-tickets-request-application-json-property-filters-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { serializeV2SearchTicketsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem } from './v-2-search-tickets-request-application-json-property-filters-item-property-nested-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"V2SearchTicketsRequestApplicationJsonPropertyFiltersItem","required":[],"properties":{"field":{"kind":"primitive","type":"string"},"operator":{"kind":"primitive","type":"string"},"value":{"kind":"primitive","type":"unknown"},"type":{"kind":"enum","values":["and","or"]},"nested":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"V2SearchTicketsRequestApplicationJsonPropertyFiltersItem","required":[],"properties":{"field":{"kind":"primitive","type":"string"},"operator":{"kind":"primitive","type":"string"},"value":{"kind":"primitive","type":"unknown"},"type":{"kind":"enum","values":["and","or"]},"nested":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const serializeV2SearchTicketsRequestApplicationJsonPropertyFiltersItem = (
  model: V2SearchTicketsRequestApplicationJsonPropertyFiltersItem,
): V2SearchTicketsRequestApplicationJsonPropertyFiltersItemResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["field","operator","value","type","nested"]),
    field: model.field,
    operator: model.operator,
    value: model.value,
    type: model.type,
    nested: model.nested != null ? model.nested.map(serializeV2SearchTicketsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem) : undefined,
  };
};
