// This file is auto-generated by oagen. Do not edit.

export const CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingConflictScope = {
  Product: 'product',
  Variant: 'variant',
} as const;

export type CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingConflictScope =
  | (typeof CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingConflictScope)[keyof typeof CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingConflictScope]
  | (string & Record<never, never>);
