// This file is auto-generated by oagen. Do not edit.

import type { CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking, CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingResponse } from './create-add-on-draft-request-application-json-property-variant-property-deliverable-property-data-property-booking.interface';
import type { CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItem, CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItemResponse } from './create-add-on-draft-request-application-json-property-variant-property-deliverable-property-data-property-credit-rate-tiers-item.interface';
import type { CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataParsingMode } from './create-add-on-draft-request-application-json-property-variant-property-deliverable-property-data-parsing-mode.interface';

export interface CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyData {
  stock?: number | null;
  serials?: string[];
  removeDuplicate?: boolean;
  parsingMode?: CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataParsingMode | (string & Record<never, never>);
  comment?: string;
  webhook?: string;
  booking?: CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking;
  /** Tiered unit prices for credit products. Credit products must include at least one priced tier. */
  creditRateTiers?: CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItem[];
  [key: string]: unknown;
}

export interface CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataResponse {
  stock?: number | null;
  serials?: string[];
  remove_duplicate?: boolean;
  parsing_mode?: CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataParsingMode | (string & Record<never, never>);
  comment?: string;
  webhook?: string;
  booking?: CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingResponse;
  credit_rate_tiers?: CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItemResponse[];
  [key: string]: unknown;
}
