// This file is auto-generated by oagen. Do not edit.

export type SdkSearchAddOnsResponseValue200ApplicationJson = Record<string, unknown>;

export type SdkSearchAddOnsResponseValue200ApplicationJsonResponse = Record<string, unknown>;
