// This file is auto-generated by oagen. Do not edit.

import type { SearchAddOnsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem, SearchAddOnsRequestApplicationJsonPropertyFiltersItemPropertyNestedItemResponse } from './search-add-ons-request-application-json-property-filters-item-property-nested-item.interface';
import type { SearchAddOnsRequestApplicationJsonPropertyFiltersItemType } from './search-add-ons-request-application-json-property-filters-item-type.interface';

export interface SearchAddOnsRequestApplicationJsonPropertyFiltersItem {
  field?: string;
  /** @default "=" */
  operator?: string;
  value?: any;
  /** @default "and" */
  type?: SearchAddOnsRequestApplicationJsonPropertyFiltersItemType | (string & Record<never, never>);
  nested?: SearchAddOnsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem[];
  [key: string]: unknown;
}

export interface SearchAddOnsRequestApplicationJsonPropertyFiltersItemResponse {
  field?: string;
  operator?: string;
  value?: any;
  type?: SearchAddOnsRequestApplicationJsonPropertyFiltersItemType | (string & Record<never, never>);
  nested?: SearchAddOnsRequestApplicationJsonPropertyFiltersItemPropertyNestedItemResponse[];
  [key: string]: unknown;
}
