// This file is auto-generated by oagen. Do not edit.

import type { CreateCourseLessonResponseValue201ApplicationJsonPropertyData, CreateCourseLessonResponseValue201ApplicationJsonPropertyDataResponse } from '../interfaces/create-course-lesson-response-value-201-application-json-property-data.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo } from './create-course-lesson-response-value-201-application-json-property-data-property-video.serializer';
import { deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyAttachmentsItem } from './create-course-lesson-response-value-201-application-json-property-data-property-attachments-item.serializer';
import { deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyAssignment } from './create-course-lesson-response-value-201-application-json-property-data-property-assignment.serializer';
import { deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItem } from './create-course-lesson-response-value-201-application-json-property-data-property-questions-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"CreateCourseLessonResponseValue201ApplicationJsonPropertyData","required":["id","sectionId","title","content","type","isPreview","isPublished","sortOrder","video","attachments","assignment","questions","createdAt","updatedAt"],"properties":{"id":{"kind":"primitive","type":"integer"},"sectionId":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"content":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"type":{"kind":"enum","values":["lecture","video","text","quiz","assignment"]},"isPreview":{"kind":"primitive","type":"boolean"},"isPublished":{"kind":"primitive","type":"boolean"},"sortOrder":{"kind":"primitive","type":"integer","constraints":{"minimum":1}},"video":{"kind":"nullable","inner":{"kind":"any"}},"attachments":{"kind":"array","items":{"kind":"any"}},"assignment":{"kind":"nullable","inner":{"kind":"any"}},"questions":{"kind":"array","items":{"kind":"any"}},"createdAt":{"kind":"primitive","type":"string","format":"date-time"},"updatedAt":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"CreateCourseLessonResponseValue201ApplicationJsonPropertyData","required":["id","section_id","title","content","type","is_preview","is_published","sort_order","video","attachments","assignment","questions","created_at","updated_at"],"properties":{"id":{"kind":"primitive","type":"integer"},"section_id":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"content":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"type":{"kind":"enum","values":["lecture","video","text","quiz","assignment"]},"is_preview":{"kind":"primitive","type":"boolean"},"is_published":{"kind":"primitive","type":"boolean"},"sort_order":{"kind":"primitive","type":"integer","constraints":{"minimum":1}},"video":{"kind":"nullable","inner":{"kind":"any"}},"attachments":{"kind":"array","items":{"kind":"any"}},"assignment":{"kind":"nullable","inner":{"kind":"any"}},"questions":{"kind":"array","items":{"kind":"any"}},"created_at":{"kind":"primitive","type":"string","format":"date-time"},"updated_at":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};

export const deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyData = (
  response: CreateCourseLessonResponseValue201ApplicationJsonPropertyDataResponse,
): CreateCourseLessonResponseValue201ApplicationJsonPropertyData => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["id","section_id","title","content","type","is_preview","is_published","sort_order","video","attachments","assignment","questions","created_at","updated_at"]),
    id: response.id,
    sectionId: response.section_id,
    title: response.title,
    content: response.content ?? null,
    type: response.type,
    isPreview: response.is_preview,
    isPublished: response.is_published,
    sortOrder: response.sort_order,
    video: response.video != null ? deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo(response.video) : null,
    attachments: response.attachments.map(deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyAttachmentsItem),
    assignment: response.assignment != null ? deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyAssignment(response.assignment) : null,
    questions: response.questions.map(deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItem),
    createdAt: new Date(response.created_at),
    updatedAt: new Date(response.updated_at),
  };
};
