// This file is auto-generated by oagen. Do not edit.

import type { CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo, CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideoResponse } from '../interfaces/create-course-lesson-response-value-201-application-json-property-data-property-video.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo","required":["source","externalUrl","muxPlaybackId","muxStatus","durationSeconds"],"properties":{"source":{"kind":"enum","values":["mux","external"]},"externalUrl":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"uri"}},"muxPlaybackId":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"muxStatus":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"durationSeconds":{"kind":"nullable","inner":{"kind":"primitive","type":"integer","constraints":{"minimum":0}}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo","required":["source","external_url","mux_playback_id","mux_status","duration_seconds"],"properties":{"source":{"kind":"enum","values":["mux","external"]},"external_url":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"uri"}},"mux_playback_id":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"mux_status":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"duration_seconds":{"kind":"nullable","inner":{"kind":"primitive","type":"integer","constraints":{"minimum":0}}}},"additionalProperties":true};

export const deserializeCreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo = (
  response: CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideoResponse,
): CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["source","external_url","mux_playback_id","mux_status","duration_seconds"]),
    source: response.source,
    externalUrl: response.external_url ?? null,
    muxPlaybackId: response.mux_playback_id ?? null,
    muxStatus: response.mux_status ?? null,
    durationSeconds: response.duration_seconds ?? null,
  };
};
