// This file is auto-generated by oagen. Do not edit.

import type { SdkCreateCourseLessonRequestApplicationJson, SdkCreateCourseLessonRequestApplicationJsonResponse } from '../interfaces/sdk-create-course-lesson-request-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { serializeCreateCourseLessonRequestApplicationJsonPropertyAssignment } from './create-course-lesson-request-application-json-property-assignment.serializer';
import { serializeCreateCourseLessonRequestApplicationJsonPropertyQuestionsItem } from './create-course-lesson-request-application-json-property-questions-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkCreateCourseLessonRequestApplicationJson","required":["title","type"],"properties":{"title":{"kind":"primitive","type":"string","constraints":{"maxLength":255}},"type":{"kind":"enum","values":["lecture","video","text","quiz","assignment"]},"content":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"isPreview":{"kind":"primitive","type":"boolean"},"isPublished":{"kind":"primitive","type":"boolean"},"assignment":{"kind":"any"},"questions":{"kind":"array","items":{"kind":"any"},"constraints":{"maxItems":12}},"expectedUpdatedAt":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkCreateCourseLessonRequestApplicationJson","required":["title","type"],"properties":{"title":{"kind":"primitive","type":"string","constraints":{"maxLength":255}},"type":{"kind":"enum","values":["lecture","video","text","quiz","assignment"]},"content":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"is_preview":{"kind":"primitive","type":"boolean"},"is_published":{"kind":"primitive","type":"boolean"},"assignment":{"kind":"any"},"questions":{"kind":"array","items":{"kind":"any"},"constraints":{"maxItems":12}},"expected_updated_at":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};

export const serializeSdkCreateCourseLessonRequestApplicationJson = (
  model: SdkCreateCourseLessonRequestApplicationJson,
): SdkCreateCourseLessonRequestApplicationJsonResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["title","type","content","isPreview","isPublished","assignment","questions","expectedUpdatedAt"]),
    title: model.title,
    type: model.type,
    content: model.content,
    is_preview: model.isPreview,
    is_published: model.isPublished,
    assignment: model.assignment != null ? serializeCreateCourseLessonRequestApplicationJsonPropertyAssignment(model.assignment) : undefined,
    questions: model.questions != null ? model.questions.map(serializeCreateCourseLessonRequestApplicationJsonPropertyQuestionsItem) : undefined,
    expected_updated_at: model.expectedUpdatedAt != null ? model.expectedUpdatedAt.toISOString() : undefined,
  };
};
