// This file is auto-generated by oagen. Do not edit.

import type { SdkReorderCourseLessonsResponseValue200ApplicationJson, SdkReorderCourseLessonsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-reorder-course-lessons-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeReorderCourseLessonsResponseValue200ApplicationJsonPropertyData } from './reorder-course-lessons-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkReorderCourseLessonsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkReorderCourseLessonsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkReorderCourseLessonsResponseValue200ApplicationJson = (
  response: SdkReorderCourseLessonsResponseValue200ApplicationJsonResponse,
): SdkReorderCourseLessonsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeReorderCourseLessonsResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
