// This file is auto-generated by oagen. Do not edit.

import type { UpdateCourseLessonResponseValue200ApplicationJsonPropertyData, UpdateCourseLessonResponseValue200ApplicationJsonPropertyDataResponse } from '../interfaces/update-course-lesson-response-value-200-application-json-property-data.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeUpdateCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideo } from './update-course-lesson-response-value-200-application-json-property-data-property-video.serializer';
import { deserializeUpdateCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAttachmentsItem } from './update-course-lesson-response-value-200-application-json-property-data-property-attachments-item.serializer';
import { deserializeUpdateCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignment } from './update-course-lesson-response-value-200-application-json-property-data-property-assignment.serializer';
import { deserializeUpdateCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyQuestionsItem } from './update-course-lesson-response-value-200-application-json-property-data-property-questions-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"UpdateCourseLessonResponseValue200ApplicationJsonPropertyData","required":["id","sectionId","title","content","type","isPreview","isPublished","sortOrder","video","attachments","assignment","questions","createdAt","updatedAt"],"properties":{"id":{"kind":"primitive","type":"integer"},"sectionId":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"content":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"type":{"kind":"enum","values":["lecture","video","text","quiz","assignment"]},"isPreview":{"kind":"primitive","type":"boolean"},"isPublished":{"kind":"primitive","type":"boolean"},"sortOrder":{"kind":"primitive","type":"integer","constraints":{"minimum":1}},"video":{"kind":"nullable","inner":{"kind":"any"}},"attachments":{"kind":"array","items":{"kind":"any"}},"assignment":{"kind":"nullable","inner":{"kind":"any"}},"questions":{"kind":"array","items":{"kind":"any"}},"createdAt":{"kind":"primitive","type":"string","format":"date-time"},"updatedAt":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"UpdateCourseLessonResponseValue200ApplicationJsonPropertyData","required":["id","section_id","title","content","type","is_preview","is_published","sort_order","video","attachments","assignment","questions","created_at","updated_at"],"properties":{"id":{"kind":"primitive","type":"integer"},"section_id":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"content":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"type":{"kind":"enum","values":["lecture","video","text","quiz","assignment"]},"is_preview":{"kind":"primitive","type":"boolean"},"is_published":{"kind":"primitive","type":"boolean"},"sort_order":{"kind":"primitive","type":"integer","constraints":{"minimum":1}},"video":{"kind":"nullable","inner":{"kind":"any"}},"attachments":{"kind":"array","items":{"kind":"any"}},"assignment":{"kind":"nullable","inner":{"kind":"any"}},"questions":{"kind":"array","items":{"kind":"any"}},"created_at":{"kind":"primitive","type":"string","format":"date-time"},"updated_at":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};

export const deserializeUpdateCourseLessonResponseValue200ApplicationJsonPropertyData = (
  response: UpdateCourseLessonResponseValue200ApplicationJsonPropertyDataResponse,
): UpdateCourseLessonResponseValue200ApplicationJsonPropertyData => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["id","section_id","title","content","type","is_preview","is_published","sort_order","video","attachments","assignment","questions","created_at","updated_at"]),
    id: response.id,
    sectionId: response.section_id,
    title: response.title,
    content: response.content ?? null,
    type: response.type,
    isPreview: response.is_preview,
    isPublished: response.is_published,
    sortOrder: response.sort_order,
    video: response.video != null ? deserializeUpdateCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideo(response.video) : null,
    attachments: response.attachments.map(deserializeUpdateCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAttachmentsItem),
    assignment: response.assignment != null ? deserializeUpdateCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignment(response.assignment) : null,
    questions: response.questions.map(deserializeUpdateCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyQuestionsItem),
    createdAt: new Date(response.created_at),
    updatedAt: new Date(response.updated_at),
  };
};
