// This file is auto-generated by oagen. Do not edit.

export const CreateOrderReplacementResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItemStatus = {
  Pending: 'PENDING',
  Reversed: 'REVERSED',
  Partial: 'PARTIAL',
  Voided: 'VOIDED',
  Refunded: 'REFUNDED',
  Paid: 'PAID',
  Completed: 'COMPLETED',
  Disputing: 'DISPUTING',
  Review: 'REVIEW',
  Failed: 'FAILED',
} as const;

export type CreateOrderReplacementResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItemStatus =
  | (typeof CreateOrderReplacementResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItemStatus)[keyof typeof CreateOrderReplacementResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItemStatus]
  | (string & Record<never, never>);
