// This file is auto-generated by oagen. Do not edit.

import type { CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderPropertyLineItemsItemStatus } from './create-order-refund-response-value-200-application-json-property-data-property-order-property-line-items-item-status.interface';

export interface CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderPropertyLineItemsItem {
  id: number;
  productId: number | null;
  productVariantId: number | null;
  productTitle: string | null;
  variantTitle: string | null;
  quantity: number;
  status: CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderPropertyLineItemsItemStatus | (string & Record<never, never>);
  currency: string | null;
  subtotalCents: number | null;
  totalExclusiveCents: number | null;
  totalCents: number;
  subscriptionId: number | null;
  createdAt: Date | null;
  [key: string]: unknown;
}

export interface CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderPropertyLineItemsItemResponse {
  id: number;
  product_id: number | null;
  product_variant_id: number | null;
  product_title: string | null;
  variant_title: string | null;
  quantity: number;
  status: CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderPropertyLineItemsItemStatus | (string & Record<never, never>);
  currency: string | null;
  subtotal_cents: number | null;
  total_exclusive_cents: number | null;
  total_cents: number;
  subscription_id: number | null;
  created_at: string | null;
  [key: string]: unknown;
}
