// This file is auto-generated by oagen. Do not edit.

export const PayOrderFromWalletResponseValue200ApplicationJsonPropertyDataStatus = {
  Pending: 'PENDING',
  Reversed: 'REVERSED',
  Partial: 'PARTIAL',
  Voided: 'VOIDED',
  Refunded: 'REFUNDED',
  Paid: 'PAID',
  Completed: 'COMPLETED',
  Disputing: 'DISPUTING',
  Review: 'REVIEW',
  Failed: 'FAILED',
} as const;

export type PayOrderFromWalletResponseValue200ApplicationJsonPropertyDataStatus =
  | (typeof PayOrderFromWalletResponseValue200ApplicationJsonPropertyDataStatus)[keyof typeof PayOrderFromWalletResponseValue200ApplicationJsonPropertyDataStatus]
  | (string & Record<never, never>);
