// This file is auto-generated by oagen. Do not edit.

export const RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyLineItemsItemStatus = {
  Pending: 'PENDING',
  Reversed: 'REVERSED',
  Partial: 'PARTIAL',
  Voided: 'VOIDED',
  Refunded: 'REFUNDED',
  Paid: 'PAID',
  Completed: 'COMPLETED',
  Disputing: 'DISPUTING',
  Review: 'REVIEW',
  Failed: 'FAILED',
} as const;

export type RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyLineItemsItemStatus =
  | (typeof RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyLineItemsItemStatus)[keyof typeof RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyLineItemsItemStatus]
  | (string & Record<never, never>);
