// This file is auto-generated by oagen. Do not edit.

export const RetryOrderFulfillmentResponseValue200ApplicationJsonPropertyDataPropertyTimelineItemStatus = {
  Pending: 'PENDING',
  Reversed: 'REVERSED',
  Partial: 'PARTIAL',
  Voided: 'VOIDED',
  Refunded: 'REFUNDED',
  Paid: 'PAID',
  Completed: 'COMPLETED',
  Disputing: 'DISPUTING',
  Review: 'REVIEW',
  Failed: 'FAILED',
} as const;

export type RetryOrderFulfillmentResponseValue200ApplicationJsonPropertyDataPropertyTimelineItemStatus =
  | (typeof RetryOrderFulfillmentResponseValue200ApplicationJsonPropertyDataPropertyTimelineItemStatus)[keyof typeof RetryOrderFulfillmentResponseValue200ApplicationJsonPropertyDataPropertyTimelineItemStatus]
  | (string & Record<never, never>);
