// This file is auto-generated by oagen. Do not edit.

import type { SdkCreateFulfillmentNotificationsRequestApplicationJson, SdkCreateFulfillmentNotificationsRequestApplicationJsonResponse } from '../../invoices/interfaces/sdk-create-fulfillment-notifications-request-application-json.interface';

export type SdkSendOrderFulfillmentNotificationsRequestApplicationJson = SdkCreateFulfillmentNotificationsRequestApplicationJson;
export type SdkSendOrderFulfillmentNotificationsRequestApplicationJsonResponse = SdkCreateFulfillmentNotificationsRequestApplicationJsonResponse;
