// This file is auto-generated by oagen. Do not edit.

import type { CreateOrderResponseValue201ApplicationJsonPropertyData, CreateOrderResponseValue201ApplicationJsonPropertyDataResponse } from './create-order-response-value-201-application-json-property-data.interface';

export interface SdkCreateOrderResponseValue201ApplicationJson {
  data: CreateOrderResponseValue201ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkCreateOrderResponseValue201ApplicationJsonResponse {
  data: CreateOrderResponseValue201ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
