// This file is auto-generated by oagen. Do not edit.

export const SdkUpdateOrderStatusRequestApplicationJsonStatus = {
  Completed: 'COMPLETED',
  Voided: 'VOIDED',
  Review: 'REVIEW',
  Disputing: 'DISPUTING',
} as const;

export type SdkUpdateOrderStatusRequestApplicationJsonStatus =
  | (typeof SdkUpdateOrderStatusRequestApplicationJsonStatus)[keyof typeof SdkUpdateOrderStatusRequestApplicationJsonStatus]
  | (string & Record<never, never>);
