// This file is auto-generated by oagen. Do not edit.

import type { ExpectedStatus } from '../../invoices/interfaces/expected-status.interface';

export interface SdkPayOrderFromWalletRequestApplicationJson {
  expectedStatus?: ExpectedStatus | (string & Record<never, never>) | null;
  [key: string]: unknown;
}

export interface SdkPayOrderFromWalletRequestApplicationJsonResponse {
  expected_status?: ExpectedStatus | (string & Record<never, never>) | null;
  [key: string]: unknown;
}
