// This file is auto-generated by oagen. Do not edit.

import type { UpdateOrderStatusResponseValue200ApplicationJsonPropertyData, UpdateOrderStatusResponseValue200ApplicationJsonPropertyDataResponse } from './update-order-status-response-value-200-application-json-property-data.interface';

export interface SdkUpdateOrderStatusResponseValue200ApplicationJson {
  data: UpdateOrderStatusResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkUpdateOrderStatusResponseValue200ApplicationJsonResponse {
  data: UpdateOrderStatusResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
