// This file is auto-generated by oagen. Do not edit.

import type { CreateWalletOrderResponseValue201ApplicationJsonPropertyData, CreateWalletOrderResponseValue201ApplicationJsonPropertyDataResponse } from './create-wallet-order-response-value-201-application-json-property-data.interface';

export interface SdkCreateWalletOrderResponseValue201ApplicationJson {
  data: CreateWalletOrderResponseValue201ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkCreateWalletOrderResponseValue201ApplicationJsonResponse {
  data: CreateWalletOrderResponseValue201ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
