// This file is auto-generated by oagen. Do not edit.

import type { SearchOrdersRequestApplicationJsonPropertySortItemDirection } from './search-orders-request-application-json-property-sort-item-direction.interface';

export interface SearchOrdersRequestApplicationJsonPropertySortItem {
  field: 'created_at';
  direction: SearchOrdersRequestApplicationJsonPropertySortItemDirection | (string & Record<never, never>);
  [key: string]: unknown;
}

export interface SearchOrdersRequestApplicationJsonPropertySortItemResponse {
  field: 'created_at';
  direction: SearchOrdersRequestApplicationJsonPropertySortItemDirection | (string & Record<never, never>);
  [key: string]: unknown;
}
