// This file is auto-generated by oagen. Do not edit.

export const SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyTimelineItemStatus = {
  Pending: 'PENDING',
  Reversed: 'REVERSED',
  Partial: 'PARTIAL',
  Voided: 'VOIDED',
  Refunded: 'REFUNDED',
  Paid: 'PAID',
  Completed: 'COMPLETED',
  Disputing: 'DISPUTING',
  Review: 'REVIEW',
  Failed: 'FAILED',
} as const;

export type SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyTimelineItemStatus =
  | (typeof SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyTimelineItemStatus)[keyof typeof SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyTimelineItemStatus]
  | (string & Record<never, never>);
