// This file is auto-generated by oagen. Do not edit.

import type { GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem, GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItemResponse } from '../interfaces/get-booking-configuration-response-value-200-application-json-property-data-property-availability-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem","required":["day","enabled","start","end"],"properties":{"day":{"kind":"primitive","type":"integer","constraints":{"minimum":1,"maximum":7}},"enabled":{"kind":"primitive","type":"boolean"},"start":{"kind":"primitive","type":"string"},"end":{"kind":"primitive","type":"string"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem","required":["day","enabled","start","end"],"properties":{"day":{"kind":"primitive","type":"integer","constraints":{"minimum":1,"maximum":7}},"enabled":{"kind":"primitive","type":"boolean"},"start":{"kind":"primitive","type":"string"},"end":{"kind":"primitive","type":"string"}},"additionalProperties":true};

export const deserializeGetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem = (
  response: GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItemResponse,
): GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["day","enabled","start","end"]),
    day: response.day,
    enabled: response.enabled,
    start: response.start,
    end: response.end,
  };
};

export const serializeGetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem = (
  model: GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem,
): GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItemResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["day","enabled","start","end"]),
    day: model.day,
    enabled: model.enabled,
    start: model.start,
    end: model.end,
  };
};
