// This file is auto-generated by oagen. Do not edit.

import type { GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMeta, GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMetaResponse } from '../interfaces/get-booking-configuration-response-value-200-application-json-property-data-property-meta.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMeta","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMeta","required":[],"properties":{},"additionalProperties":true};

export const deserializeGetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMeta = (
  _response: GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMetaResponse,
): GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMeta => {
  assertValidModel(_response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_response, []),
  };
};
