// This file is auto-generated by oagen. Do not edit.

import type { SdkAddHighlightMediaResponseValue201ApplicationJson, SdkAddHighlightMediaResponseValue201ApplicationJsonResponse } from '../interfaces/sdk-add-highlight-media-response-value-201-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeAddHighlightMediaResponseValue201ApplicationJsonPropertyData } from './add-highlight-media-response-value-201-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkAddHighlightMediaResponseValue201ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkAddHighlightMediaResponseValue201ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkAddHighlightMediaResponseValue201ApplicationJson = (
  response: SdkAddHighlightMediaResponseValue201ApplicationJsonResponse,
): SdkAddHighlightMediaResponseValue201ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeAddHighlightMediaResponseValue201ApplicationJsonPropertyData(response.data),
  };
};
