// This file is auto-generated by oagen. Do not edit.

import type { SdkReplaceHighlightResponseValue200ApplicationJson, SdkReplaceHighlightResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-replace-highlight-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeReplaceHighlightResponseValue200ApplicationJsonPropertyData } from './replace-highlight-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceHighlightResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceHighlightResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkReplaceHighlightResponseValue200ApplicationJson = (
  response: SdkReplaceHighlightResponseValue200ApplicationJsonResponse,
): SdkReplaceHighlightResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeReplaceHighlightResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
