// This file is auto-generated by oagen. Do not edit.

import type { ReplaceRewardRuleResponseValue200ApplicationJsonPropertyData, ReplaceRewardRuleResponseValue200ApplicationJsonPropertyDataResponse } from './replace-reward-rule-response-value-200-application-json-property-data.interface';

export interface SdkReplaceRewardRuleResponseValue200ApplicationJson {
  data: ReplaceRewardRuleResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkReplaceRewardRuleResponseValue200ApplicationJsonResponse {
  data: ReplaceRewardRuleResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
