// This file is auto-generated by oagen. Do not edit.

export const SearchRewardRulesRequestApplicationJsonPropertySortItemDirection = {
  Asc: 'asc',
  Desc: 'desc',
} as const;

export type SearchRewardRulesRequestApplicationJsonPropertySortItemDirection =
  | (typeof SearchRewardRulesRequestApplicationJsonPropertySortItemDirection)[keyof typeof SearchRewardRulesRequestApplicationJsonPropertySortItemDirection]
  | (string & Record<never, never>);
