// This file is auto-generated by oagen. Do not edit.

import type { GetOptions as RequestOptions } from '../../common/interfaces/get-options.interface';
import type { SdkUpdateRewardRuleRequestApplicationJsonTriggerType } from './sdk-update-reward-rule-request-application-json-trigger-type.interface';
import type { UpdateRewardRuleRequestApplicationJsonPropertyOutputsItem } from './update-reward-rule-request-application-json-property-outputs-item.interface';

export interface UpdateOptions {
  /** Per-call timeout, retry, headers, cancellation, and lifecycle metadata. */
  requestOptions?: RequestOptions;
  /** The rewardRule path parameter. */
  rewardRule: number;
  name?: string;
  description?: string | null;
  isActive?: boolean;
  triggerType?: SdkUpdateRewardRuleRequestApplicationJsonTriggerType | (string & Record<never, never>);
  triggerThreshold?: number;
  outputs?: UpdateRewardRuleRequestApplicationJsonPropertyOutputsItem[];
  expectedUpdatedAt?: Date;
}
