// This file is auto-generated by oagen. Do not edit.

import type { SdkSendTestWebhookResponseValue200ApplicationJson, SdkSendTestWebhookResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-send-test-webhook-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeSendTestWebhookResponseValue200ApplicationJsonPropertyData } from './send-test-webhook-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkSendTestWebhookResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkSendTestWebhookResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkSendTestWebhookResponseValue200ApplicationJson = (
  response: SdkSendTestWebhookResponseValue200ApplicationJsonResponse,
): SdkSendTestWebhookResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeSendTestWebhookResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
