// This file is auto-generated by oagen. Do not edit.

import type { SendTestWebhookResponseValue200ApplicationJsonPropertyData, SendTestWebhookResponseValue200ApplicationJsonPropertyDataResponse } from '../interfaces/send-test-webhook-response-value-200-application-json-property-data.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SendTestWebhookResponseValue200ApplicationJsonPropertyData","required":["channelId","event","status"],"properties":{"channelId":{"kind":"primitive","type":"string","format":"uuid"},"event":{"kind":"enum","values":["booking.cancelled","booking.rescheduled","cash_app.payment_requires_attention","charge.completed","charge.created","charge.disputed","charge.partial_paid","charge.review","feedback.created","order.completed","order.created","order.disputed","order.manual_payment_completed","order.paid","order.partial_paid","product.created","product.trashed","product.updated","subscription.cancelled","subscription.created","subscription.renewed","ticket_message.created","variant.created","variant.sold_out","variant.updated"]},"status":{"kind":"literal","value":"delivered"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SendTestWebhookResponseValue200ApplicationJsonPropertyData","required":["channel_id","event","status"],"properties":{"channel_id":{"kind":"primitive","type":"string","format":"uuid"},"event":{"kind":"enum","values":["booking.cancelled","booking.rescheduled","cash_app.payment_requires_attention","charge.completed","charge.created","charge.disputed","charge.partial_paid","charge.review","feedback.created","order.completed","order.created","order.disputed","order.manual_payment_completed","order.paid","order.partial_paid","product.created","product.trashed","product.updated","subscription.cancelled","subscription.created","subscription.renewed","ticket_message.created","variant.created","variant.sold_out","variant.updated"]},"status":{"kind":"literal","value":"delivered"}},"additionalProperties":true};

export const deserializeSendTestWebhookResponseValue200ApplicationJsonPropertyData = (
  response: SendTestWebhookResponseValue200ApplicationJsonPropertyDataResponse,
): SendTestWebhookResponseValue200ApplicationJsonPropertyData => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["channel_id","event","status"]),
    channelId: response.channel_id,
    event: response.event,
    status: response.status,
  };
};
