// This file is auto-generated by oagen. Do not edit.

export const GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType = {
  Instructions: 'instructions',
  Redirect: 'redirect',
} as const;

export type GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType =
  | (typeof GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType)[keyof typeof GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType]
  | (string & Record<never, never>);
