// This file is auto-generated by oagen. Do not edit.

export const SdkCreateCustomPaymentMethodRequestApplicationJsonType = {
  Instructions: 'instructions',
  Redirect: 'redirect',
} as const;

export type SdkCreateCustomPaymentMethodRequestApplicationJsonType =
  | (typeof SdkCreateCustomPaymentMethodRequestApplicationJsonType)[keyof typeof SdkCreateCustomPaymentMethodRequestApplicationJsonType]
  | (string & Record<never, never>);
