// This file is auto-generated by oagen. Do not edit.

import type { GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyData, GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataResponse } from './get-payment-method-status-response-value-200-application-json-property-data.interface';

export interface SdkGetPaymentMethodStatusResponseValue200ApplicationJson {
  data: GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkGetPaymentMethodStatusResponseValue200ApplicationJsonResponse {
  data: GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
