// This file is auto-generated by oagen. Do not edit.

import type { SdkPreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJson, SdkPreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-preview-customer-subscription-renewal-date-change-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializePreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyData } from './preview-customer-subscription-renewal-date-change-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkPreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkPreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkPreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJson = (
  response: SdkPreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonResponse,
): SdkPreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializePreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
