// This file is auto-generated by oagen. Do not edit.

import type { SdkGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJson, SdkGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-get-customer-portal-subscription-capabilities-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJsonPropertyData } from './get-customer-portal-subscription-capabilities-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJson = (
  response: SdkGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJsonResponse,
): SdkGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
