// This file is auto-generated by oagen. Do not edit.

import type { SdkResumeCustomerSubscriptionResponseValue200ApplicationJson, SdkResumeCustomerSubscriptionResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-resume-customer-subscription-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyData } from './resume-customer-subscription-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkResumeCustomerSubscriptionResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkResumeCustomerSubscriptionResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkResumeCustomerSubscriptionResponseValue200ApplicationJson = (
  response: SdkResumeCustomerSubscriptionResponseValue200ApplicationJsonResponse,
): SdkResumeCustomerSubscriptionResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
