// This file is auto-generated by oagen. Do not edit.

import type { GetOptions as RequestOptions } from '../../common/interfaces/get-options.interface';
import type { ExchangeOAuthTokenRequestApplicationXWwwFormUrlencodedOneOfValue1 } from './exchange-oauth-token-request-application-x-www-form-urlencoded-one-of-value-1.interface';
import type { ExchangeOAuthTokenRequestApplicationXWwwFormUrlencodedOneOfValue2 } from './exchange-oauth-token-request-application-x-www-form-urlencoded-one-of-value-2.interface';

export type ExchangeOAuthTokenOptions = {
  /** Per-call timeout, retry, headers, cancellation, and lifecycle metadata. */
  requestOptions?: RequestOptions;
} & (ExchangeOAuthTokenRequestApplicationXWwwFormUrlencodedOneOfValue1 | ExchangeOAuthTokenRequestApplicationXWwwFormUrlencodedOneOfValue2);
