// This file is auto-generated by oagen. Do not edit.

import type { SdkGetExportResponseValue200ApplicationJson, SdkGetExportResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-get-export-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeGetExportResponseValue200ApplicationJsonPropertyData } from './get-export-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkGetExportResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkGetExportResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkGetExportResponseValue200ApplicationJson = (
  response: SdkGetExportResponseValue200ApplicationJsonResponse,
): SdkGetExportResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeGetExportResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
