// This file is auto-generated by oagen. Do not edit.

import type { SearchUpsellOffersRequestApplicationJsonPropertySortItem, SearchUpsellOffersRequestApplicationJsonPropertySortItemResponse } from '../interfaces/search-upsell-offers-request-application-json-property-sort-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SearchUpsellOffersRequestApplicationJsonPropertySortItem","required":["field"],"properties":{"field":{"kind":"primitive","type":"string"},"direction":{"kind":"enum","values":["asc","desc"]}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SearchUpsellOffersRequestApplicationJsonPropertySortItem","required":["field"],"properties":{"field":{"kind":"primitive","type":"string"},"direction":{"kind":"enum","values":["asc","desc"]}},"additionalProperties":true};

export const serializeSearchUpsellOffersRequestApplicationJsonPropertySortItem = (
  model: SearchUpsellOffersRequestApplicationJsonPropertySortItem,
): SearchUpsellOffersRequestApplicationJsonPropertySortItemResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["field","direction"]),
    field: model.field,
    direction: model.direction,
  };
};
