// This file is auto-generated by oagen. Do not edit.

export const ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItemStatus = {
  Active: 'active',
  Frozen: 'frozen',
} as const;

export type ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItemStatus =
  | (typeof ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItemStatus)[keyof typeof ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItemStatus]
  | (string & Record<never, never>);
