// This file is auto-generated by oagen. Do not edit.

import type { SdkCreateWalletTopUpRequestApplicationJsonPaymentMethod } from './sdk-create-wallet-top-up-request-application-json-payment-method.interface';

export interface SdkCreateWalletTopUpRequestApplicationJson {
  /** Deposit in integer USD cents: 2500 means $25.00. The store's minimum and maximum top-up amounts also apply. */
  amountCents: number;
  /** One enabled payment gateway allowed by the store's wallet settings for USD. CUSTOM_PAYMENT_METHOD also requires custom_payment_method_id. */
  paymentMethod: SdkCreateWalletTopUpRequestApplicationJsonPaymentMethod | (string & Record<never, never>);
  /** Enabled custom method in this store. Required for CUSTOM_PAYMENT_METHOD; omit or use null for other gateways. */
  customPaymentMethodId?: string | null;
  [key: string]: unknown;
}

export interface SdkCreateWalletTopUpRequestApplicationJsonResponse {
  amount_cents: number;
  payment_method: SdkCreateWalletTopUpRequestApplicationJsonPaymentMethod | (string & Record<never, never>);
  custom_payment_method_id?: string | null;
  [key: string]: unknown;
}
