// This file is auto-generated by oagen. Do not edit.

import type { GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyDefaultVariantValuePropertyRateTiersItem, GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyDefaultVariantValuePropertyRateTiersItemResponse } from './get-credits-product-response-value-200-application-json-property-data-property-default-variant-value-property-rate-tiers-item.interface';

/** The single sellable variant, or null when zero or multiple variants exist. When null, variant_invariant explains the issue. */
export interface GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyDefaultVariant {
  id: number;
  priceCents: number;
  currency: string;
  minimumPurchaseQuantity: number;
  maximumPurchaseQuantity?: number | null;
  quantityIncrement: number;
  stock?: number | null;
  paymentMethods: string[];
  rateTiers: GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyDefaultVariantValuePropertyRateTiersItem[];
  [key: string]: unknown;
}

export interface GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyDefaultVariantResponse {
  id: number;
  price_cents: number;
  currency: string;
  minimum_purchase_quantity: number;
  maximum_purchase_quantity?: number | null;
  quantity_increment: number;
  stock?: number | null;
  payment_methods: string[];
  rate_tiers: GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyDefaultVariantValuePropertyRateTiersItemResponse[];
  [key: string]: unknown;
}
