// This file is auto-generated by oagen. Do not edit.

export const ReplaceCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyVariantInvariantState = {
  MissingDefaultVariant: 'missing_default_variant',
  MultipleDefaultVariants: 'multiple_default_variants',
} as const;

export type ReplaceCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyVariantInvariantState =
  | (typeof ReplaceCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyVariantInvariantState)[keyof typeof ReplaceCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyVariantInvariantState]
  | (string & Record<never, never>);
