// This file is auto-generated by oagen. Do not edit.

export type GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMeta = Record<string, unknown>;

export type GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMetaResponse = Record<string, unknown>;
