// This file is auto-generated by oagen. Do not edit.

export type ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMeta = Record<string, unknown>;

export type ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMetaResponse = Record<string, unknown>;
