// This file is auto-generated by oagen. Do not edit.

export const SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItemStatus = {
  Active: 'active',
  Inactive: 'inactive',
} as const;

export type SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItemStatus =
  | (typeof SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItemStatus)[keyof typeof SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItemStatus]
  | (string & Record<never, never>);
