// This file is auto-generated by oagen. Do not edit.

export const UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope = {
  Product: 'product',
  Variant: 'variant',
} as const;

export type UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope =
  | (typeof UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope)[keyof typeof UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope]
  | (string & Record<never, never>);
