// This file is auto-generated by oagen. Do not edit.

import type { CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice, CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertyFullPriceResponse } from '../interfaces/create-invoice-response-value-201-application-json-property-data-property-payment-property-full-price.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeCreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertyFullPricePropertyTotal } from './create-invoice-response-value-201-application-json-property-data-property-payment-property-full-price-property-total.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice","required":["base","currency","units","vat","total"],"properties":{"base":{"kind":"primitive","type":"string"},"currency":{"kind":"primitive","type":"string"},"units":{"kind":"primitive","type":"integer"},"vat":{"kind":"primitive","type":"integer"},"total":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice","required":["base","currency","units","vat","total"],"properties":{"base":{"kind":"primitive","type":"string"},"currency":{"kind":"primitive","type":"string"},"units":{"kind":"primitive","type":"integer"},"vat":{"kind":"primitive","type":"integer"},"total":{"kind":"any"}},"additionalProperties":true};

export const deserializeCreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice = (
  response: CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertyFullPriceResponse,
): CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["base","currency","units","vat","total"]),
    base: response.base,
    currency: response.currency,
    units: response.units,
    vat: response.vat,
    total: deserializeCreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertyFullPricePropertyTotal(response.total),
  };
};
