// This file is auto-generated by oagen. Do not edit.

import type { CreateInvoiceRefundResponseValue200ApplicationJsonPropertyData, CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataResponse } from '../interfaces/create-invoice-refund-response-value-200-application-json-property-data.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeCreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice } from './create-invoice-refund-response-value-200-application-json-property-data-property-invoice.serializer';
import { deserializeCreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyRefund } from './create-invoice-refund-response-value-200-application-json-property-data-property-refund.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"CreateInvoiceRefundResponseValue200ApplicationJsonPropertyData","required":["invoice","refund"],"properties":{"invoice":{"kind":"any"},"refund":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"CreateInvoiceRefundResponseValue200ApplicationJsonPropertyData","required":["invoice","refund"],"properties":{"invoice":{"kind":"any"},"refund":{"kind":"any"}},"additionalProperties":true};

export const deserializeCreateInvoiceRefundResponseValue200ApplicationJsonPropertyData = (
  response: CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataResponse,
): CreateInvoiceRefundResponseValue200ApplicationJsonPropertyData => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["invoice","refund"]),
    invoice: deserializeCreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice(response.invoice),
    refund: deserializeCreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyRefund(response.refund),
  };
};
