// This file is auto-generated by oagen. Do not edit.

import type { GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal, GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotalResponse } from '../interfaces/get-invoice-response-value-200-application-json-property-data-property-payment-property-subtotal.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeGetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotalPropertyTotal } from './get-invoice-response-value-200-application-json-property-data-property-payment-property-subtotal-property-total.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal","required":["base","currency","units","vat","total"],"properties":{"base":{"kind":"primitive","type":"string"},"currency":{"kind":"primitive","type":"string"},"units":{"kind":"primitive","type":"integer"},"vat":{"kind":"primitive","type":"integer"},"total":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal","required":["base","currency","units","vat","total"],"properties":{"base":{"kind":"primitive","type":"string"},"currency":{"kind":"primitive","type":"string"},"units":{"kind":"primitive","type":"integer"},"vat":{"kind":"primitive","type":"integer"},"total":{"kind":"any"}},"additionalProperties":true};

export const deserializeGetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal = (
  response: GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotalResponse,
): GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["base","currency","units","vat","total"]),
    base: response.base,
    currency: response.currency,
    units: response.units,
    vat: response.vat,
    total: deserializeGetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotalPropertyTotal(response.total),
  };
};
