// This file is auto-generated by oagen. Do not edit.

import type { IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyCustomerInformationPropertyDiscordData, IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyCustomerInformationPropertyDiscordDataResponse } from '../interfaces/issue-replacement-for-completed-invoice-response-value-200-application-json-property-customer-information-property-discord-data.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyCustomerInformationPropertyDiscordData","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyCustomerInformationPropertyDiscordData","required":[],"properties":{},"additionalProperties":true};

export const deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyCustomerInformationPropertyDiscordData = (
  _response: IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyCustomerInformationPropertyDiscordDataResponse,
): IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyCustomerInformationPropertyDiscordData => {
  assertValidModel(_response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_response, []),
  };
};
