// This file is auto-generated by oagen. Do not edit.

import type { IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGateway, IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayResponse } from '../interfaces/issue-replacement-for-completed-invoice-response-value-200-application-json-property-payment-property-gateway.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyData } from './issue-replacement-for-completed-invoice-response-value-200-application-json-property-payment-property-gateway-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGateway","required":["data","type"],"properties":{"data":{"kind":"any"},"type":{"kind":"primitive","type":"string"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGateway","required":["data","type"],"properties":{"data":{"kind":"any"},"type":{"kind":"primitive","type":"string"}},"additionalProperties":true};

export const deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGateway = (
  response: IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayResponse,
): IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGateway => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data","type"]),
    data: deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyData(response.data),
    type: response.type,
  };
};
