// This file is auto-generated by oagen. Do not edit.

import type { IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPayment, IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentResponse } from '../interfaces/issue-replacement-for-completed-invoice-response-value-200-application-json-property-payment.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyFee } from './issue-replacement-for-completed-invoice-response-value-200-application-json-property-payment-property-fee.serializer';
import { deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGateway } from './issue-replacement-for-completed-invoice-response-value-200-application-json-property-payment-property-gateway.serializer';
import { deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertySubtotal } from './issue-replacement-for-completed-invoice-response-value-200-application-json-property-payment-property-subtotal.serializer';
import { deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyFullPrice } from './issue-replacement-for-completed-invoice-response-value-200-application-json-property-payment-property-full-price.serializer';
import { deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyOriginalAmount } from './issue-replacement-for-completed-invoice-response-value-200-application-json-property-payment-property-original-amount.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPayment","required":["fee","gateway","subtotal","expiresAt","fullPrice","originalAmount"],"properties":{"fee":{"kind":"any"},"gateway":{"kind":"any"},"subtotal":{"kind":"any"},"expiresAt":{"kind":"primitive","type":"string","format":"date-time"},"fullPrice":{"kind":"any"},"originalAmount":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPayment","required":["fee","gateway","subtotal","expires_at","full_price","original_amount"],"properties":{"fee":{"kind":"any"},"gateway":{"kind":"any"},"subtotal":{"kind":"any"},"expires_at":{"kind":"primitive","type":"string","format":"date-time"},"full_price":{"kind":"any"},"original_amount":{"kind":"any"}},"additionalProperties":true};

export const deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPayment = (
  response: IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentResponse,
): IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPayment => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["fee","gateway","subtotal","expires_at","full_price","original_amount"]),
    fee: deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyFee(response.fee),
    gateway: deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGateway(response.gateway),
    subtotal: deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertySubtotal(response.subtotal),
    expiresAt: new Date(response.expires_at),
    fullPrice: deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyFullPrice(response.full_price),
    originalAmount: deserializeIssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyOriginalAmount(response.original_amount),
  };
};
