// This file is auto-generated by oagen. Do not edit.

import type { ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyBillingDetails, ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyBillingDetailsResponse } from '../interfaces/list-invoices-response-value-200-application-json-property-data-item-property-customer-information-property-billing-details.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyBillingDetails","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyBillingDetails","required":[],"properties":{},"additionalProperties":true};

export const deserializeListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyBillingDetails = (
  _response: ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyBillingDetailsResponse,
): ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyBillingDetails => {
  assertValidModel(_response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_response, []),
  };
};
