// This file is auto-generated by oagen. Do not edit.

export { deserializeListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyWebhooksItem as deserializeMarkPendingInvoiceCompletedResponseValue200ApplicationJsonPropertyWebhooksItem } from './list-invoices-response-value-200-application-json-property-data-item-property-webhooks-item.serializer';
