// This file is auto-generated by oagen. Do not edit.

export { serializeSdkMarkPendingInvoiceCompletedRequestApplicationJson as serializeSdkMarkPendingInvoiceVoidedRequestApplicationJson } from './sdk-mark-pending-invoice-completed-request-application-json.serializer';
