// This file is auto-generated by oagen. Do not edit.

import type { SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGateway, SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGatewayResponse } from '../interfaces/search-invoices-response-value-200-application-json-property-data-item-property-payment-property-gateway.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeSearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGatewayPropertyData } from './search-invoices-response-value-200-application-json-property-data-item-property-payment-property-gateway-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGateway","required":["data","type"],"properties":{"data":{"kind":"any"},"type":{"kind":"primitive","type":"string"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGateway","required":["data","type"],"properties":{"data":{"kind":"any"},"type":{"kind":"primitive","type":"string"}},"additionalProperties":true};

export const deserializeSearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGateway = (
  response: SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGatewayResponse,
): SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGateway => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data","type"]),
    data: deserializeSearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGatewayPropertyData(response.data),
    type: response.type,
  };
};
