// This file is auto-generated by oagen. Do not edit.

import type { SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotal, SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotalResponse } from '../interfaces/search-invoices-response-value-200-application-json-property-data-item-property-payment-property-subtotal.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeSearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotalPropertyTotal } from './search-invoices-response-value-200-application-json-property-data-item-property-payment-property-subtotal-property-total.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotal","required":["base","currency","units","vat","total"],"properties":{"base":{"kind":"primitive","type":"string"},"currency":{"kind":"primitive","type":"string"},"units":{"kind":"primitive","type":"integer"},"vat":{"kind":"primitive","type":"integer"},"total":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotal","required":["base","currency","units","vat","total"],"properties":{"base":{"kind":"primitive","type":"string"},"currency":{"kind":"primitive","type":"string"},"units":{"kind":"primitive","type":"integer"},"vat":{"kind":"primitive","type":"integer"},"total":{"kind":"any"}},"additionalProperties":true};

export const deserializeSearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotal = (
  response: SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotalResponse,
): SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotal => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["base","currency","units","vat","total"]),
    base: response.base,
    currency: response.currency,
    units: response.units,
    vat: response.vat,
    total: deserializeSearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotalPropertyTotal(response.total),
  };
};
