// This file is auto-generated by oagen. Do not edit.

import type { UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyData, UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyDataResponse } from '../interfaces/update-invoice-status-response-value-200-application-json-property-payment-property-gateway-property-data.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyData","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyData","required":[],"properties":{},"additionalProperties":true};

export const deserializeUpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyData = (
  _response: UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyDataResponse,
): UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyData => {
  assertValidModel(_response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_response, []),
  };
};
