// This file is auto-generated by oagen. Do not edit.

import type { GetOAuthInstallationResponseValue200ApplicationJsonPropertyData, GetOAuthInstallationResponseValue200ApplicationJsonPropertyDataResponse } from './get-oauth-installation-response-value-200-application-json-property-data.interface';

export interface SdkGetOAuthInstallationResponseValue200ApplicationJson {
  data: GetOAuthInstallationResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkGetOAuthInstallationResponseValue200ApplicationJsonResponse {
  data: GetOAuthInstallationResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
