// This file is auto-generated by oagen. Do not edit.

import type { SdkAppendVariantSerialInventoryResponseValue201ApplicationJson, SdkAppendVariantSerialInventoryResponseValue201ApplicationJsonResponse } from '../interfaces/sdk-append-variant-serial-inventory-response-value-201-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeAppendVariantSerialInventoryResponseValue201ApplicationJsonPropertyData } from './append-variant-serial-inventory-response-value-201-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkAppendVariantSerialInventoryResponseValue201ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkAppendVariantSerialInventoryResponseValue201ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkAppendVariantSerialInventoryResponseValue201ApplicationJson = (
  response: SdkAppendVariantSerialInventoryResponseValue201ApplicationJsonResponse,
): SdkAppendVariantSerialInventoryResponseValue201ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeAppendVariantSerialInventoryResponseValue201ApplicationJsonPropertyData(response.data),
  };
};
