// This file is auto-generated by oagen. Do not edit.

import type { GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet, GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWalletResponse } from '../interfaces/get-customer-response-value-200-application-json-property-data-property-wallet.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet","required":["status","balanceCents"],"properties":{"status":{"kind":"enum","values":["active","frozen"]},"balanceCents":{"kind":"primitive","type":"integer","constraints":{"minimum":0}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet","required":["status","balance_cents"],"properties":{"status":{"kind":"enum","values":["active","frozen"]},"balance_cents":{"kind":"primitive","type":"integer","constraints":{"minimum":0}}},"additionalProperties":true};

export const deserializeGetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet = (
  response: GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWalletResponse,
): GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["status","balance_cents"]),
    status: response.status,
    balanceCents: response.balance_cents,
  };
};
