// This file is auto-generated by oagen. Do not edit.

export { deserializeCreateCustomerResponseValue201ApplicationJsonPropertyDataPropertyInsights as deserializeUpdateCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights } from './create-customer-response-value-201-application-json-property-data-property-insights.serializer';
