// This file is auto-generated by oagen. Do not edit.

import type { UpsertCustomerRequestApplicationJsonPropertyMetadata, UpsertCustomerRequestApplicationJsonPropertyMetadataResponse } from '../interfaces/upsert-customer-request-application-json-property-metadata.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"UpsertCustomerRequestApplicationJsonPropertyMetadata","required":[],"properties":{},"additionalProperties":{"kind":"any"},"constraints":{"maxProperties":50}};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"UpsertCustomerRequestApplicationJsonPropertyMetadata","required":[],"properties":{},"additionalProperties":{"kind":"any"},"constraints":{"maxProperties":50}};

export const serializeUpsertCustomerRequestApplicationJsonPropertyMetadata = (
  _model: UpsertCustomerRequestApplicationJsonPropertyMetadata,
): UpsertCustomerRequestApplicationJsonPropertyMetadataResponse => {
  assertValidModel(_model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_model, []),
  };
};
