// This file is auto-generated by oagen. Do not edit.

import type { BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem, BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemResponse } from '../interfaces/batch-create-product-variants-request-application-json-property-resources-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { serializeBatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverable } from './batch-create-product-variants-request-application-json-property-resources-item-property-deliverable.serializer';
import { serializeBatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyPricing } from './batch-create-product-variants-request-application-json-property-resources-item-property-pricing.serializer';
import { serializeBatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyBulkDiscountItem } from './batch-create-product-variants-request-application-json-property-resources-item-property-bulk-discount-item.serializer';
import { serializeBatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyOtherSettings } from './batch-create-product-variants-request-application-json-property-resources-item-property-other-settings.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem","required":["title","description","deliverable","pricing","paymentMethods"],"properties":{"title":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"deliverable":{"kind":"any"},"pricing":{"kind":"any"},"minimumPurchaseQuantity":{"kind":"primitive","type":"integer"},"maximumPurchaseQuantity":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"bulkDiscount":{"kind":"array","items":{"kind":"any"}},"paymentMethods":{"kind":"array","items":{"kind":"enum","values":["AUTHNET","BTCPAY","CASHAPP","COINBASE","PADDLE","PAYDASH","PAYPAL","PAYSTACK","SQUARE","STRIPE","VENMO","NMI","MERCADO_PAGO","MOLLIE","RAZORPAY","CUSTOM_PAYMENT_METHOD","LIFI","BTC","LTC","ETH","XMR","SOL","ADA","BNB","TRX","MATIC","ETH_USDT","ETH_USDC","ETH_UNI","ETH_SHIB","ETH_DAI","BNB_USDT","BNB_USDC","TRX_USDT","TRX_USDC","SOL_USDT","SOL_USDC"]},"constraints":{"minItems":1}},"otherSettings":{"kind":"any"},"expectedUpdatedAt":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem","required":["title","description","deliverable","pricing","payment_methods"],"properties":{"title":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"deliverable":{"kind":"any"},"pricing":{"kind":"any"},"minimum_purchase_quantity":{"kind":"primitive","type":"integer"},"maximum_purchase_quantity":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"bulk_discount":{"kind":"array","items":{"kind":"any"}},"payment_methods":{"kind":"array","items":{"kind":"enum","values":["AUTHNET","BTCPAY","CASHAPP","COINBASE","PADDLE","PAYDASH","PAYPAL","PAYSTACK","SQUARE","STRIPE","VENMO","NMI","MERCADO_PAGO","MOLLIE","RAZORPAY","CUSTOM_PAYMENT_METHOD","LIFI","BTC","LTC","ETH","XMR","SOL","ADA","BNB","TRX","MATIC","ETH_USDT","ETH_USDC","ETH_UNI","ETH_SHIB","ETH_DAI","BNB_USDT","BNB_USDC","TRX_USDT","TRX_USDC","SOL_USDT","SOL_USDC"]},"constraints":{"minItems":1}},"other_settings":{"kind":"any"},"expected_updated_at":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};

export const serializeBatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem = (
  model: BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem,
): BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["title","description","deliverable","pricing","minimumPurchaseQuantity","maximumPurchaseQuantity","bulkDiscount","paymentMethods","otherSettings","expectedUpdatedAt"]),
    title: model.title,
    description: model.description,
    deliverable: serializeBatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverable(model.deliverable),
    pricing: serializeBatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyPricing(model.pricing),
    minimum_purchase_quantity: model.minimumPurchaseQuantity,
    maximum_purchase_quantity: model.maximumPurchaseQuantity,
    bulk_discount: model.bulkDiscount != null ? model.bulkDiscount.map(serializeBatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyBulkDiscountItem) : undefined,
    payment_methods: model.paymentMethods,
    other_settings: model.otherSettings != null ? serializeBatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyOtherSettings(model.otherSettings) : undefined,
    expected_updated_at: model.expectedUpdatedAt != null ? model.expectedUpdatedAt.toISOString() : undefined,
  };
};
