// This file is auto-generated by oagen. Do not edit.

export { deserializeListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemPropertyDefaultPrice as deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingPropertyPrice } from '../../groups/serializers/list-products-within-group-response-value-200-application-json-property-data-item-property-default-price.serializer';
