// This file is auto-generated by oagen. Do not edit.

import type { ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem, ListProductVariantsResponseValue200ApplicationJsonPropertyDataItemResponse } from '../interfaces/list-product-variants-response-value-200-application-json-property-data-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable } from './list-product-variants-response-value-200-application-json-property-data-item-property-deliverable.serializer';
import { deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricing } from './list-product-variants-response-value-200-application-json-property-data-item-property-pricing.serializer';
import { deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyBulkDiscountItem } from './list-product-variants-response-value-200-application-json-property-data-item-property-bulk-discount-item.serializer';
import { deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings } from './list-product-variants-response-value-200-application-json-property-data-item-property-other-settings.serializer';
import { deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct } from './list-product-variants-response-value-200-application-json-property-data-item-property-product.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem","required":["id","productId","title","description","deliverable","pricing","minimumPurchaseQuantity","maximumPurchaseQuantity","bulkDiscount","paymentMethods","otherSettings","order","createdAt","updatedAt","deletedAt","product"],"properties":{"id":{"kind":"primitive","type":"integer"},"productId":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"deliverable":{"kind":"any"},"pricing":{"kind":"any"},"minimumPurchaseQuantity":{"kind":"primitive","type":"integer"},"maximumPurchaseQuantity":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"bulkDiscount":{"kind":"nullable","inner":{"kind":"array","items":{"kind":"any"}}},"paymentMethods":{"kind":"array","items":{"kind":"primitive","type":"string"}},"otherSettings":{"kind":"any"},"order":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"createdAt":{"kind":"primitive","type":"string","format":"date-time"},"updatedAt":{"kind":"primitive","type":"string","format":"date-time"},"deletedAt":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"product":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem","required":["id","product_id","title","description","deliverable","pricing","minimum_purchase_quantity","maximum_purchase_quantity","bulk_discount","payment_methods","other_settings","order","created_at","updated_at","deleted_at","product"],"properties":{"id":{"kind":"primitive","type":"integer"},"product_id":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"deliverable":{"kind":"any"},"pricing":{"kind":"any"},"minimum_purchase_quantity":{"kind":"primitive","type":"integer"},"maximum_purchase_quantity":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"bulk_discount":{"kind":"nullable","inner":{"kind":"array","items":{"kind":"any"}}},"payment_methods":{"kind":"array","items":{"kind":"primitive","type":"string"}},"other_settings":{"kind":"any"},"order":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"created_at":{"kind":"primitive","type":"string","format":"date-time"},"updated_at":{"kind":"primitive","type":"string","format":"date-time"},"deleted_at":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"product":{"kind":"any"}},"additionalProperties":true};

export const deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItem = (
  response: ListProductVariantsResponseValue200ApplicationJsonPropertyDataItemResponse,
): ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["id","product_id","title","description","deliverable","pricing","minimum_purchase_quantity","maximum_purchase_quantity","bulk_discount","payment_methods","other_settings","order","created_at","updated_at","deleted_at","product"]),
    id: response.id,
    productId: response.product_id,
    title: response.title,
    description: response.description,
    deliverable: deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable(response.deliverable),
    pricing: deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricing(response.pricing),
    minimumPurchaseQuantity: response.minimum_purchase_quantity,
    maximumPurchaseQuantity: response.maximum_purchase_quantity ?? null,
    bulkDiscount: response.bulk_discount != null ? response.bulk_discount.map(deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyBulkDiscountItem) : null,
    paymentMethods: response.payment_methods,
    otherSettings: deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings(response.other_settings),
    order: response.order ?? null,
    createdAt: new Date(response.created_at),
    updatedAt: new Date(response.updated_at),
    deletedAt: response.deleted_at != null ? new Date(response.deleted_at) : null,
    product: deserializeListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct(response.product),
  };
};
