// This file is auto-generated by oagen. Do not edit.

import type { ReplaceProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct, ReplaceProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProductResponse } from '../interfaces/replace-product-variant-pricing-response-value-200-application-json-property-data-property-product.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeReplaceProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProductPropertyAdditionalInformationItem } from './replace-product-variant-pricing-response-value-200-application-json-property-data-property-product-property-additional-information-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ReplaceProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct","required":["additionalInformation"],"properties":{"additionalInformation":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ReplaceProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct","required":["additional_information"],"properties":{"additional_information":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const deserializeReplaceProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct = (
  response: ReplaceProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProductResponse,
): ReplaceProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["additional_information"]),
    additionalInformation: response.additional_information.map(deserializeReplaceProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProductPropertyAdditionalInformationItem),
  };
};
