// This file is auto-generated by oagen. Do not edit.

import type { ReplaceProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem, ReplaceProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItemResponse } from '../interfaces/replace-product-variant-pricing-request-application-json-property-bulk-discount-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ReplaceProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem","required":["minimumPurchaseAmount","discountPercentage"],"properties":{"minimumPurchaseAmount":{"kind":"primitive","type":"integer","constraints":{"minimum":1}},"discountPercentage":{"kind":"primitive","type":"integer","constraints":{"minimum":1,"maximum":100}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ReplaceProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem","required":["minimum_purchase_amount","discount_percentage"],"properties":{"minimum_purchase_amount":{"kind":"primitive","type":"integer","constraints":{"minimum":1}},"discount_percentage":{"kind":"primitive","type":"integer","constraints":{"minimum":1,"maximum":100}}},"additionalProperties":true};

export const serializeReplaceProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem = (
  model: ReplaceProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem,
): ReplaceProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItemResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["minimumPurchaseAmount","discountPercentage"]),
    minimum_purchase_amount: model.minimumPurchaseAmount,
    discount_percentage: model.discountPercentage,
  };
};
