// This file is auto-generated by oagen. Do not edit.

import type { ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequency, ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyResponse } from '../interfaces/replace-product-variant-pricing-request-application-json-property-pricing-property-frequency.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequency","required":["value","interval"],"properties":{"value":{"kind":"primitive","type":"integer","constraints":{"minimum":1}},"interval":{"kind":"enum","values":["DAY","WEEK","MONTH","YEAR"]}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequency","required":["value","interval"],"properties":{"value":{"kind":"primitive","type":"integer","constraints":{"minimum":1}},"interval":{"kind":"enum","values":["DAY","WEEK","MONTH","YEAR"]}},"additionalProperties":true};

export const serializeReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequency = (
  model: ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequency,
): ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["value","interval"]),
    value: model.value,
    interval: model.interval,
  };
};
