// This file is auto-generated by oagen. Do not edit.

import type { ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice, ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceResponse } from '../interfaces/replace-product-variant-pricing-request-application-json-property-pricing-property-price.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice","required":["price","currency"],"properties":{"price":{"kind":"primitive","type":"integer","constraints":{"minimum":0}},"currency":{"kind":"enum","values":["AUD","BRL","CAD","CNY","CZK","DKK","EUR","GHS","HKD","HUF","ILS","INR","JPY","MYR","MXN","NGN","TWD","NZD","NOK","PHP","PLN","GBP","RUB","SGD","SEK","CHF","THB","USD","ZAR"]}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice","required":["price","currency"],"properties":{"price":{"kind":"primitive","type":"integer","constraints":{"minimum":0}},"currency":{"kind":"enum","values":["AUD","BRL","CAD","CNY","CZK","DKK","EUR","GHS","HKD","HUF","ILS","INR","JPY","MYR","MXN","NGN","TWD","NZD","NOK","PHP","PLN","GBP","RUB","SGD","SEK","CHF","THB","USD","ZAR"]}},"additionalProperties":true};

export const serializeReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice = (
  model: ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice,
): ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["price","currency"]),
    price: model.price,
    currency: model.currency,
  };
};
