// This file is auto-generated by oagen. Do not edit.

import type { SdkGetProductVariantResponseValue200ApplicationJson, SdkGetProductVariantResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-get-product-variant-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeGetProductVariantResponseValue200ApplicationJsonPropertyData } from './get-product-variant-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkGetProductVariantResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkGetProductVariantResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkGetProductVariantResponseValue200ApplicationJson = (
  response: SdkGetProductVariantResponseValue200ApplicationJsonResponse,
): SdkGetProductVariantResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeGetProductVariantResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
