// This file is auto-generated by oagen. Do not edit.

import type { SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct, SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProductResponse } from '../interfaces/search-product-variants-response-value-200-application-json-property-data-item-property-product.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeSearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProductPropertyAdditionalInformationItem } from './search-product-variants-response-value-200-application-json-property-data-item-property-product-property-additional-information-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct","required":["additionalInformation"],"properties":{"additionalInformation":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct","required":["additional_information"],"properties":{"additional_information":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const deserializeSearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct = (
  response: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProductResponse,
): SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["additional_information"]),
    additionalInformation: response.additional_information.map(deserializeSearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyProductPropertyAdditionalInformationItem),
  };
};
