// This file is auto-generated by oagen. Do not edit.

import type { UpdateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataPropertyBookingPropertyMeta, UpdateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataPropertyBookingPropertyMetaResponse } from '../interfaces/update-product-variant-request-application-json-property-deliverable-property-data-property-booking-property-meta.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"UpdateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataPropertyBookingPropertyMeta","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"UpdateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataPropertyBookingPropertyMeta","required":[],"properties":{},"additionalProperties":true};

export const serializeUpdateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataPropertyBookingPropertyMeta = (
  _model: UpdateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataPropertyBookingPropertyMeta,
): UpdateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataPropertyBookingPropertyMetaResponse => {
  assertValidModel(_model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_model, []),
  };
};
