// This file is auto-generated by oagen. Do not edit.

import type { UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct, UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProductResponse } from '../interfaces/update-product-variant-pricing-response-value-200-application-json-property-data-property-product.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeUpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProductPropertyAdditionalInformationItem } from './update-product-variant-pricing-response-value-200-application-json-property-data-property-product-property-additional-information-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct","required":["additionalInformation"],"properties":{"additionalInformation":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct","required":["additional_information"],"properties":{"additional_information":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const deserializeUpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct = (
  response: UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProductResponse,
): UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProduct => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["additional_information"]),
    additionalInformation: response.additional_information.map(deserializeUpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProductPropertyAdditionalInformationItem),
  };
};
