// This file is auto-generated by oagen. Do not edit.

export { serializeReplaceProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem as serializeUpdateProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem } from './replace-product-variant-pricing-request-application-json-property-bulk-discount-item.serializer';
