// This file is auto-generated by oagen. Do not edit.

export { deserializeListProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem as deserializeUpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyProductPropertyAdditionalInformationItem } from '../../products/serializers/list-products-response-value-200-application-json-property-data-item-property-additional-information-item.serializer';
