// This file is auto-generated by oagen. Do not edit.

import type { CancelSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyData, CancelSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyDataResponse } from '../interfaces/cancel-subscription-immediately-response-value-200-application-json-property-data.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"CancelSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyData","required":[],"properties":{"id":{"kind":"primitive","type":"integer"},"productSubscriptionId":{"kind":"primitive","type":"integer"},"subscriptionId":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"action":{"kind":"enum","values":["pause","resume","cancel_at_period_end","cancel_immediately","update_payment_method","change_plan","shift_billing_date"]},"status":{"kind":"enum","values":["pending","confirmed","failed","expired","dismissed","force_resolved"]},"provider":{"kind":"primitive","type":"string"},"customerMessage":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"confirmedAt":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"failedAt":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"createdAt":{"kind":"primitive","type":"string","format":"date-time"},"updatedAt":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"CancelSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyData","required":[],"properties":{"id":{"kind":"primitive","type":"integer"},"product_subscription_id":{"kind":"primitive","type":"integer"},"subscription_id":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"action":{"kind":"enum","values":["pause","resume","cancel_at_period_end","cancel_immediately","update_payment_method","change_plan","shift_billing_date"]},"status":{"kind":"enum","values":["pending","confirmed","failed","expired","dismissed","force_resolved"]},"provider":{"kind":"primitive","type":"string"},"customer_message":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"confirmed_at":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"failed_at":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"created_at":{"kind":"primitive","type":"string","format":"date-time"},"updated_at":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};

export const deserializeCancelSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyData = (
  response: CancelSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyDataResponse,
): CancelSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyData => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["id","product_subscription_id","subscription_id","action","status","provider","customer_message","confirmed_at","failed_at","created_at","updated_at"]),
    id: response.id,
    productSubscriptionId: response.product_subscription_id,
    subscriptionId: response.subscription_id ?? null,
    action: response.action,
    status: response.status,
    provider: response.provider,
    customerMessage: response.customer_message ?? null,
    confirmedAt: response.confirmed_at != null ? new Date(response.confirmed_at) : null,
    failedAt: response.failed_at != null ? new Date(response.failed_at) : null,
    createdAt: response.created_at != null ? new Date(response.created_at) : undefined,
    updatedAt: response.updated_at != null ? new Date(response.updated_at) : undefined,
  };
};
