// This file is auto-generated by oagen. Do not edit.

import type { SdkPauseSubscriptionRequestApplicationJson, SdkPauseSubscriptionRequestApplicationJsonResponse } from '../interfaces/sdk-pause-subscription-request-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkPauseSubscriptionRequestApplicationJson","required":[],"properties":{"idempotencyKey":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":128}}},"resumeAt":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"reason":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":500}}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkPauseSubscriptionRequestApplicationJson","required":[],"properties":{"idempotency_key":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":128}}},"resume_at":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"reason":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":500}}}},"additionalProperties":true};

export const serializeSdkPauseSubscriptionRequestApplicationJson = (
  model: SdkPauseSubscriptionRequestApplicationJson,
): SdkPauseSubscriptionRequestApplicationJsonResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["idempotencyKey","resumeAt","reason"]),
    idempotency_key: model.idempotencyKey,
    resume_at: model.resumeAt != null ? model.resumeAt.toISOString() : null,
    reason: model.reason,
  };
};
