// This file is auto-generated by oagen. Do not edit.

import type { CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyServerPropertyRolesItem, CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyServerPropertyRolesItemResponse } from './complete-community-connection-response-value-200-application-json-property-data-property-server-property-roles-item.interface';

export interface CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyServer {
  id: string;
  name: string;
  type: string | null;
  /** @readonly */
  readonly healthStatus: string | null;
  /** @readonly */
  readonly healthCheckedAt: Date | null;
  /** @readonly */
  readonly roles: CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyServerPropertyRolesItem[];
  [key: string]: unknown;
}

export interface CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyServerResponse {
  id: string;
  name: string;
  type: string | null;
  health_status: string | null;
  health_checked_at: string | null;
  roles: CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyServerPropertyRolesItemResponse[];
  [key: string]: unknown;
}
