// This file is auto-generated by oagen. Do not edit.

export interface PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyAvailableServersItem {
  id: string;
  name: string;
  type: 'group';
  [key: string]: unknown;
}

export interface PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyAvailableServersItemResponse {
  id: string;
  name: string;
  type: 'group';
  [key: string]: unknown;
}
