// This file is auto-generated by oagen. Do not edit.

export const PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataStatus = {
  Pending: 'pending',
  Used: 'used',
  Linked: 'linked',
  Expired: 'expired',
  Authenticated: 'authenticated',
  Error: 'error',
  Unknown: 'unknown',
} as const;

export type PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataStatus =
  | (typeof PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataStatus)[keyof typeof PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataStatus]
  | (string & Record<never, never>);
