// This file is auto-generated by oagen. Do not edit.

import type { CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyData, CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyDataResponse } from './complete-community-connection-response-value-200-application-json-property-data.interface';

export interface SdkCompleteCommunityConnectionResponseValue200ApplicationJson {
  data: CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkCompleteCommunityConnectionResponseValue200ApplicationJsonResponse {
  data: CompleteCommunityConnectionResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
