// This file is auto-generated by oagen. Do not edit.

import type { ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral, ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferralResponse } from '../interfaces/list-order-line-items-response-value-200-application-json-property-data-item-property-referral.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral","required":["id","status","amountUsdCents"],"properties":{"id":{"kind":"primitive","type":"integer"},"status":{"kind":"primitive","type":"string"},"amountUsdCents":{"kind":"primitive","type":"integer"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral","required":["id","status","amount_usd_cents"],"properties":{"id":{"kind":"primitive","type":"integer"},"status":{"kind":"primitive","type":"string"},"amount_usd_cents":{"kind":"primitive","type":"integer"}},"additionalProperties":true};

export const deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral = (
  response: ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferralResponse,
): ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["id","status","amount_usd_cents"]),
    id: response.id,
    status: response.status,
    amountUsdCents: response.amount_usd_cents,
  };
};
