// This file is auto-generated by oagen. Do not edit.

import type { ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem, ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemResponse } from '../interfaces/list-order-line-items-response-value-200-application-json-property-data-item-property-discounts-property-modifiers-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemPropertyAttributes } from './list-order-line-items-response-value-200-application-json-property-data-item-property-discounts-property-modifiers-item-property-attributes.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem","required":["type"],"properties":{"type":{"kind":"primitive","type":"string"},"key":{"kind":"primitive","type":"string"},"amountCents":{"kind":"primitive","type":"integer"},"attributes":{"kind":"any"}},"additionalProperties":false};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem","required":["type"],"properties":{"type":{"kind":"primitive","type":"string"},"key":{"kind":"primitive","type":"string"},"amount_cents":{"kind":"primitive","type":"integer"},"attributes":{"kind":"any"}},"additionalProperties":false};

export const deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem = (
  response: ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemResponse,
): ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["type","key","amount_cents","attributes"]),
    type: response.type,
    key: response.key,
    amountCents: response.amount_cents,
    attributes: response.attributes != null ? deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItemPropertyAttributes(response.attributes) : undefined,
  };
};
