// This file is auto-generated by oagen. Do not edit.

import type { ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts, ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsResponse } from '../interfaces/list-order-s-line-items-response-value-200-application-json-property-data-item-property-discounts.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyCoupon } from './list-order-s-line-items-response-value-200-application-json-property-data-item-property-discounts-property-coupon.serializer';
import { deserializeListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem } from './list-order-s-line-items-response-value-200-application-json-property-data-item-property-discounts-property-modifiers-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts","required":["coupon","modifiers"],"properties":{"coupon":{"kind":"nullable","inner":{"kind":"any"}},"modifiers":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts","required":["coupon","modifiers"],"properties":{"coupon":{"kind":"nullable","inner":{"kind":"any"}},"modifiers":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const deserializeListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts = (
  response: ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsResponse,
): ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["coupon","modifiers"]),
    coupon: response.coupon != null ? deserializeListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyCoupon(response.coupon) : null,
    modifiers: response.modifiers.map(deserializeListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem),
  };
};
