// This file is auto-generated by oagen. Do not edit.

import type { ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscription, ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscriptionResponse } from '../interfaces/list-order-line-items-response-value-200-application-json-property-data-item-property-subscription.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscription","required":["id","provider","status","cancelAtPeriodEnd"],"properties":{"id":{"kind":"primitive","type":"integer"},"provider":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"status":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"currentPeriodStart":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"currentPeriodEnd":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"cancelAtPeriodEnd":{"kind":"primitive","type":"boolean"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscription","required":["id","provider","status","cancel_at_period_end"],"properties":{"id":{"kind":"primitive","type":"integer"},"provider":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"status":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"current_period_start":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"current_period_end":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"cancel_at_period_end":{"kind":"primitive","type":"boolean"}},"additionalProperties":true};

export const deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscription = (
  response: ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscriptionResponse,
): ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscription => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["id","provider","status","current_period_start","current_period_end","cancel_at_period_end"]),
    id: response.id,
    provider: response.provider ?? null,
    status: response.status ?? null,
    currentPeriodStart: response.current_period_start != null ? new Date(response.current_period_start) : null,
    currentPeriodEnd: response.current_period_end != null ? new Date(response.current_period_end) : null,
    cancelAtPeriodEnd: response.cancel_at_period_end,
  };
};
