// This file is auto-generated by oagen. Do not edit.

import type { ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts, ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsResponse } from '../interfaces/list-order-line-items-response-value-200-application-json-property-data-item-property-discounts.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyCoupon } from './list-order-line-items-response-value-200-application-json-property-data-item-property-discounts-property-coupon.serializer';
import { deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem } from './list-order-line-items-response-value-200-application-json-property-data-item-property-discounts-property-modifiers-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts","required":["coupon","modifiers"],"properties":{"coupon":{"kind":"nullable","inner":{"kind":"any"}},"modifiers":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts","required":["coupon","modifiers"],"properties":{"coupon":{"kind":"nullable","inner":{"kind":"any"}},"modifiers":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts = (
  response: ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsResponse,
): ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["coupon","modifiers"]),
    coupon: response.coupon != null ? deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyCoupon(response.coupon) : null,
    modifiers: response.modifiers.map(deserializeListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem),
  };
};
