// This file is auto-generated by oagen. Do not edit.

import type { SellApp } from '../sellapp';
import type { GetOptions as RequestOptions } from '../common/interfaces/get-options.interface';
import { AutoPaginatable } from '../common/utils/pagination';
import { fetchAndDeserialize } from '../common/utils/fetch-and-deserialize';
import type { ListRefundsOptions } from './interfaces/list-refunds-options.interface';
import type { GetRefundOptions } from './interfaces/get-refund-options.interface';
import type { ListRefundsResponseValue200ApplicationJsonPropertyDataItem, ListRefundsResponseValue200ApplicationJsonPropertyDataItemResponse } from './interfaces/list-refunds-response-value-200-application-json-property-data-item.interface';
import type { SdkGetRefundResponseValue200ApplicationJson, SdkGetRefundResponseValue200ApplicationJsonResponse } from './interfaces/sdk-get-refund-response-value-200-application-json.interface';
import { deserializeListRefundsResponseValue200ApplicationJsonPropertyDataItem } from './serializers/list-refunds-response-value-200-application-json-property-data-item.serializer';
import { deserializeSdkGetRefundResponseValue200ApplicationJson } from './serializers/sdk-get-refund-response-value-200-application-json.serializer';

interface SellAppResponseEnvelope<T> { data: T; status: number; headers: Headers; requestId?: string }
type SellAppWithResponse<T extends object> = {
  [K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never]:
    T[K] extends (...args: infer A) => Promise<infer R> ? (...args: A) => Promise<SellAppResponseEnvelope<R>> : never;
};
function createResourceWithResponse<T extends object>(resource: T, client: SellApp): SellAppWithResponse<T> {
  return new Proxy({} as SellAppWithResponse<T>, {
    get: (_target, property) => (...args: unknown[]) => client.captureResponse(
      () => (resource[property as keyof T] as (...values: unknown[]) => Promise<unknown>).apply(resource, args),
    ),
  }) as SellAppWithResponse<T>;
}

export class Refunds {
  constructor(private readonly sellApp: SellApp) {}
  get withResponse(): SellAppWithResponse<this> { return createResourceWithResponse(this, this.sellApp); }

  /**
   * List refunds
   *
   * List refunds for orders and standalone charges in the selected store, one page at a time. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<ListRefundsResponseValue200ApplicationJsonPropertyDataItem>>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async listRefunds(options?: ListRefundsOptions): Promise<AutoPaginatable<ListRefundsResponseValue200ApplicationJsonPropertyDataItem, ListRefundsOptions>> {
    const paginationOptions = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<ListRefundsResponseValue200ApplicationJsonPropertyDataItemResponse, ListRefundsResponseValue200ApplicationJsonPropertyDataItem>(
        this.sellApp,
        '/v2/refunds',
        deserializeListRefundsResponseValue200ApplicationJsonPropertyDataItem,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<ListRefundsResponseValue200ApplicationJsonPropertyDataItemResponse, ListRefundsResponseValue200ApplicationJsonPropertyDataItem>(
          this.sellApp,
          '/v2/refunds',
          deserializeListRefundsResponseValue200ApplicationJsonPropertyDataItem,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * Retrieve a refund
   *
   * Retrieve one store-scoped refund. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.refund - The refund identifier.
   * @example 781
   * @returns {Promise<SdkGetRefundResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async getRefund(options: GetRefundOptions): Promise<SdkGetRefundResponseValue200ApplicationJson> {
    const { refund } = options;
    const { data } = await this.sellApp.get<SdkGetRefundResponseValue200ApplicationJsonResponse>(`/v2/refunds/${encodeURIComponent(refund)}`, { ...options.requestOptions, operationId: 'getRefund' });
    return deserializeSdkGetRefundResponseValue200ApplicationJson(data);
  }
}
