// This file is auto-generated by oagen. Do not edit.

import type { SellApp } from '../sellapp';
import type { GetOptions as RequestOptions } from '../common/interfaces/get-options.interface';
import type { ListAvailabilityOptions } from './interfaces/list-availability-options.interface';
import type { CreateHoldOptions } from './interfaces/create-hold-options.interface';
import type { ReleaseHoldOptions } from './interfaces/release-hold-options.interface';
import type { GetOptions } from './interfaces/get-options.interface';
import type { ReplaceOptions } from './interfaces/replace-options.interface';
import type { UpdateOptions } from './interfaces/update-options.interface';
import type { SdkListBookingAvailabilityResponseValue200ApplicationJson, SdkListBookingAvailabilityResponseValue200ApplicationJsonResponse } from '../product-variants/interfaces/sdk-list-booking-availability-response-value-200-application-json.interface';
import type { SdkCreateBookingHoldResponseValue201ApplicationJson, SdkCreateBookingHoldResponseValue201ApplicationJsonResponse } from '../product-variants/interfaces/sdk-create-booking-hold-response-value-201-application-json.interface';
import type { SdkGetBookingConfigurationResponseValue200ApplicationJson, SdkGetBookingConfigurationResponseValue200ApplicationJsonResponse } from '../bookings/interfaces/sdk-get-booking-configuration-response-value-200-application-json.interface';
import type { SdkReplaceBookingConfigurationResponseValue200ApplicationJson, SdkReplaceBookingConfigurationResponseValue200ApplicationJsonResponse } from '../bookings/interfaces/sdk-replace-booking-configuration-response-value-200-application-json.interface';
import type { SdkUpdateBookingConfigurationResponseValue200ApplicationJson, SdkUpdateBookingConfigurationResponseValue200ApplicationJsonResponse } from '../bookings/interfaces/sdk-update-booking-configuration-response-value-200-application-json.interface';
import type { SdkCreateBookingHoldRequestApplicationJsonResponse } from '../product-variants/interfaces/sdk-create-booking-hold-request-application-json.interface';
import type { SdkReleaseBookingHoldRequestApplicationJsonResponse } from '../product-variants/interfaces/sdk-release-booking-hold-request-application-json.interface';
import type { SdkReplaceBookingConfigurationRequestApplicationJsonResponse } from '../bookings/interfaces/sdk-replace-booking-configuration-request-application-json.interface';
import type { SdkUpdateBookingConfigurationRequestApplicationJsonResponse } from '../bookings/interfaces/sdk-update-booking-configuration-request-application-json.interface';
import { deserializeSdkListBookingAvailabilityResponseValue200ApplicationJson } from '../product-variants/serializers/sdk-list-booking-availability-response-value-200-application-json.serializer';
import { deserializeSdkCreateBookingHoldResponseValue201ApplicationJson } from '../product-variants/serializers/sdk-create-booking-hold-response-value-201-application-json.serializer';
import { deserializeSdkGetBookingConfigurationResponseValue200ApplicationJson } from '../bookings/serializers/sdk-get-booking-configuration-response-value-200-application-json.serializer';
import { deserializeSdkReplaceBookingConfigurationResponseValue200ApplicationJson } from '../bookings/serializers/sdk-replace-booking-configuration-response-value-200-application-json.serializer';
import { deserializeSdkUpdateBookingConfigurationResponseValue200ApplicationJson } from '../bookings/serializers/sdk-update-booking-configuration-response-value-200-application-json.serializer';
import { serializeSdkCreateBookingHoldRequestApplicationJson } from '../product-variants/serializers/sdk-create-booking-hold-request-application-json.serializer';
import { serializeSdkReleaseBookingHoldRequestApplicationJson } from '../product-variants/serializers/sdk-release-booking-hold-request-application-json.serializer';
import { serializeSdkReplaceBookingConfigurationRequestApplicationJson } from '../bookings/serializers/sdk-replace-booking-configuration-request-application-json.serializer';
import { serializeSdkUpdateBookingConfigurationRequestApplicationJson } from '../bookings/serializers/sdk-update-booking-configuration-request-application-json.serializer';

interface SellAppResponseEnvelope<T> { data: T; status: number; headers: Headers; requestId?: string }
type SellAppWithResponse<T extends object> = {
  [K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never]:
    T[K] extends (...args: infer A) => Promise<infer R> ? (...args: A) => Promise<SellAppResponseEnvelope<R>> : never;
};
function createResourceWithResponse<T extends object>(resource: T, client: SellApp): SellAppWithResponse<T> {
  return new Proxy({} as SellAppWithResponse<T>, {
    get: (_target, property) => (...args: unknown[]) => client.captureResponse(
      () => (resource[property as keyof T] as (...values: unknown[]) => Promise<unknown>).apply(resource, args),
    ),
  }) as SellAppWithResponse<T>;
}

export class ProductVariantsBooking {
  constructor(private readonly sellApp: SellApp) {}
  get withResponse(): SellAppWithResponse<this> { return createResourceWithResponse(this, this.sellApp); }

  /**
   * List booking availability
   *
   * Retrieve available appointment slots for a booking product variant. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Additional query options.
   * @param options.product - The product path parameter.
   * @param options.variant - The variant path parameter.
   * @param options.from - Start date for the availability window.
   * @param options.to - End date for the availability window.
   * @param options.quantity - Number of seats to reserve for each returned slot.
   * @returns {Promise<SdkListBookingAvailabilityResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async listAvailability(options: ListAvailabilityOptions): Promise<SdkListBookingAvailabilityResponseValue200ApplicationJson> {
    const { product, variant } = options;
    const { data } = await this.sellApp.get<SdkListBookingAvailabilityResponseValue200ApplicationJsonResponse>(`/v2/products/${encodeURIComponent(product)}/variants/${encodeURIComponent(variant)}/booking/availability`, { ...options.requestOptions, operationId: 'listBookingAvailability', query: { ...(options.from !== undefined && { from: options.from }), ...(options.to !== undefined && { to: options.to }), ...(options.quantity !== undefined && { quantity: options.quantity }) } });
    return deserializeSdkListBookingAvailabilityResponseValue200ApplicationJson(data);
  }

  /**
   * Create a booking hold
   *
   * Temporarily reserve a booking slot before checkout. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.product - The product path parameter.
   * @param options.variant - The variant path parameter.
   * @returns {Promise<SdkCreateBookingHoldResponseValue201ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async createHold(options: CreateHoldOptions): Promise<SdkCreateBookingHoldResponseValue201ApplicationJson> {
    const { product, variant, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.post<SdkCreateBookingHoldResponseValue201ApplicationJsonResponse, SdkCreateBookingHoldRequestApplicationJsonResponse>(
      `/v2/products/${encodeURIComponent(product)}/variants/${encodeURIComponent(variant)}/booking/holds`,
      serializeSdkCreateBookingHoldRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'createBookingHold' },
    );
    return deserializeSdkCreateBookingHoldResponseValue201ApplicationJson(data);
  }

  /**
   * Release a booking hold
   *
   * Release a previously created booking hold. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.product - The product path parameter.
   * @param options.hold - The hold path parameter.
   * @returns {Promise<void>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async releaseHold(options: ReleaseHoldOptions): Promise<void> {
    const { product, hold, requestOptions, ...payload } = options;
    await this.sellApp.deleteWithBody<SdkReleaseBookingHoldRequestApplicationJsonResponse>(`/v2/products/${encodeURIComponent(product)}/variants/booking/holds/${encodeURIComponent(hold)}`, serializeSdkReleaseBookingHoldRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'releaseBookingHold' });
  }

  /**
   * Retrieve booking configuration
   *
   * Retrieve creator-facing availability, capacity, calendar, meeting, and reminder configuration for a booking variant. Requires the `listing` Sanctum ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.product - The booking product ID or slug.
   * @example "41"
   * @param options.variant - The variant path parameter.
   * @example 73
   * @returns {Promise<SdkGetBookingConfigurationResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async get(options: GetOptions): Promise<SdkGetBookingConfigurationResponseValue200ApplicationJson> {
    const { product, variant } = options;
    const { data } = await this.sellApp.get<SdkGetBookingConfigurationResponseValue200ApplicationJsonResponse>(`/v2/products/${encodeURIComponent(product)}/variants/${encodeURIComponent(variant)}/booking`, { ...options.requestOptions, operationId: 'getBookingConfiguration' });
    return deserializeSdkGetBookingConfigurationResponseValue200ApplicationJson(data);
  }

  /**
   * Update booking configuration
   *
   * Partially update a booking variant's configuration. Provider connection IDs must belong to the selected store; secret credentials are never accepted or returned here. Requires the `listing` Sanctum ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.product - The booking product ID or slug.
   * @example "41"
   * @param options.variant - The variant path parameter.
   * @example 73
   * @returns {Promise<SdkReplaceBookingConfigurationResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async replace(options: ReplaceOptions): Promise<SdkReplaceBookingConfigurationResponseValue200ApplicationJson> {
    const { product, variant, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.put<SdkReplaceBookingConfigurationResponseValue200ApplicationJsonResponse, SdkReplaceBookingConfigurationRequestApplicationJsonResponse>(
      `/v2/products/${encodeURIComponent(product)}/variants/${encodeURIComponent(variant)}/booking`,
      serializeSdkReplaceBookingConfigurationRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'replaceBookingConfiguration' },
    );
    return deserializeSdkReplaceBookingConfigurationResponseValue200ApplicationJson(data);
  }

  /**
   * Update booking configuration
   *
   * Partially update a booking variant's configuration. Provider connection IDs must belong to the selected store; secret credentials are never accepted or returned here. Requires the `listing` Sanctum ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.product - The booking product ID or slug.
   * @example "41"
   * @param options.variant - The variant path parameter.
   * @example 73
   * @returns {Promise<SdkUpdateBookingConfigurationResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async update(options: UpdateOptions): Promise<SdkUpdateBookingConfigurationResponseValue200ApplicationJson> {
    const { product, variant, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.patch<SdkUpdateBookingConfigurationResponseValue200ApplicationJsonResponse, SdkUpdateBookingConfigurationRequestApplicationJsonResponse>(
      `/v2/products/${encodeURIComponent(product)}/variants/${encodeURIComponent(variant)}/booking`,
      serializeSdkUpdateBookingConfigurationRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'updateBookingConfiguration' },
    );
    return deserializeSdkUpdateBookingConfigurationResponseValue200ApplicationJson(data);
  }
}
