// This file is auto-generated by oagen. Do not edit.

import type { SellApp } from '../sellapp';
import type { GetOptions as RequestOptions } from '../common/interfaces/get-options.interface';
import { AutoPaginatable } from '../common/utils/pagination';
import { fetchAndDeserialize } from '../common/utils/fetch-and-deserialize';
import type { GroupsListOptions } from './interfaces/groups-list-options.interface';
import type { CreateOptions } from './interfaces/create-options.interface';
import type { GetOptions } from './interfaces/get-options.interface';
import type { UpdateOptions } from './interfaces/update-options.interface';
import type { DeleteOptions } from './interfaces/delete-options.interface';
import type { SearchOptions } from './interfaces/search-options.interface';
import type { ListGroupsResponseValue200ApplicationJsonPropertyDataItem, ListGroupsResponseValue200ApplicationJsonPropertyDataItemResponse } from './interfaces/list-groups-response-value-200-application-json-property-data-item.interface';
import type { SdkCreateGroupResponseValue201ApplicationJson, SdkCreateGroupResponseValue201ApplicationJsonResponse } from './interfaces/sdk-create-group-response-value-201-application-json.interface';
import type { SdkGetGroupResponseValue200ApplicationJson, SdkGetGroupResponseValue200ApplicationJsonResponse } from './interfaces/sdk-get-group-response-value-200-application-json.interface';
import type { SdkUpdateGroupResponseValue200ApplicationJson, SdkUpdateGroupResponseValue200ApplicationJsonResponse } from './interfaces/sdk-update-group-response-value-200-application-json.interface';
import type { SearchGroupsResponseValue200ApplicationJsonPropertyDataItem, SearchGroupsResponseValue200ApplicationJsonPropertyDataItemResponse } from './interfaces/search-groups-response-value-200-application-json-property-data-item.interface';
import type { SdkCreateGroupRequestApplicationJsonResponse } from './interfaces/sdk-create-group-request-application-json.interface';
import type { SdkUpdateGroupRequestApplicationJsonResponse } from './interfaces/sdk-update-group-request-application-json.interface';
import type { SdkSearchGroupsRequestApplicationJsonResponse } from './interfaces/sdk-search-groups-request-application-json.interface';
import { deserializeListGroupsResponseValue200ApplicationJsonPropertyDataItem } from './serializers/list-groups-response-value-200-application-json-property-data-item.serializer';
import { deserializeSdkCreateGroupResponseValue201ApplicationJson } from './serializers/sdk-create-group-response-value-201-application-json.serializer';
import { deserializeSdkGetGroupResponseValue200ApplicationJson } from './serializers/sdk-get-group-response-value-200-application-json.serializer';
import { deserializeSdkUpdateGroupResponseValue200ApplicationJson } from './serializers/sdk-update-group-response-value-200-application-json.serializer';
import { deserializeSearchGroupsResponseValue200ApplicationJsonPropertyDataItem } from './serializers/search-groups-response-value-200-application-json-property-data-item.serializer';
import { serializeSdkCreateGroupRequestApplicationJson } from './serializers/sdk-create-group-request-application-json.serializer';
import { serializeSdkUpdateGroupRequestApplicationJson } from './serializers/sdk-update-group-request-application-json.serializer';
import { serializeSdkSearchGroupsRequestApplicationJson } from './serializers/sdk-search-groups-request-application-json.serializer';

interface SellAppResponseEnvelope<T> { data: T; status: number; headers: Headers; requestId?: string }
type SellAppWithResponse<T extends object> = {
  [K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never]:
    T[K] extends (...args: infer A) => Promise<infer R> ? (...args: A) => Promise<SellAppResponseEnvelope<R>> : never;
};
function createResourceWithResponse<T extends object>(resource: T, client: SellApp): SellAppWithResponse<T> {
  return new Proxy({} as SellAppWithResponse<T>, {
    get: (_target, property) => (...args: unknown[]) => client.captureResponse(
      () => (resource[property as keyof T] as (...values: unknown[]) => Promise<unknown>).apply(resource, args),
    ),
  }) as SellAppWithResponse<T>;
}

export class Groups {
  constructor(private readonly sellApp: SellApp) {}
  get withResponse(): SellAppWithResponse<this> { return createResourceWithResponse(this, this.sellApp); }

  /**
   * List all groups
   *
   * List your store's groups, 15 per page by default. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<ListGroupsResponseValue200ApplicationJsonPropertyDataItem>>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async list(options?: GroupsListOptions): Promise<AutoPaginatable<ListGroupsResponseValue200ApplicationJsonPropertyDataItem, GroupsListOptions>> {
    const paginationOptions = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<ListGroupsResponseValue200ApplicationJsonPropertyDataItemResponse, ListGroupsResponseValue200ApplicationJsonPropertyDataItem>(
        this.sellApp,
        '/v2/groups',
        deserializeListGroupsResponseValue200ApplicationJsonPropertyDataItem,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<ListGroupsResponseValue200ApplicationJsonPropertyDataItemResponse, ListGroupsResponseValue200ApplicationJsonPropertyDataItem>(
          this.sellApp,
          '/v2/groups',
          deserializeListGroupsResponseValue200ApplicationJsonPropertyDataItem,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * Create a group
   *
   * Create a group for related products. Supply product_ids and section_id to save the group, ordered product membership, and section together. The whole change rolls back if any selected product is invalid. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @returns {Promise<SdkCreateGroupResponseValue201ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async create(options: CreateOptions): Promise<SdkCreateGroupResponseValue201ApplicationJson> {
    const { requestOptions, ...payload } = options;
    const { data } = await this.sellApp.post<SdkCreateGroupResponseValue201ApplicationJsonResponse, SdkCreateGroupRequestApplicationJsonResponse>(
      '/v2/groups',
      serializeSdkCreateGroupRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'createGroup' },
    );
    return deserializeSdkCreateGroupResponseValue201ApplicationJson(data);
  }

  /**
   * Retrieve a group
   *
   * Retrieve a group by its ID. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.group - The group path parameter.
   * @example 1
   * @returns {Promise<SdkGetGroupResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async get(options: GetOptions): Promise<SdkGetGroupResponseValue200ApplicationJson> {
    const { group } = options;
    const { data } = await this.sellApp.get<SdkGetGroupResponseValue200ApplicationJsonResponse>(`/v2/groups/${encodeURIComponent(group)}`, { ...options.requestOptions, operationId: 'getGroup' });
    return deserializeSdkGetGroupResponseValue200ApplicationJson(data);
  }

  /**
   * Update a group
   *
   * Update a group's details. Supply product_ids and section_id to save the group, ordered product membership, and section together. The whole change rolls back if any selected product is invalid. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.group - The group path parameter.
   * @example 1
   * @returns {Promise<SdkUpdateGroupResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async update(options: UpdateOptions): Promise<SdkUpdateGroupResponseValue200ApplicationJson> {
    const { group, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.patch<SdkUpdateGroupResponseValue200ApplicationJsonResponse, SdkUpdateGroupRequestApplicationJsonResponse>(
      `/v2/groups/${encodeURIComponent(group)}`,
      serializeSdkUpdateGroupRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'updateGroup' },
    );
    return deserializeSdkUpdateGroupResponseValue200ApplicationJson(data);
  }

  /**
   * Delete a group
   *
   * Deletes a group. This will permanently delete the group and its details. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.group - The group path parameter.
   * @example 1
   * @returns {Promise<void>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async delete(options: DeleteOptions): Promise<void> {
    const { group } = options;
    await this.sellApp.delete(`/v2/groups/${encodeURIComponent(group)}`, { ...options.requestOptions, operationId: 'deleteGroup' });
  }

  /**
   * Search groups
   *
   * Search groups using JSON body filters, search terms, includes, and sort instructions. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<SearchGroupsResponseValue200ApplicationJsonPropertyDataItem>>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async search(options: SearchOptions): Promise<SdkSearchGroupsResponseValue200ApplicationJson> {
    const { requestOptions, ...payload } = options;
    const { data } = await this.sellApp.post<SdkSearchGroupsResponseValue200ApplicationJsonResponse, SdkSearchGroupsRequestApplicationJsonResponse>(
      '/v2/groups/search',
      serializeSdkSearchGroupsRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'searchGroups' },
    );
    return deserializeSdkSearchGroupsResponseValue200ApplicationJson(data);
  }
}
