// This file is auto-generated by oagen. Do not edit.

import type { SellApp } from '../sellapp';
import type { GetOptions as RequestOptions } from '../common/interfaces/get-options.interface';
import { AutoPaginatable } from '../common/utils/pagination';
import { fetchAndDeserialize } from '../common/utils/fetch-and-deserialize';
import type { PostOptions } from '../common/interfaces/post-options.interface';
import type { CustomersListOptions } from './interfaces/customers-list-options.interface';
import type { CreateCustomerOptions } from './interfaces/create-customer-options.interface';
import type { SearchOptions } from './interfaces/search-options.interface';
import type { GetOptions } from './interfaces/get-options.interface';
import type { UpdateCustomerOptions } from './interfaces/update-customer-options.interface';
import type { GetCustomerByExternalIdOptions } from './interfaces/get-customer-by-external-id-options.interface';
import type { UpsertByExternalIdOptions } from './interfaces/upsert-by-external-id-options.interface';
import type { UpdateCustomerByExternalIdOptions } from './interfaces/update-customer-by-external-id-options.interface';
import type { SdkListCustomersResponseValue200ApplicationJson, SdkListCustomersResponseValue200ApplicationJsonResponse } from './interfaces/sdk-list-customers-response-value-200-application-json.interface';
import type { SdkCreateCustomerResponseValue201ApplicationJson, SdkCreateCustomerResponseValue201ApplicationJsonResponse } from './interfaces/sdk-create-customer-response-value-201-application-json.interface';
import type { SdkSearchCustomersResponseValue200ApplicationJson, SdkSearchCustomersResponseValue200ApplicationJsonResponse } from './interfaces/sdk-search-customers-response-value-200-application-json.interface';
import type { SdkGetCustomerResponseValue200ApplicationJson, SdkGetCustomerResponseValue200ApplicationJsonResponse } from './interfaces/sdk-get-customer-response-value-200-application-json.interface';
import type { SdkUpdateCustomerResponseValue200ApplicationJson, SdkUpdateCustomerResponseValue200ApplicationJsonResponse } from './interfaces/sdk-update-customer-response-value-200-application-json.interface';
import type { SdkUpsertCustomerResponseValue200ApplicationJson, SdkUpsertCustomerResponseValue200ApplicationJsonResponse } from './interfaces/sdk-upsert-customer-response-value-200-application-json.interface';
import type { SdkCreateCustomerRequestApplicationJsonResponse } from './interfaces/sdk-create-customer-request-application-json.interface';
import type { SdkSearchCustomersRequestApplicationJsonResponse } from './interfaces/sdk-search-customers-request-application-json.interface';
import type { SdkUpdateCustomerRequestApplicationJsonResponse } from './interfaces/sdk-update-customer-request-application-json.interface';
import type { SdkUpsertCustomerRequestApplicationJsonResponse } from './interfaces/sdk-upsert-customer-request-application-json.interface';
import { deserializeSdkListCustomersResponseValue200ApplicationJson } from './serializers/sdk-list-customers-response-value-200-application-json.serializer';
import { deserializeSdkCreateCustomerResponseValue201ApplicationJson } from './serializers/sdk-create-customer-response-value-201-application-json.serializer';
import { deserializeSdkSearchCustomersResponseValue200ApplicationJson } from './serializers/sdk-search-customers-response-value-200-application-json.serializer';
import { deserializeSdkGetCustomerResponseValue200ApplicationJson } from './serializers/sdk-get-customer-response-value-200-application-json.serializer';
import { deserializeSdkUpdateCustomerResponseValue200ApplicationJson } from './serializers/sdk-update-customer-response-value-200-application-json.serializer';
import { deserializeSdkUpsertCustomerResponseValue200ApplicationJson } from './serializers/sdk-upsert-customer-response-value-200-application-json.serializer';
import { serializeSdkCreateCustomerRequestApplicationJson } from './serializers/sdk-create-customer-request-application-json.serializer';
import { serializeSdkSearchCustomersRequestApplicationJson } from './serializers/sdk-search-customers-request-application-json.serializer';
import { serializeSdkUpdateCustomerRequestApplicationJson } from './serializers/sdk-update-customer-request-application-json.serializer';
import { serializeSdkUpsertCustomerRequestApplicationJson } from './serializers/sdk-upsert-customer-request-application-json.serializer';

interface SellAppResponseEnvelope<T> { data: T; status: number; headers: Headers; requestId?: string }
type SellAppWithResponse<T extends object> = {
  [K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never]:
    T[K] extends (...args: infer A) => Promise<infer R> ? (...args: A) => Promise<SellAppResponseEnvelope<R>> : never;
};
function createResourceWithResponse<T extends object>(resource: T, client: SellApp): SellAppWithResponse<T> {
  return new Proxy({} as SellAppWithResponse<T>, {
    get: (_target, property) => (...args: unknown[]) => client.captureResponse(
      () => (resource[property as keyof T] as (...values: unknown[]) => Promise<unknown>).apply(resource, args),
    ),
  }) as SellAppWithResponse<T>;
}

export class Customers {
  constructor(private readonly sellApp: SellApp) {}
  get withResponse(): SellAppWithResponse<this> { return createResourceWithResponse(this, this.sellApp); }

  /**
   * List customers
   *
   * List customer profiles for the authenticated store. Requires the `invoice` Sanctum ability and matching store permission. Responses deliberately redact checkout IP, billing, location, and community identity data. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<SdkListCustomersResponseValue200ApplicationJson>>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async list(options?: CustomersListOptions): Promise<AutoPaginatable<SdkListCustomersResponseValue200ApplicationJson, CustomersListOptions>> {
    const paginationOptions = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<SdkListCustomersResponseValue200ApplicationJsonResponse, SdkListCustomersResponseValue200ApplicationJson>(
        this.sellApp,
        '/v2/customers',
        deserializeSdkListCustomersResponseValue200ApplicationJson,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<SdkListCustomersResponseValue200ApplicationJsonResponse, SdkListCustomersResponseValue200ApplicationJson>(
          this.sellApp,
          '/v2/customers',
          deserializeSdkListCustomersResponseValue200ApplicationJson,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * Create a customer
   *
   * Create a customer with normalized unique email and immutable-per-store external_id. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @returns {Promise<SdkCreateCustomerResponseValue201ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async createCustomer(options: CreateCustomerOptions): Promise<SdkCreateCustomerResponseValue201ApplicationJson> {
    const { requestOptions, ...payload } = options;
    const { data } = await this.sellApp.post<SdkCreateCustomerResponseValue201ApplicationJsonResponse, SdkCreateCustomerRequestApplicationJsonResponse>(
      '/v2/customers',
      serializeSdkCreateCustomerRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'createCustomer' },
    );
    return deserializeSdkCreateCustomerResponseValue201ApplicationJson(data);
  }

  /**
   * Search customers
   *
   * Search customer email identities and compose supported ID or email filters and deterministic sorts. Requires the `invoice` Sanctum ability and matching store permission. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<SdkSearchCustomersResponseValue200ApplicationJson>>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async search(options: SearchOptions): Promise<SdkSearchCustomersResponseValue200ApplicationJson> {
    const { page, pagination, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.post<SdkSearchCustomersResponseValue200ApplicationJsonResponse, SdkSearchCustomersRequestApplicationJsonResponse>(
      '/v2/customers/search',
      serializeSdkSearchCustomersRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'searchCustomers', query: { ...(options.page !== undefined && { page: options.page }), ...(options.pagination !== undefined && { pagination: options.pagination }) } },
    );
    return deserializeSdkSearchCustomersResponseValue200ApplicationJson(data);
  }

  /**
   * Retrieve a customer
   *
   * Retrieve a store-scoped customer profile and concise order, line-item, subscription, and revenue insights. Wallet insights are included only when the token and staff role also have wallet or store management permission. Requires the `invoice` Sanctum ability and matching store permission. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.customer - The customer path parameter.
   * @example 125
   * @returns {Promise<SdkGetCustomerResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async get(options: GetOptions): Promise<SdkGetCustomerResponseValue200ApplicationJson> {
    const { customer } = options;
    const { data } = await this.sellApp.get<SdkGetCustomerResponseValue200ApplicationJsonResponse>(`/v2/customers/${encodeURIComponent(customer)}`, { ...options.requestOptions, operationId: 'getCustomer' });
    return deserializeSdkGetCustomerResponseValue200ApplicationJson(data);
  }

  /**
   * Update a customer
   *
   * Update name, BCP 47 locale, normalized email, or constrained scalar metadata. Assign external_id when it is unset; changing an existing external_id returns 409. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.customer - The customer identifier.
   * @example 314
   * @returns {Promise<SdkUpdateCustomerResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async updateCustomer(options: UpdateCustomerOptions): Promise<SdkUpdateCustomerResponseValue200ApplicationJson> {
    const { customer, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.patch<SdkUpdateCustomerResponseValue200ApplicationJsonResponse, SdkUpdateCustomerRequestApplicationJsonResponse>(
      `/v2/customers/${encodeURIComponent(customer)}`,
      serializeSdkUpdateCustomerRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'updateCustomer' },
    );
    return deserializeSdkUpdateCustomerResponseValue200ApplicationJson(data);
  }

  /**
   * Retrieve a customer by external ID
   *
   * Resolve by immutable store-local external ID. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.externalId - The externalId identifier.
   * @example "314"
   * @returns {Promise<SdkGetCustomerResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async getCustomerByExternalId(options: GetCustomerByExternalIdOptions): Promise<SdkGetCustomerResponseValue200ApplicationJson> {
    const { externalId } = options;
    const { data } = await this.sellApp.get<SdkGetCustomerResponseValue200ApplicationJsonResponse>(`/v2/customers/external/${encodeURIComponent(externalId)}`, { ...options.requestOptions, operationId: 'getCustomerByExternalId' });
    return deserializeSdkGetCustomerResponseValue200ApplicationJson(data);
  }

  /**
   * Create or update a customer by external ID
   *
   * Create a customer when the store-local external ID is new, or update the same customer when it already exists. Requires the invoice API-key ability and store invoice permission. Send email on every call; omitted name, locale, and metadata remain unchanged. Metadata replaces the complete metadata object when supplied. The external ID comes from the URL and cannot be changed in the body. An email already used by another customer returns 422; a concurrent email or external-ID collision returns 409. Retrieve the customer and check its identity before retrying. Accounts are never merged. Returns 201 on creation and 200 on update. Reusing the external ID preserves customer identity. Use the same optional Idempotency-Key and body to replay an identical response. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.externalId - Store-local external ID, 1–255 characters; whitespace-only values are invalid. URL-encode it as one path segment.
   * @example "crm_maya_314"
   * @returns {Promise<SdkUpsertCustomerResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async upsertByExternalId(options: UpsertByExternalIdOptions): Promise<SdkUpsertCustomerResponseValue200ApplicationJson> {
    const { externalId, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.put<SdkUpsertCustomerResponseValue200ApplicationJsonResponse, SdkUpsertCustomerRequestApplicationJsonResponse>(
      `/v2/customers/external/${encodeURIComponent(externalId)}`,
      serializeSdkUpsertCustomerRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'upsertCustomerByExternalId' },
    );
    return deserializeSdkUpsertCustomerResponseValue200ApplicationJson(data);
  }

  /**
   * Update a customer by external ID
   *
   * Update the customer resolved by immutable external ID. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.externalId - The externalId identifier.
   * @example "314"
   * @returns {Promise<SdkUpdateCustomerResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async updateCustomerByExternalId(options: UpdateCustomerByExternalIdOptions): Promise<SdkUpdateCustomerResponseValue200ApplicationJson> {
    const { externalId, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.patch<SdkUpdateCustomerResponseValue200ApplicationJsonResponse, SdkUpdateCustomerRequestApplicationJsonResponse>(
      `/v2/customers/external/${encodeURIComponent(externalId)}`,
      serializeSdkUpdateCustomerRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'updateCustomerByExternalId' },
    );
    return deserializeSdkUpdateCustomerResponseValue200ApplicationJson(data);
  }
}
