// This file is auto-generated by oagen. Do not edit.

import type { ListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItem, ListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItemResponse } from '../interfaces/list-order-deliverables-response-value-200-application-json-property-data-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable } from './list-order-deliverables-response-value-200-application-json-property-data-item-property-deliverable.serializer';
import { deserializeListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem } from './list-order-deliverables-response-value-200-application-json-property-data-item-property-additional-information-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItem","required":["orderId","lineItemId","type","status","productVariantId","quantity","deliverable","additionalInformation"],"properties":{"orderId":{"kind":"primitive","type":"integer"},"lineItemId":{"kind":"primitive","type":"integer"},"type":{"kind":"primitive","type":"string"},"status":{"kind":"enum","values":["pending","delivered"]},"productVariantId":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"quantity":{"kind":"primitive","type":"integer"},"deliverable":{"kind":"any"},"additionalInformation":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItem","required":["order_id","line_item_id","type","status","product_variant_id","quantity","deliverable","additional_information"],"properties":{"order_id":{"kind":"primitive","type":"integer"},"line_item_id":{"kind":"primitive","type":"integer"},"type":{"kind":"primitive","type":"string"},"status":{"kind":"enum","values":["pending","delivered"]},"product_variant_id":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"quantity":{"kind":"primitive","type":"integer"},"deliverable":{"kind":"any"},"additional_information":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const deserializeListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItem = (
  response: ListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItemResponse,
): ListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItem => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["order_id","line_item_id","type","status","product_variant_id","quantity","deliverable","additional_information"]),
    orderId: response.order_id,
    lineItemId: response.line_item_id,
    type: response.type,
    status: response.status,
    productVariantId: response.product_variant_id ?? null,
    quantity: response.quantity,
    deliverable: deserializeListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable(response.deliverable),
    additionalInformation: response.additional_information.map(deserializeListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem),
  };
};
