// This file is auto-generated by oagen. Do not edit.

import type { RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyTimelineItem, RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyTimelineItemResponse } from '../interfaces/retry-order-dynamic-delivery-response-value-202-application-json-property-data-property-timeline-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyTimelineItem","required":["status","setAt"],"properties":{"status":{"kind":"enum","values":["PENDING","REVERSED","PARTIAL","VOIDED","REFUNDED","PAID","COMPLETED","DISPUTING","REVIEW","FAILED"]},"setAt":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyTimelineItem","required":["status","set_at"],"properties":{"status":{"kind":"enum","values":["PENDING","REVERSED","PARTIAL","VOIDED","REFUNDED","PAID","COMPLETED","DISPUTING","REVIEW","FAILED"]},"set_at":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};

export const deserializeRetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyTimelineItem = (
  response: RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyTimelineItemResponse,
): RetryOrderDynamicDeliveryResponseValue202ApplicationJsonPropertyDataPropertyTimelineItem => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["status","set_at"]),
    status: response.status,
    setAt: new Date(response.set_at),
  };
};
