// This file is auto-generated by oagen. Do not edit.

import type { SdkPayOrderFromWalletResponseValue200ApplicationJson, SdkPayOrderFromWalletResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-pay-order-from-wallet-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializePayOrderFromWalletResponseValue200ApplicationJsonPropertyData } from './pay-order-from-wallet-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkPayOrderFromWalletResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkPayOrderFromWalletResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkPayOrderFromWalletResponseValue200ApplicationJson = (
  response: SdkPayOrderFromWalletResponseValue200ApplicationJsonResponse,
): SdkPayOrderFromWalletResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializePayOrderFromWalletResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
