// This file is auto-generated by oagen. Do not edit.

export { deserializeListOrdersResponseValue200ApplicationJsonPropertyDataItemPropertyPayment as deserializeSearchOrdersResponseValue200ApplicationJsonPropertyDataItemPropertyPayment } from './list-orders-response-value-200-application-json-property-data-item-property-payment.serializer';
