// This file is auto-generated by oagen. Do not edit.

import type { GetOptions as RequestOptions } from '../../common/interfaces/get-options.interface';
import type { SdkUpdateCustomerWalletStatusRequestApplicationJsonStatus } from '../../wallet-settings/interfaces/sdk-update-customer-wallet-status-request-application-json-status.interface';

export interface UpdateStatusOptions {
  /** Per-call timeout, retry, headers, cancellation, and lifecycle metadata. */
  requestOptions?: RequestOptions;
  /** The customer path parameter. */
  customer: number;
  status: SdkUpdateCustomerWalletStatusRequestApplicationJsonStatus | (string & Record<never, never>);
}
