// This file is auto-generated by oagen. Do not edit.

import type { PauseSubscriptionResponseValue200ApplicationJsonPropertyData, PauseSubscriptionResponseValue200ApplicationJsonPropertyDataResponse } from './pause-subscription-response-value-200-application-json-property-data.interface';

export interface SdkPauseSubscriptionResponseValue200ApplicationJson {
  data: PauseSubscriptionResponseValue200ApplicationJsonPropertyData;
  message: string;
  [key: string]: unknown;
}

export interface SdkPauseSubscriptionResponseValue200ApplicationJsonResponse {
  data: PauseSubscriptionResponseValue200ApplicationJsonPropertyDataResponse;
  message: string;
  [key: string]: unknown;
}
