// This file is auto-generated by oagen. Do not edit.

export const SdkConfirmSubscriptionPlanChangeRequestApplicationJsonEffectiveTiming = {
  Immediate: 'immediate',
  NextRenewal: 'next_renewal',
} as const;

export type SdkConfirmSubscriptionPlanChangeRequestApplicationJsonEffectiveTiming =
  | (typeof SdkConfirmSubscriptionPlanChangeRequestApplicationJsonEffectiveTiming)[keyof typeof SdkConfirmSubscriptionPlanChangeRequestApplicationJsonEffectiveTiming]
  | (string & Record<never, never>);
