// This file is auto-generated by oagen. Do not edit.

import type { CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyPaymentPropertyOriginalAmountPropertyTotal, CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyPaymentPropertyOriginalAmountPropertyTotalResponse } from './create-invoice-refund-response-value-200-application-json-property-data-property-invoice-property-payment-property-original-amount-property-total.interface';

export interface CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyPaymentPropertyOriginalAmount {
  base: string;
  currency: string;
  units: number;
  vat: number;
  total: CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyPaymentPropertyOriginalAmountPropertyTotal;
  [key: string]: unknown;
}

export interface CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyPaymentPropertyOriginalAmountResponse {
  base: string;
  currency: string;
  units: number;
  vat: number;
  total: CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyPaymentPropertyOriginalAmountPropertyTotalResponse;
  [key: string]: unknown;
}
