// This file is auto-generated by oagen. Do not edit.

import type { ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusPropertyHistoryItem, ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusPropertyHistoryItemResponse } from './list-invoices-response-value-200-application-json-property-data-item-property-status-property-history-item.interface';
import type { ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusPropertyStatus, ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusPropertyStatusResponse } from './list-invoices-response-value-200-application-json-property-data-item-property-status-property-status.interface';

export interface ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatus {
  history: ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusPropertyHistoryItem[];
  status: ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusPropertyStatus;
  [key: string]: unknown;
}

export interface ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusResponse {
  history: ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusPropertyHistoryItemResponse[];
  status: ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusPropertyStatusResponse;
  [key: string]: unknown;
}
