// This file is auto-generated by oagen. Do not edit.

import type { MarkPendingInvoiceCompletedResponseValue200ApplicationJsonPropertyPaymentPropertyFullPricePropertyTotal, MarkPendingInvoiceCompletedResponseValue200ApplicationJsonPropertyPaymentPropertyFullPricePropertyTotalResponse } from './mark-pending-invoice-completed-response-value-200-application-json-property-payment-property-full-price-property-total.interface';

export interface MarkPendingInvoiceCompletedResponseValue200ApplicationJsonPropertyPaymentPropertyFullPrice {
  base: string;
  currency: string;
  units: number;
  vat: number;
  total: MarkPendingInvoiceCompletedResponseValue200ApplicationJsonPropertyPaymentPropertyFullPricePropertyTotal;
  [key: string]: unknown;
}

export interface MarkPendingInvoiceCompletedResponseValue200ApplicationJsonPropertyPaymentPropertyFullPriceResponse {
  base: string;
  currency: string;
  units: number;
  vat: number;
  total: MarkPendingInvoiceCompletedResponseValue200ApplicationJsonPropertyPaymentPropertyFullPricePropertyTotalResponse;
  [key: string]: unknown;
}
