// This file is auto-generated by oagen. Do not edit.

import type { CreateInvoiceRequestApplicationJsonPropertyExtra, CreateInvoiceRequestApplicationJsonPropertyExtraResponse } from './create-invoice-request-application-json-property-extra.interface';
import type { CreateInvoiceRequestApplicationJsonPropertyProductVariants, CreateInvoiceRequestApplicationJsonPropertyProductVariantsResponse } from './create-invoice-request-application-json-property-product-variants.interface';
import type { SdkCreateInvoiceRequestApplicationJsonPaymentMethod } from './sdk-create-invoice-request-application-json-payment-method.interface';

export interface SdkCreateInvoiceRequestApplicationJson {
  customerEmail: string;
  customerIp?: string | null;
  paymentMethod: SdkCreateInvoiceRequestApplicationJsonPaymentMethod | (string & Record<never, never>);
  coupon?: string;
  vatId?: string;
  country?: string;
  affiliate?: string | null;
  extra?: CreateInvoiceRequestApplicationJsonPropertyExtra;
  productVariants: CreateInvoiceRequestApplicationJsonPropertyProductVariants;
  [key: string]: unknown;
}

export interface SdkCreateInvoiceRequestApplicationJsonResponse {
  customer_email: string;
  customer_ip?: string | null;
  payment_method: SdkCreateInvoiceRequestApplicationJsonPaymentMethod | (string & Record<never, never>);
  coupon?: string;
  vat_id?: string;
  country?: string;
  affiliate?: string | null;
  extra?: CreateInvoiceRequestApplicationJsonPropertyExtraResponse;
  product_variants: CreateInvoiceRequestApplicationJsonPropertyProductVariantsResponse;
  [key: string]: unknown;
}
