// This file is auto-generated by oagen. Do not edit.

import type { SellApp } from '../sellapp';
import type { GetOptions as RequestOptions } from '../common/interfaces/get-options.interface';
import type { ListCustomerEntitlementsOptions } from './interfaces/list-customer-entitlements-options.interface';
import type { ListCustomerEntitlementsByExternalIdOptions } from './interfaces/list-customer-entitlements-by-external-id-options.interface';
import type { SdkListCustomerEntitlementsResponseValue200ApplicationJson, SdkListCustomerEntitlementsResponseValue200ApplicationJsonResponse } from './interfaces/sdk-list-customer-entitlements-response-value-200-application-json.interface';
import { deserializeSdkListCustomerEntitlementsResponseValue200ApplicationJson } from './serializers/sdk-list-customer-entitlements-response-value-200-application-json.serializer';

interface SellAppResponseEnvelope<T> { data: T; status: number; headers: Headers; requestId?: string }
type SellAppWithResponse<T extends object> = {
  [K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never]:
    T[K] extends (...args: infer A) => Promise<infer R> ? (...args: A) => Promise<SellAppResponseEnvelope<R>> : never;
};
function createResourceWithResponse<T extends object>(resource: T, client: SellApp): SellAppWithResponse<T> {
  return new Proxy({} as SellAppWithResponse<T>, {
    get: (_target, property) => (...args: unknown[]) => client.captureResponse(
      () => (resource[property as keyof T] as (...values: unknown[]) => Promise<unknown>).apply(resource, args),
    ),
  }) as SellAppWithResponse<T>;
}

export class Entitlements {
  constructor(private readonly sellApp: SellApp) {}
  get withResponse(): SellAppWithResponse<this> { return createResourceWithResponse(this, this.sellApp); }

  /**
   * List customer entitlements
   *
   * Unified access without raw keys, serials, files, dynamic payloads, or seller-only metadata. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.customer - The customer identifier.
   * @example 42
   * @returns {Promise<SdkListCustomerEntitlementsResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async listCustomerEntitlements(options: ListCustomerEntitlementsOptions): Promise<SdkListCustomerEntitlementsResponseValue200ApplicationJson> {
    const { customer } = options;
    const { data } = await this.sellApp.get<SdkListCustomerEntitlementsResponseValue200ApplicationJsonResponse>(`/v2/customers/${encodeURIComponent(customer)}/entitlements`, { ...options.requestOptions, operationId: 'listCustomerEntitlements' });
    return deserializeSdkListCustomerEntitlementsResponseValue200ApplicationJson(data);
  }

  /**
   * List customer entitlements
   *
   * Unified access without raw keys, serials, files, dynamic payloads, or seller-only metadata. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.externalId - The externalId identifier.
   * @example "externalId_01K4CUSTOMER"
   * @returns {Promise<SdkListCustomerEntitlementsResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async listCustomerEntitlementsByExternalId(options: ListCustomerEntitlementsByExternalIdOptions): Promise<SdkListCustomerEntitlementsResponseValue200ApplicationJson> {
    const { externalId } = options;
    const { data } = await this.sellApp.get<SdkListCustomerEntitlementsResponseValue200ApplicationJsonResponse>(`/v2/customers/external/${encodeURIComponent(externalId)}/entitlements`, { ...options.requestOptions, operationId: 'listCustomerEntitlementsByExternalId' });
    return deserializeSdkListCustomerEntitlementsResponseValue200ApplicationJson(data);
  }
}
