// This file is auto-generated by oagen. Do not edit.

export { deserializeListGroupsResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItem as deserializeCreateGroupResponseValue201ApplicationJsonPropertyDataPropertyProductsItem } from './list-groups-response-value-200-application-json-property-data-item-property-products-item.serializer';
