// This file is auto-generated by oagen. Do not edit.

import type { SearchProductsWithinGroupRequestApplicationJsonPropertySortItem, SearchProductsWithinGroupRequestApplicationJsonPropertySortItemResponse } from '../interfaces/search-products-within-group-request-application-json-property-sort-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SearchProductsWithinGroupRequestApplicationJsonPropertySortItem","required":["field"],"properties":{"field":{"kind":"primitive","type":"string"},"direction":{"kind":"enum","values":["asc","desc"]}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SearchProductsWithinGroupRequestApplicationJsonPropertySortItem","required":["field"],"properties":{"field":{"kind":"primitive","type":"string"},"direction":{"kind":"enum","values":["asc","desc"]}},"additionalProperties":true};

export const serializeSearchProductsWithinGroupRequestApplicationJsonPropertySortItem = (
  model: SearchProductsWithinGroupRequestApplicationJsonPropertySortItem,
): SearchProductsWithinGroupRequestApplicationJsonPropertySortItemResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["field","direction"]),
    field: model.field,
    direction: model.direction,
  };
};
