// This file is auto-generated by oagen. Do not edit.

export { deserializeListGroupsResponseValue200ApplicationJsonPropertyDataItemPropertyImageValuePropertyMetadata as deserializeSyncGroupProductsResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata } from './list-groups-response-value-200-application-json-property-data-item-property-image-value-property-metadata.serializer';
