// This file is auto-generated by oagen. Do not edit.

export interface AppendVariantSerialInventoryResponseValue201ApplicationJsonPropertyData {
  previousCount: number;
  currentCount: number;
  submittedCount: number;
  [key: string]: unknown;
}

export interface AppendVariantSerialInventoryResponseValue201ApplicationJsonPropertyDataResponse {
  previous_count: number;
  current_count: number;
  submitted_count: number;
  [key: string]: unknown;
}
