// This file is auto-generated by oagen. Do not edit.

import type { PaginationOptions } from '../../common/interfaces/pagination-options.interface';

export interface VariantSerialsListOptions extends PaginationOptions {
  /** The product path parameter. */
  product: number;
  /** The variant path parameter. */
  variant: number;
  /** Filter inventory by a partial serial value. */
  search?: string;
  /** Page number to return. */
  page?: number;
}
