// This file is auto-generated by oagen. Do not edit.

export const AddHighlightMediaResponseValue201ApplicationJsonPropertyDataType = {
  Image: 'image',
  Video: 'video',
} as const;

export type AddHighlightMediaResponseValue201ApplicationJsonPropertyDataType =
  | (typeof AddHighlightMediaResponseValue201ApplicationJsonPropertyDataType)[keyof typeof AddHighlightMediaResponseValue201ApplicationJsonPropertyDataType]
  | (string & Record<never, never>);
