// This file is auto-generated by oagen. Do not edit.

export const GetHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType = {
  Image: 'image',
  Video: 'video',
} as const;

export type GetHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType =
  | (typeof GetHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType)[keyof typeof GetHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType]
  | (string & Record<never, never>);
