// This file is auto-generated by oagen. Do not edit.

export const SearchHighlightsRequestApplicationJsonPropertySortItemDirection = {
  Asc: 'asc',
  Desc: 'desc',
} as const;

export type SearchHighlightsRequestApplicationJsonPropertySortItemDirection =
  | (typeof SearchHighlightsRequestApplicationJsonPropertySortItemDirection)[keyof typeof SearchHighlightsRequestApplicationJsonPropertySortItemDirection]
  | (string & Record<never, never>);
