// This file is auto-generated by oagen. Do not edit.

export { deserializeActivateLicenseKeyResponseValue200ApplicationJsonPropertyData as deserializeGetLicenseInstanceResponseValue200ApplicationJsonPropertyData } from '../../licenses/serializers/activate-license-key-response-value-200-application-json-property-data.serializer';
