// This file is auto-generated by oagen. Do not edit.

import type { SdkApproveOAuthAuthorizationRequestApplicationXWwwFormUrlencoded, SdkApproveOAuthAuthorizationRequestApplicationXWwwFormUrlencodedResponse } from '../interfaces/sdk-approve-oauth-authorization-request-application-x-www-form-urlencoded.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkApproveOAuthAuthorizationRequestApplicationXWwwFormUrlencoded","required":["authToken","clientId","state","token"],"properties":{"authToken":{"kind":"primitive","type":"string"},"clientId":{"kind":"primitive","type":"string","format":"uuid"},"state":{"kind":"primitive","type":"string","constraints":{"minLength":1}},"token":{"kind":"primitive","type":"string"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkApproveOAuthAuthorizationRequestApplicationXWwwFormUrlencoded","required":["auth_token","client_id","state","token"],"properties":{"auth_token":{"kind":"primitive","type":"string"},"client_id":{"kind":"primitive","type":"string","format":"uuid"},"state":{"kind":"primitive","type":"string","constraints":{"minLength":1}},"token":{"kind":"primitive","type":"string"}},"additionalProperties":true};

export const serializeSdkApproveOAuthAuthorizationRequestApplicationXWwwFormUrlencoded = (
  model: SdkApproveOAuthAuthorizationRequestApplicationXWwwFormUrlencoded,
): SdkApproveOAuthAuthorizationRequestApplicationXWwwFormUrlencodedResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["authToken","clientId","state","token"]),
    auth_token: model.authToken,
    client_id: model.clientId,
    state: model.state,
    token: model.token,
  };
};
