// This file is auto-generated by oagen. Do not edit.

import type { CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType } from './create-reward-coupon-template-response-value-201-application-json-property-data-type.interface';
import type { CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataRedemptionMode } from './create-reward-coupon-template-response-value-201-application-json-property-data-redemption-mode.interface';

export interface CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyData {
  id: number;
  name: string;
  type: CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType | (string & Record<never, never>);
  discount: string;
  storeWide: boolean;
  minimumAmount?: string | null;
  maximumDiscountAmount?: string | null;
  expiresAt?: Date | null;
  expiresAfterDays?: number | null;
  redemptionMode: CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataRedemptionMode | (string & Record<never, never>);
  isActive: boolean;
  listingIds?: number[];
  createdAt?: Date | null;
  updatedAt?: Date | null;
  [key: string]: unknown;
}

export interface CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataResponse {
  id: number;
  name: string;
  type: CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType | (string & Record<never, never>);
  discount: string;
  store_wide: boolean;
  minimum_amount?: string | null;
  maximum_discount_amount?: string | null;
  expires_at?: string | null;
  expires_after_days?: number | null;
  redemption_mode: CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataRedemptionMode | (string & Record<never, never>);
  is_active: boolean;
  listing_ids?: number[];
  created_at?: string | null;
  updated_at?: string | null;
  [key: string]: unknown;
}
