// This file is auto-generated by oagen. Do not edit.

export type SdkListRewardCouponTemplatesResponseValue200ApplicationJson = Record<string, unknown>;

export type SdkListRewardCouponTemplatesResponseValue200ApplicationJsonResponse = Record<string, unknown>;
