// This file is auto-generated by oagen. Do not edit.

import type { GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType } from './get-refund-response-value-200-application-json-property-data-property-refundable-type.interface';

export interface GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundable {
  type: GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType | (string & Record<never, never>);
  id: number;
  [key: string]: unknown;
}

export interface GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableResponse {
  type: GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType | (string & Record<never, never>);
  id: number;
  [key: string]: unknown;
}
