// This file is auto-generated by oagen. Do not edit.

import type { BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem, BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemResponse } from './batch-update-products-response-value-200-application-json-property-data-item-property-images-item.interface';
import type { BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem, BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItemResponse } from './batch-update-products-response-value-200-application-json-property-data-item-property-additional-information-item.interface';
import type { BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings, BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettingsResponse } from './batch-update-products-response-value-200-application-json-property-data-item-property-other-settings.interface';
import type { BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem, BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItemResponse } from './batch-update-products-response-value-200-application-json-property-data-item-property-variants-item.interface';

export interface BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItem {
  id: number;
  title: string;
  slug: string;
  description: string;
  images: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem[];
  order: number | null;
  visibility: string;
  deliveryText: string | null;
  additionalInformation: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem[];
  otherSettings: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  storeId: number;
  sectionId: number | null;
  sectionOrder: number | null;
  isDiscoverable: boolean;
  variants: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem[];
  url: string;
  [key: string]: unknown;
}

export interface BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemResponse {
  id: number;
  title: string;
  slug: string;
  description: string;
  images: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemResponse[];
  order: number | null;
  visibility: string;
  delivery_text: string | null;
  additional_information: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItemResponse[];
  other_settings: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettingsResponse;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  store_id: number;
  section_id: number | null;
  section_order: number | null;
  is_discoverable: boolean;
  variants: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItemResponse[];
  url: string;
  [key: string]: unknown;
}
