// This file is auto-generated by oagen. Do not edit.

export const BatchCreateProductsRequestApplicationJsonPropertyResourcesItemPropertyAdditionalInformationItemType = {
  Text: 'text',
  Number: 'number',
  Email: 'email',
  Phone: 'phone',
  Currency: 'currency',
  Link: 'link',
  Textarea: 'textarea',
  Select: 'select',
  Radio: 'radio',
  CheckboxGroup: 'checkbox-group',
  Pillbox: 'pillbox',
  Checkbox: 'checkbox',
  Switch: 'switch',
  Date: 'date',
  DateRange: 'date-range',
  Hidden: 'hidden',
} as const;

export type BatchCreateProductsRequestApplicationJsonPropertyResourcesItemPropertyAdditionalInformationItemType =
  | (typeof BatchCreateProductsRequestApplicationJsonPropertyResourcesItemPropertyAdditionalInformationItemType)[keyof typeof BatchCreateProductsRequestApplicationJsonPropertyResourcesItemPropertyAdditionalInformationItemType]
  | (string & Record<never, never>);
