// This file is auto-generated by oagen. Do not edit.

import type { BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem, BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemResponse } from './batch-create-products-response-value-200-application-json-property-data-item-property-images-item.interface';
import type { BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem, BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItemResponse } from './batch-create-products-response-value-200-application-json-property-data-item-property-additional-information-item.interface';
import type { BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings, BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettingsResponse } from './batch-create-products-response-value-200-application-json-property-data-item-property-other-settings.interface';
import type { BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem, BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItemResponse } from './batch-create-products-response-value-200-application-json-property-data-item-property-variants-item.interface';

export interface BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItem {
  id: number;
  title: string;
  slug: string;
  description: string;
  images: BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem[];
  order: number | null;
  visibility: string;
  deliveryText: string | null;
  additionalInformation: BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem[];
  otherSettings: BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  storeId: number;
  sectionId: number | null;
  sectionOrder: number | null;
  isDiscoverable: boolean;
  variants: BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem[];
  url: string;
  [key: string]: unknown;
}

export interface BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemResponse {
  id: number;
  title: string;
  slug: string;
  description: string;
  images: BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemResponse[];
  order: number | null;
  visibility: string;
  delivery_text: string | null;
  additional_information: BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItemResponse[];
  other_settings: BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettingsResponse;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  store_id: number;
  section_id: number | null;
  section_order: number | null;
  is_discoverable: boolean;
  variants: BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItemResponse[];
  url: string;
  [key: string]: unknown;
}
