// This file is auto-generated by oagen. Do not edit.

import type { BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemPropertyMetadata, BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemPropertyMetadataResponse } from './batch-update-products-response-value-200-application-json-property-data-item-property-images-item-property-metadata.interface';

export interface BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem {
  path: string;
  metadata: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemPropertyMetadata;
  [key: string]: unknown;
}

export interface BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemResponse {
  path: string;
  metadata: BatchUpdateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemPropertyMetadataResponse;
  [key: string]: unknown;
}
