// This file is auto-generated by oagen. Do not edit.

import type { CreateProductRequestApplicationJsonPropertyAdditionalInformationItemPropertyDateOptions, CreateProductRequestApplicationJsonPropertyAdditionalInformationItemPropertyDateOptionsResponse } from './create-product-request-application-json-property-additional-information-item-property-date-options.interface';
import type { CreateProductRequestApplicationJsonPropertyAdditionalInformationItemType } from './create-product-request-application-json-property-additional-information-item-type.interface';

export interface CreateProductRequestApplicationJsonPropertyAdditionalInformationItem {
  type: CreateProductRequestApplicationJsonPropertyAdditionalInformationItemType | (string & Record<never, never>);
  required: boolean;
  label: string;
  key?: string;
  options?: string[];
  placeholder?: string;
  description?: string;
  variant?: string;
  dateOptions?: CreateProductRequestApplicationJsonPropertyAdditionalInformationItemPropertyDateOptions;
  [key: string]: unknown;
}

export interface CreateProductRequestApplicationJsonPropertyAdditionalInformationItemResponse {
  type: CreateProductRequestApplicationJsonPropertyAdditionalInformationItemType | (string & Record<never, never>);
  required: boolean;
  label: string;
  key?: string;
  options?: string[];
  placeholder?: string;
  description?: string;
  variant?: string;
  date_options?: CreateProductRequestApplicationJsonPropertyAdditionalInformationItemPropertyDateOptionsResponse;
  [key: string]: unknown;
}
