// This file is auto-generated by oagen. Do not edit.

import type { CreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItem, CreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItemResponse } from './create-product-response-value-201-application-json-property-data-property-images-item.interface';
import type { CreateProductResponseValue201ApplicationJsonPropertyDataPropertyAdditionalInformationItem, CreateProductResponseValue201ApplicationJsonPropertyDataPropertyAdditionalInformationItemResponse } from './create-product-response-value-201-application-json-property-data-property-additional-information-item.interface';
import type { CreateProductResponseValue201ApplicationJsonPropertyDataPropertyOtherSettings, CreateProductResponseValue201ApplicationJsonPropertyDataPropertyOtherSettingsResponse } from './create-product-response-value-201-application-json-property-data-property-other-settings.interface';
import type { CreateProductResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem, CreateProductResponseValue201ApplicationJsonPropertyDataPropertyVariantsItemResponse } from './create-product-response-value-201-application-json-property-data-property-variants-item.interface';

export interface CreateProductResponseValue201ApplicationJsonPropertyData {
  id: number;
  title: string;
  slug: string;
  description: string;
  images: CreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItem[];
  order: number | null;
  visibility: string;
  deliveryText: string | null;
  additionalInformation: CreateProductResponseValue201ApplicationJsonPropertyDataPropertyAdditionalInformationItem[];
  otherSettings: CreateProductResponseValue201ApplicationJsonPropertyDataPropertyOtherSettings;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  storeId: number;
  sectionId: number | null;
  sectionOrder: number | null;
  isDiscoverable: boolean;
  variants: CreateProductResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem[];
  url: string;
  [key: string]: unknown;
}

export interface CreateProductResponseValue201ApplicationJsonPropertyDataResponse {
  id: number;
  title: string;
  slug: string;
  description: string;
  images: CreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItemResponse[];
  order: number | null;
  visibility: string;
  delivery_text: string | null;
  additional_information: CreateProductResponseValue201ApplicationJsonPropertyDataPropertyAdditionalInformationItemResponse[];
  other_settings: CreateProductResponseValue201ApplicationJsonPropertyDataPropertyOtherSettingsResponse;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  store_id: number;
  section_id: number | null;
  section_order: number | null;
  is_discoverable: boolean;
  variants: CreateProductResponseValue201ApplicationJsonPropertyDataPropertyVariantsItemResponse[];
  url: string;
  [key: string]: unknown;
}
