// This file is auto-generated by oagen. Do not edit.

export const CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBookingConflictScope = {
  Product: 'product',
  Variant: 'variant',
} as const;

export type CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBookingConflictScope =
  | (typeof CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBookingConflictScope)[keyof typeof CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBookingConflictScope]
  | (string & Record<never, never>);
