// This file is auto-generated by oagen. Do not edit.

import type { BatchCreateProductsRequestApplicationJsonPropertyResourcesItem, BatchCreateProductsRequestApplicationJsonPropertyResourcesItemResponse } from './batch-create-products-request-application-json-property-resources-item.interface';

export interface SdkBatchCreateProductsRequestApplicationJson {
  resources: BatchCreateProductsRequestApplicationJsonPropertyResourcesItem[];
  [key: string]: unknown;
}

export interface SdkBatchCreateProductsRequestApplicationJsonResponse {
  resources: BatchCreateProductsRequestApplicationJsonPropertyResourcesItemResponse[];
  [key: string]: unknown;
}
