// This file is auto-generated by oagen. Do not edit.

import type { UpdateProductResponseValue200ApplicationJsonPropertyData, UpdateProductResponseValue200ApplicationJsonPropertyDataResponse } from './update-product-response-value-200-application-json-property-data.interface';

export interface SdkUpdateProductResponseValue200ApplicationJson {
  data: UpdateProductResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkUpdateProductResponseValue200ApplicationJsonResponse {
  data: UpdateProductResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
