// This file is auto-generated by oagen. Do not edit.

import type { UpdatePromotionRequestApplicationJsonPropertyPhasesItem, UpdatePromotionRequestApplicationJsonPropertyPhasesItemResponse } from './update-promotion-request-application-json-property-phases-item.interface';
import type { SdkUpdatePromotionRequestApplicationJsonStatus } from './sdk-update-promotion-request-application-json-status.interface';

export interface SdkUpdatePromotionRequestApplicationJson {
  name?: string;
  status?: SdkUpdatePromotionRequestApplicationJsonStatus | (string & Record<never, never>);
  startsAt?: Date | null;
  /** A date and time after starts_at and after the current time, or null for no end date. */
  endsAt?: Date | null;
  priority?: number;
  isStackable?: boolean;
  maxRedemptions?: number | null;
  /** The complete ordered phase set. Array order becomes phase position. */
  phases?: UpdatePromotionRequestApplicationJsonPropertyPhasesItem[];
  [key: string]: unknown;
}

export interface SdkUpdatePromotionRequestApplicationJsonResponse {
  name?: string;
  status?: SdkUpdatePromotionRequestApplicationJsonStatus | (string & Record<never, never>);
  starts_at?: string | null;
  ends_at?: string | null;
  priority?: number;
  is_stackable?: boolean;
  max_redemptions?: number | null;
  phases?: UpdatePromotionRequestApplicationJsonPropertyPhasesItemResponse[];
  [key: string]: unknown;
}
