// This file is auto-generated by oagen. Do not edit.

import type { SellApp } from '../sellapp';
import type { GetOptions as RequestOptions } from '../common/interfaces/get-options.interface';
import type { ReplaceOptions } from './interfaces/replace-options.interface';
import type { SdkGetWalletSettingsResponseValue200ApplicationJson, SdkGetWalletSettingsResponseValue200ApplicationJsonResponse } from './interfaces/sdk-get-wallet-settings-response-value-200-application-json.interface';
import type { SdkReplaceWalletSettingsResponseValue200ApplicationJson, SdkReplaceWalletSettingsResponseValue200ApplicationJsonResponse } from './interfaces/sdk-replace-wallet-settings-response-value-200-application-json.interface';
import type { SdkReplaceWalletSettingsRequestApplicationJsonResponse } from './interfaces/sdk-replace-wallet-settings-request-application-json.interface';
import { deserializeSdkGetWalletSettingsResponseValue200ApplicationJson } from './serializers/sdk-get-wallet-settings-response-value-200-application-json.serializer';
import { deserializeSdkReplaceWalletSettingsResponseValue200ApplicationJson } from './serializers/sdk-replace-wallet-settings-response-value-200-application-json.serializer';
import { serializeSdkReplaceWalletSettingsRequestApplicationJson } from './serializers/sdk-replace-wallet-settings-request-application-json.serializer';

interface SellAppResponseEnvelope<T> { data: T; status: number; headers: Headers; requestId?: string }
type SellAppWithResponse<T extends object> = {
  [K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never]:
    T[K] extends (...args: infer A) => Promise<infer R> ? (...args: A) => Promise<SellAppResponseEnvelope<R>> : never;
};
function createResourceWithResponse<T extends object>(resource: T, client: SellApp): SellAppWithResponse<T> {
  return new Proxy({} as SellAppWithResponse<T>, {
    get: (_target, property) => (...args: unknown[]) => client.captureResponse(
      () => (resource[property as keyof T] as (...values: unknown[]) => Promise<unknown>).apply(resource, args),
    ),
  }) as SellAppWithResponse<T>;
}

export class WalletSettings {
  constructor(private readonly sellApp: SellApp) {}
  get withResponse(): SellAppWithResponse<this> { return createResourceWithResponse(this, this.sellApp); }

  /**
   * Retrieve wallet settings
   *
   * Retrieve wallet settings for the authenticated store. Requires the `wallet` or `wallet:write` API ability. Payment methods are returned as their effective configurable values when no explicit restriction is stored. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @returns {Promise<SdkGetWalletSettingsResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async get(requestOptions: RequestOptions = {}): Promise<SdkGetWalletSettingsResponseValue200ApplicationJson> {
    const { data } = await this.sellApp.get<SdkGetWalletSettingsResponseValue200ApplicationJsonResponse>('/v2/wallet/settings', requestOptions);
    return deserializeSdkGetWalletSettingsResponseValue200ApplicationJson(data);
  }

  /**
   * Update wallet settings
   *
   * Update wallet settings. Requires the `wallet:write` API ability and the store wallet permission. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @returns {Promise<SdkReplaceWalletSettingsResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async replace(options: ReplaceOptions): Promise<SdkReplaceWalletSettingsResponseValue200ApplicationJson> {
    const { requestOptions, ...payload } = options;
    const { data } = await this.sellApp.put<SdkReplaceWalletSettingsResponseValue200ApplicationJsonResponse, SdkReplaceWalletSettingsRequestApplicationJsonResponse>(
      '/v2/wallet/settings',
      serializeSdkReplaceWalletSettingsRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'replaceWalletSettings' },
    );
    return deserializeSdkReplaceWalletSettingsResponseValue200ApplicationJson(data);
  }
}
