// This file is auto-generated by oagen. Do not edit.

export const SearchProductsWithinGroupRequestApplicationJsonPropertySortItemDirection = {
  Asc: 'asc',
  Desc: 'desc',
} as const;

export type SearchProductsWithinGroupRequestApplicationJsonPropertySortItemDirection =
  | (typeof SearchProductsWithinGroupRequestApplicationJsonPropertySortItemDirection)[keyof typeof SearchProductsWithinGroupRequestApplicationJsonPropertySortItemDirection]
  | (string & Record<never, never>);
