// This file is auto-generated by oagen. Do not edit.

import type { ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItemPropertyTargetProduct, ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItemPropertyTargetProductResponse } from './replace-upsell-offer-response-value-200-application-json-property-data-property-items-item-property-target-product.interface';
import type { ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItemPropertyTargetVariant, ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItemPropertyTargetVariantResponse } from './replace-upsell-offer-response-value-200-application-json-property-data-property-items-item-property-target-variant.interface';
import type { DiscountType } from './discount-type.interface';

export interface ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItem {
  id: number;
  targetListingId: number;
  targetVariantId: number;
  headline: string | null;
  description: string | null;
  discountType: DiscountType | (string & Record<never, never>) | null;
  /** Decimal percentage or fixed major-unit discount. Currency arithmetic is performed in integer minor units by checkout. */
  discountValue: string | null;
  /** Optional major-unit cap for percentage discounts. Must be null for fixed discounts. */
  maximumDiscountAmount: string | null;
  sortOrder: number;
  targetProduct: ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItemPropertyTargetProduct | null;
  targetVariant: ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItemPropertyTargetVariant | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  [key: string]: unknown;
}

export interface ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItemResponse {
  id: number;
  target_listing_id: number;
  target_variant_id: number;
  headline: string | null;
  description: string | null;
  discount_type: DiscountType | (string & Record<never, never>) | null;
  discount_value: string | null;
  maximum_discount_amount: string | null;
  sort_order: number;
  target_product: ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItemPropertyTargetProductResponse | null;
  target_variant: ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItemPropertyTargetVariantResponse | null;
  created_at: string | null;
  updated_at: string | null;
  [key: string]: unknown;
}
