// This file is auto-generated by oagen. Do not edit.

import type { SearchUpsellOffersRequestApplicationJsonPropertyFiltersItem, SearchUpsellOffersRequestApplicationJsonPropertyFiltersItemResponse } from './search-upsell-offers-request-application-json-property-filters-item.interface';
import type { SearchUpsellOffersRequestApplicationJsonPropertySortItem, SearchUpsellOffersRequestApplicationJsonPropertySortItemResponse } from './search-upsell-offers-request-application-json-property-sort-item.interface';
import type { SearchUpsellOffersRequestApplicationJsonPropertySearch, SearchUpsellOffersRequestApplicationJsonPropertySearchResponse } from './search-upsell-offers-request-application-json-property-search.interface';
import type { SearchUpsellOffersRequestApplicationJsonPropertyIncludesItem, SearchUpsellOffersRequestApplicationJsonPropertyIncludesItemResponse } from './search-upsell-offers-request-application-json-property-includes-item.interface';

export interface SdkSearchUpsellOffersRequestApplicationJson {
  filters?: SearchUpsellOffersRequestApplicationJsonPropertyFiltersItem[];
  sort?: SearchUpsellOffersRequestApplicationJsonPropertySortItem[];
  search?: SearchUpsellOffersRequestApplicationJsonPropertySearch;
  includes?: SearchUpsellOffersRequestApplicationJsonPropertyIncludesItem[];
  [key: string]: unknown;
}

export interface SdkSearchUpsellOffersRequestApplicationJsonResponse {
  filters?: SearchUpsellOffersRequestApplicationJsonPropertyFiltersItemResponse[];
  sort?: SearchUpsellOffersRequestApplicationJsonPropertySortItemResponse[];
  search?: SearchUpsellOffersRequestApplicationJsonPropertySearchResponse;
  includes?: SearchUpsellOffersRequestApplicationJsonPropertyIncludesItemResponse[];
  [key: string]: unknown;
}
