// This file is auto-generated by oagen. Do not edit.

export const SearchUpsellOffersRequestApplicationJsonPropertyFiltersItemType = {
  And: 'and',
  Or: 'or',
} as const;

export type SearchUpsellOffersRequestApplicationJsonPropertyFiltersItemType =
  | (typeof SearchUpsellOffersRequestApplicationJsonPropertyFiltersItemType)[keyof typeof SearchUpsellOffersRequestApplicationJsonPropertyFiltersItemType]
  | (string & Record<never, never>);
