// This file is auto-generated by oagen. Do not edit.

import type { CreateNotificationChannelRequestApplicationJsonPropertyChannel, CreateNotificationChannelRequestApplicationJsonPropertyChannelResponse } from '../interfaces/create-notification-channel-request-application-json-property-channel.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"CreateNotificationChannelRequestApplicationJsonPropertyChannel","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"CreateNotificationChannelRequestApplicationJsonPropertyChannel","required":[],"properties":{},"additionalProperties":true};

export const serializeCreateNotificationChannelRequestApplicationJsonPropertyChannel = (
  _model: CreateNotificationChannelRequestApplicationJsonPropertyChannel,
): CreateNotificationChannelRequestApplicationJsonPropertyChannelResponse => {
  assertValidModel(_model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_model, []),
  };
};
