// This file is auto-generated by oagen. Do not edit.

import type { SdkReplaceAnalyticsSettingsResponseValue200ApplicationJson, SdkReplaceAnalyticsSettingsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-replace-analytics-settings-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyData } from './replace-analytics-settings-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceAnalyticsSettingsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceAnalyticsSettingsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkReplaceAnalyticsSettingsResponseValue200ApplicationJson = (
  response: SdkReplaceAnalyticsSettingsResponseValue200ApplicationJsonResponse,
): SdkReplaceAnalyticsSettingsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
