// This file is auto-generated by oagen. Do not edit.

import type { SdkReplaceAnalyticsSettingsRequestApplicationJson, SdkReplaceAnalyticsSettingsRequestApplicationJsonResponse } from '../interfaces/sdk-replace-analytics-settings-request-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceAnalyticsSettingsRequestApplicationJson","required":[],"properties":{"ga4MeasurementId":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":64}}},"metaPixelId":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":64}}},"tiktokPixelId":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":64}}},"ga4ApiSecret":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":255}}},"metaAccessToken":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":255}}},"tiktokAccessToken":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":255}}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceAnalyticsSettingsRequestApplicationJson","required":[],"properties":{"ga_4_measurement_id":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":64}}},"meta_pixel_id":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":64}}},"tiktok_pixel_id":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":64}}},"ga_4_api_secret":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":255}}},"meta_access_token":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":255}}},"tiktok_access_token":{"kind":"nullable","inner":{"kind":"primitive","type":"string","constraints":{"maxLength":255}}}},"additionalProperties":true};

export const serializeSdkReplaceAnalyticsSettingsRequestApplicationJson = (
  model: SdkReplaceAnalyticsSettingsRequestApplicationJson,
): SdkReplaceAnalyticsSettingsRequestApplicationJsonResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["ga4MeasurementId","metaPixelId","tiktokPixelId","ga4ApiSecret","metaAccessToken","tiktokAccessToken"]),
    ga_4_measurement_id: model.ga4MeasurementId,
    meta_pixel_id: model.metaPixelId,
    tiktok_pixel_id: model.tiktokPixelId,
    ga_4_api_secret: model.ga4ApiSecret,
    meta_access_token: model.metaAccessToken,
    tiktok_access_token: model.tiktokAccessToken,
  };
};
