// This file is auto-generated by oagen. Do not edit.

import type { SdkUpdateAnalyticsSettingsResponseValue200ApplicationJson, SdkUpdateAnalyticsSettingsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-update-analytics-settings-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeUpdateAnalyticsSettingsResponseValue200ApplicationJsonPropertyData } from './update-analytics-settings-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkUpdateAnalyticsSettingsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkUpdateAnalyticsSettingsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkUpdateAnalyticsSettingsResponseValue200ApplicationJson = (
  response: SdkUpdateAnalyticsSettingsResponseValue200ApplicationJsonResponse,
): SdkUpdateAnalyticsSettingsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeUpdateAnalyticsSettingsResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
