// This file is auto-generated by oagen. Do not edit.

import type { SellApp } from '../sellapp';
import type { GetOptions as RequestOptions } from '../common/interfaces/get-options.interface';
import { AutoPaginatable } from '../common/utils/pagination';
import { fetchAndDeserialize } from '../common/utils/fetch-and-deserialize';
import type { AddOptions } from './interfaces/add-options.interface';
import type { RemoveOptions } from './interfaces/remove-options.interface';
import type { GroupsProductsListOptions } from './interfaces/groups-products-list-options.interface';
import type { ReplaceOptions } from './interfaces/replace-options.interface';
import type { GetOptions } from './interfaces/get-options.interface';
import type { SearchOptions } from './interfaces/search-options.interface';
import type { SdkAddProductsToGroupResponseValue200ApplicationJson, SdkAddProductsToGroupResponseValue200ApplicationJsonResponse } from '../groups/interfaces/sdk-add-products-to-group-response-value-200-application-json.interface';
import type { ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem, ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemResponse } from '../groups/interfaces/list-products-within-group-response-value-200-application-json-property-data-item.interface';
import type { SdkSyncGroupProductsResponseValue200ApplicationJson, SdkSyncGroupProductsResponseValue200ApplicationJsonResponse } from '../groups/interfaces/sdk-sync-group-products-response-value-200-application-json.interface';
import type { SdkGetProductWithinGroupResponseValue200ApplicationJson, SdkGetProductWithinGroupResponseValue200ApplicationJsonResponse } from '../groups/interfaces/sdk-get-product-within-group-response-value-200-application-json.interface';
import type { SearchProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem, SearchProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemResponse } from '../groups/interfaces/search-products-within-group-response-value-200-application-json-property-data-item.interface';
import type { SdkAddProductsToGroupRequestApplicationJsonResponse } from '../groups/interfaces/sdk-add-products-to-group-request-application-json.interface';
import type { SdkRemoveProductsFromGroupRequestApplicationJsonResponse } from '../groups/interfaces/sdk-remove-products-from-group-request-application-json.interface';
import type { SdkSyncGroupProductsRequestApplicationJsonResponse } from '../groups/interfaces/sdk-sync-group-products-request-application-json.interface';
import type { SdkSearchProductsWithinGroupRequestApplicationJsonResponse } from '../groups/interfaces/sdk-search-products-within-group-request-application-json.interface';
import { deserializeSdkAddProductsToGroupResponseValue200ApplicationJson } from '../groups/serializers/sdk-add-products-to-group-response-value-200-application-json.serializer';
import { deserializeListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem } from '../groups/serializers/list-products-within-group-response-value-200-application-json-property-data-item.serializer';
import { deserializeSdkSyncGroupProductsResponseValue200ApplicationJson } from '../groups/serializers/sdk-sync-group-products-response-value-200-application-json.serializer';
import { deserializeSdkGetProductWithinGroupResponseValue200ApplicationJson } from '../groups/serializers/sdk-get-product-within-group-response-value-200-application-json.serializer';
import { deserializeSearchProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem } from '../groups/serializers/search-products-within-group-response-value-200-application-json-property-data-item.serializer';
import { serializeSdkAddProductsToGroupRequestApplicationJson } from '../groups/serializers/sdk-add-products-to-group-request-application-json.serializer';
import { serializeSdkRemoveProductsFromGroupRequestApplicationJson } from '../groups/serializers/sdk-remove-products-from-group-request-application-json.serializer';
import { serializeSdkSyncGroupProductsRequestApplicationJson } from '../groups/serializers/sdk-sync-group-products-request-application-json.serializer';
import { serializeSdkSearchProductsWithinGroupRequestApplicationJson } from '../groups/serializers/sdk-search-products-within-group-request-application-json.serializer';

interface SellAppResponseEnvelope<T> { data: T; status: number; headers: Headers; requestId?: string }
type SellAppWithResponse<T extends object> = {
  [K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never]:
    T[K] extends (...args: infer A) => Promise<infer R> ? (...args: A) => Promise<SellAppResponseEnvelope<R>> : never;
};
function createResourceWithResponse<T extends object>(resource: T, client: SellApp): SellAppWithResponse<T> {
  return new Proxy({} as SellAppWithResponse<T>, {
    get: (_target, property) => (...args: unknown[]) => client.captureResponse(
      () => (resource[property as keyof T] as (...values: unknown[]) => Promise<unknown>).apply(resource, args),
    ),
  }) as SellAppWithResponse<T>;
}

export class GroupsProducts {
  constructor(private readonly sellApp: SellApp) {}
  get withResponse(): SellAppWithResponse<this> { return createResourceWithResponse(this, this.sellApp); }

  /**
   * Add products to group
   *
   * Add existing products to a group. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.group - The group path parameter.
   * @returns {Promise<SdkAddProductsToGroupResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async add(options: AddOptions): Promise<SdkAddProductsToGroupResponseValue200ApplicationJson> {
    const { group, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.post<SdkAddProductsToGroupResponseValue200ApplicationJsonResponse, SdkAddProductsToGroupRequestApplicationJsonResponse>(
      `/v2/groups/${encodeURIComponent(group)}/products/attach`,
      serializeSdkAddProductsToGroupRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'addProductsToGroup' },
    );
    return deserializeSdkAddProductsToGroupResponseValue200ApplicationJson(data);
  }

  /**
   * Remove products from group
   *
   * Remove products from a group without deleting the products. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.group - The group path parameter.
   * @returns {Promise<void>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async remove(options: RemoveOptions): Promise<void> {
    const { group, requestOptions, ...payload } = options;
    await this.sellApp.deleteWithBody<SdkRemoveProductsFromGroupRequestApplicationJsonResponse>(`/v2/groups/${encodeURIComponent(group)}/products/detach`, serializeSdkRemoveProductsFromGroupRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'removeProductsFromGroup' });
  }

  /**
   * List all products within group
   *
   * List the products in a group, 15 per page by default. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Pagination and filter options.
   * @param options.group - The group path parameter.
   * @example 1
   * @returns {Promise<AutoPaginatable<ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem>>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async list(options: GroupsProductsListOptions): Promise<AutoPaginatable<ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem, Omit<GroupsProductsListOptions, 'group'>>> {
    const { group, ...paginationOptions } = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemResponse, ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem>(
        this.sellApp,
        `/v2/groups/${encodeURIComponent(group)}/products`,
        deserializeListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemResponse, ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem>(
          this.sellApp,
          `/v2/groups/${encodeURIComponent(group)}/products`,
          deserializeListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * Replace ordered group products
   *
   * Replace a group's complete product membership in one transaction. Requires the group API-key ability and store group permission. The order of product_ids becomes display order. An empty array clears the group. Missing or draft products return 422; products from another store are rejected. Retrying the same list has the same result. Private products remain assigned but are omitted from the returned group summary. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @example 42
   * @returns {Promise<SdkSyncGroupProductsResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async replace(options: ReplaceOptions): Promise<SdkSyncGroupProductsResponseValue200ApplicationJson> {
    const { group, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.put<SdkSyncGroupProductsResponseValue200ApplicationJsonResponse, SdkSyncGroupProductsRequestApplicationJsonResponse>(
      `/v2/groups/${encodeURIComponent(group)}/products`,
      serializeSdkSyncGroupProductsRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'syncGroupProducts' },
    );
    return deserializeSdkSyncGroupProductsResponseValue200ApplicationJson(data);
  }

  /**
   * List specific product within group
   *
   * Retrieve one product from a group. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.group - The group path parameter.
   * @example 1
   * @param options.product - The product path parameter.
   * @example 1
   * @returns {Promise<SdkGetProductWithinGroupResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async get(options: GetOptions): Promise<SdkGetProductWithinGroupResponseValue200ApplicationJson> {
    const { group, product } = options;
    const { data } = await this.sellApp.get<SdkGetProductWithinGroupResponseValue200ApplicationJsonResponse>(`/v2/groups/${encodeURIComponent(group)}/products/${encodeURIComponent(product)}`, { ...options.requestOptions, operationId: 'getProductWithinGroup' });
    return deserializeSdkGetProductWithinGroupResponseValue200ApplicationJson(data);
  }

  /**
   * Search products within group
   *
   * Search the products in a group using JSON body filters, search terms, includes, and sort instructions. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - Pagination and filter options.
   * @param options.group - The group path parameter.
   * @example 1
   * @returns {Promise<AutoPaginatable<SearchProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem>>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async search(options: SearchOptions): Promise<SdkSearchProductsWithinGroupResponseValue200ApplicationJson> {
    const { group, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.post<SdkSearchProductsWithinGroupResponseValue200ApplicationJsonResponse, SdkSearchProductsWithinGroupRequestApplicationJsonResponse>(
      `/v2/groups/${encodeURIComponent(group)}/products/search`,
      serializeSdkSearchProductsWithinGroupRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'searchProductsWithinGroup' },
    );
    return deserializeSdkSearchProductsWithinGroupResponseValue200ApplicationJson(data);
  }
}
