// This file is auto-generated by oagen. Do not edit.

import type { ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataPropertyOwnershipVerification, ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataPropertyOwnershipVerificationResponse } from './connect-custom-domain-response-value-201-application-json-property-data-property-ownership-verification.interface';
import type { ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataPropertySslValidationRecordsItem, ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataPropertySslValidationRecordsItemResponse } from './connect-custom-domain-response-value-201-application-json-property-data-property-ssl-validation-records-item.interface';
import type { ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataStatus } from './connect-custom-domain-response-value-201-application-json-property-data-status.interface';

export interface ConnectCustomDomainResponseValue201ApplicationJsonPropertyData {
  id: number;
  domain: string;
  status: ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataStatus | (string & Record<never, never>);
  hostnameStatus?: string | null;
  sslStatus?: string | null;
  ownershipVerification?: ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataPropertyOwnershipVerification;
  sslValidationRecords?: ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataPropertySslValidationRecordsItem[] | null;
  /**
   * DNS CNAME destination configured for this API environment. Use the value returned here; the default is sell-beacon.net.
   * @readonly
   */
  readonly cnameTarget: string;
  lastCheckedAt?: Date | null;
  verifiedAt?: Date | null;
  [key: string]: unknown;
}

export interface ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataResponse {
  id: number;
  domain: string;
  status: ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataStatus | (string & Record<never, never>);
  hostname_status?: string | null;
  ssl_status?: string | null;
  ownership_verification?: ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataPropertyOwnershipVerificationResponse;
  ssl_validation_records?: ConnectCustomDomainResponseValue201ApplicationJsonPropertyDataPropertySslValidationRecordsItemResponse[] | null;
  cname_target: string;
  last_checked_at?: string | null;
  verified_at?: string | null;
  [key: string]: unknown;
}
