// This file is auto-generated by oagen. Do not edit.

import type { GetOptions as RequestOptions } from '../../common/interfaces/get-options.interface';

export interface ReplaceAnalyticsOptions {
  /** Per-call timeout, retry, headers, cancellation, and lifecycle metadata. */
  requestOptions?: RequestOptions;
  ga4MeasurementId?: string | null;
  metaPixelId?: string | null;
  tiktokPixelId?: string | null;
  ga4ApiSecret?: string | null;
  metaAccessToken?: string | null;
  tiktokAccessToken?: string | null;
}
