// This file is auto-generated by oagen. Do not edit.

import type { UpdateGeneralStoreSettingsResponseValue200ApplicationJsonPropertyData, UpdateGeneralStoreSettingsResponseValue200ApplicationJsonPropertyDataResponse } from './update-general-store-settings-response-value-200-application-json-property-data.interface';

export interface SdkUpdateGeneralStoreSettingsResponseValue200ApplicationJson {
  data: UpdateGeneralStoreSettingsResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkUpdateGeneralStoreSettingsResponseValue200ApplicationJsonResponse {
  data: UpdateGeneralStoreSettingsResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
