// This file is auto-generated by oagen. Do not edit.

import type { ReplaceGeneralStoreSettingsResponseValue200ApplicationJsonPropertyData, ReplaceGeneralStoreSettingsResponseValue200ApplicationJsonPropertyDataResponse } from './replace-general-store-settings-response-value-200-application-json-property-data.interface';

export interface SdkReplaceGeneralStoreSettingsResponseValue200ApplicationJson {
  data: ReplaceGeneralStoreSettingsResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkReplaceGeneralStoreSettingsResponseValue200ApplicationJsonResponse {
  data: ReplaceGeneralStoreSettingsResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
