// This file is auto-generated by oagen. Do not edit.

import type { UpdateMarketingSettingsResponseValue200ApplicationJsonPropertyData, UpdateMarketingSettingsResponseValue200ApplicationJsonPropertyDataResponse } from './update-marketing-settings-response-value-200-application-json-property-data.interface';

export interface SdkUpdateMarketingSettingsResponseValue200ApplicationJson {
  data: UpdateMarketingSettingsResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkUpdateMarketingSettingsResponseValue200ApplicationJsonResponse {
  data: UpdateMarketingSettingsResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
