// This file is auto-generated by oagen. Do not edit.

import type { GetNotificationChannelResponseValue200ApplicationJsonPropertyData, GetNotificationChannelResponseValue200ApplicationJsonPropertyDataResponse } from './get-notification-channel-response-value-200-application-json-property-data.interface';

export interface SdkGetNotificationChannelResponseValue200ApplicationJson {
  data: GetNotificationChannelResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkGetNotificationChannelResponseValue200ApplicationJsonResponse {
  data: GetNotificationChannelResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
