// This file is auto-generated by oagen. Do not edit.

import type { BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem, BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItemResponse } from './batch-create-sections-response-value-200-application-json-property-data-item-property-groups-item.interface';
import type { BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItem, BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItemResponse } from './batch-create-sections-response-value-200-application-json-property-data-item-property-products-item.interface';

export interface BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItem {
  id: number;
  title: string;
  slug: string | null;
  hidden: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
  storeId: number;
  groupsLinked: number;
  productsLinked: number;
  groups: BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem[];
  products: BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItem[];
  [key: string]: unknown;
}

export interface BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemResponse {
  id: number;
  title: string;
  slug: string | null;
  hidden: boolean;
  order: number;
  created_at: string;
  updated_at: string;
  store_id: number;
  groups_linked: number;
  products_linked: number;
  groups: BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItemResponse[];
  products: BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItemResponse[];
  [key: string]: unknown;
}
