// This file is auto-generated by oagen. Do not edit.

import type { ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataPropertyGroupsItem, ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataPropertyGroupsItemResponse } from './replace-section-groups-response-value-200-application-json-property-data-property-groups-item.interface';
import type { ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataPropertyProductsItem, ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataPropertyProductsItemResponse } from './replace-section-groups-response-value-200-application-json-property-data-property-products-item.interface';

export interface ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyData {
  id: number;
  title: string;
  slug: string | null;
  hidden: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
  storeId: number;
  groupsLinked: number;
  productsLinked: number;
  groups: ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataPropertyGroupsItem[];
  products: ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataPropertyProductsItem[];
  [key: string]: unknown;
}

export interface ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataResponse {
  id: number;
  title: string;
  slug: string | null;
  hidden: boolean;
  order: number;
  created_at: string;
  updated_at: string;
  store_id: number;
  groups_linked: number;
  products_linked: number;
  groups: ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataPropertyGroupsItemResponse[];
  products: ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataPropertyProductsItemResponse[];
  [key: string]: unknown;
}
