// This file is auto-generated by oagen. Do not edit.

import type { SearchTicketMessagesRequestApplicationJsonPropertyFiltersItem, SearchTicketMessagesRequestApplicationJsonPropertyFiltersItemResponse } from './search-ticket-messages-request-application-json-property-filters-item.interface';
import type { SearchTicketMessagesRequestApplicationJsonPropertySortItem, SearchTicketMessagesRequestApplicationJsonPropertySortItemResponse } from './search-ticket-messages-request-application-json-property-sort-item.interface';
import type { SearchTicketMessagesRequestApplicationJsonPropertySearch, SearchTicketMessagesRequestApplicationJsonPropertySearchResponse } from './search-ticket-messages-request-application-json-property-search.interface';
import type { SearchTicketMessagesRequestApplicationJsonPropertyIncludesItem, SearchTicketMessagesRequestApplicationJsonPropertyIncludesItemResponse } from './search-ticket-messages-request-application-json-property-includes-item.interface';

export interface SdkSearchTicketMessagesRequestApplicationJson {
  filters?: SearchTicketMessagesRequestApplicationJsonPropertyFiltersItem[];
  sort?: SearchTicketMessagesRequestApplicationJsonPropertySortItem[];
  search?: SearchTicketMessagesRequestApplicationJsonPropertySearch;
  includes?: SearchTicketMessagesRequestApplicationJsonPropertyIncludesItem[];
  [key: string]: unknown;
}

export interface SdkSearchTicketMessagesRequestApplicationJsonResponse {
  filters?: SearchTicketMessagesRequestApplicationJsonPropertyFiltersItemResponse[];
  sort?: SearchTicketMessagesRequestApplicationJsonPropertySortItemResponse[];
  search?: SearchTicketMessagesRequestApplicationJsonPropertySearchResponse;
  includes?: SearchTicketMessagesRequestApplicationJsonPropertyIncludesItemResponse[];
  [key: string]: unknown;
}
