// This file is auto-generated by oagen. Do not edit.

import type { V2ReplaceFeedbackResponseValue200ApplicationJsonPropertyData, V2ReplaceFeedbackResponseValue200ApplicationJsonPropertyDataResponse } from './v-2-replace-feedback-response-value-200-application-json-property-data.interface';

export interface SdkV2ReplaceFeedbackResponseValue200ApplicationJson {
  data: V2ReplaceFeedbackResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkV2ReplaceFeedbackResponseValue200ApplicationJsonResponse {
  data: V2ReplaceFeedbackResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
