// This file is auto-generated by oagen. Do not edit.

import type { SdkV2ReplaceCouponRequestApplicationJsonType } from './sdk-v-2-replace-coupon-request-application-json-type.interface';

export interface SdkV2ReplaceCouponRequestApplicationJson {
  code?: string;
  type?: SdkV2ReplaceCouponRequestApplicationJsonType | (string & Record<never, never>);
  /** A decimal discount value of at least 1. Percentage discounts cannot exceed 100; amount discounts use the store currency's major unit. */
  discount?: number | string;
  storeWide?: boolean;
  /** Product IDs the coupon applies to when store_wide is false. */
  products?: number[];
  /** Optional variant restrictions. Omit to preserve existing restrictions or send an empty array to allow every variant of the selected products. */
  productVariants?: number[];
  limit?: number | null;
  /** A future date and time, or null for no expiry. */
  expiresAt?: Date | null;
  /** A decimal minimum order amount in the store currency's major unit, or null for no minimum. */
  minimumAmount?: number | string | null;
  [key: string]: unknown;
}

export interface SdkV2ReplaceCouponRequestApplicationJsonResponse {
  code?: string;
  type?: SdkV2ReplaceCouponRequestApplicationJsonType | (string & Record<never, never>);
  discount?: number | string;
  store_wide?: boolean;
  products?: number[];
  product_variants?: number[];
  limit?: number | null;
  expires_at?: string | null;
  minimum_amount?: number | string | null;
  [key: string]: unknown;
}
