// This file is auto-generated by oagen. Do not edit.

import type { ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyData, ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataResponse } from './replace-section-groups-response-value-200-application-json-property-data.interface';

export interface SdkReplaceSectionGroupsResponseValue200ApplicationJson {
  data: ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkReplaceSectionGroupsResponseValue200ApplicationJsonResponse {
  data: ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
