// This file is auto-generated by oagen. Do not edit.

import type { V2CreateSectionResponseValue201ApplicationJsonPropertyData, V2CreateSectionResponseValue201ApplicationJsonPropertyDataResponse } from './v-2-create-section-response-value-201-application-json-property-data.interface';

export interface SdkV2CreateSectionResponseValue201ApplicationJson {
  data: V2CreateSectionResponseValue201ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkV2CreateSectionResponseValue201ApplicationJsonResponse {
  data: V2CreateSectionResponseValue201ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
