// This file is auto-generated by oagen. Do not edit.

export interface SdkReplyToFeedbackRequestApplicationJson {
  reply: string;
  [key: string]: unknown;
}

export interface SdkReplyToFeedbackRequestApplicationJsonResponse {
  reply: string;
  [key: string]: unknown;
}
