// This file is auto-generated by oagen. Do not edit.

import type { BatchUpdateSectionsRequestApplicationJsonPropertyResources, BatchUpdateSectionsRequestApplicationJsonPropertyResourcesResponse } from './batch-update-sections-request-application-json-property-resources.interface';

export interface SdkBatchUpdateSectionsRequestApplicationJson {
  resources: BatchUpdateSectionsRequestApplicationJsonPropertyResources;
  [key: string]: unknown;
}

export interface SdkBatchUpdateSectionsRequestApplicationJsonResponse {
  resources: BatchUpdateSectionsRequestApplicationJsonPropertyResourcesResponse;
  [key: string]: unknown;
}
