// This file is auto-generated by oagen. Do not edit.

import type { V2SearchSectionsRequestApplicationJsonPropertyFiltersItem, V2SearchSectionsRequestApplicationJsonPropertyFiltersItemResponse } from './v-2-search-sections-request-application-json-property-filters-item.interface';
import type { V2SearchSectionsRequestApplicationJsonPropertySortItem, V2SearchSectionsRequestApplicationJsonPropertySortItemResponse } from './v-2-search-sections-request-application-json-property-sort-item.interface';
import type { V2SearchSectionsRequestApplicationJsonPropertySearch, V2SearchSectionsRequestApplicationJsonPropertySearchResponse } from './v-2-search-sections-request-application-json-property-search.interface';
import type { V2SearchSectionsRequestApplicationJsonPropertyIncludesItem, V2SearchSectionsRequestApplicationJsonPropertyIncludesItemResponse } from './v-2-search-sections-request-application-json-property-includes-item.interface';

export interface SdkV2SearchSectionsRequestApplicationJson {
  filters?: V2SearchSectionsRequestApplicationJsonPropertyFiltersItem[];
  sort?: V2SearchSectionsRequestApplicationJsonPropertySortItem[];
  search?: V2SearchSectionsRequestApplicationJsonPropertySearch;
  includes?: V2SearchSectionsRequestApplicationJsonPropertyIncludesItem[];
  [key: string]: unknown;
}

export interface SdkV2SearchSectionsRequestApplicationJsonResponse {
  filters?: V2SearchSectionsRequestApplicationJsonPropertyFiltersItemResponse[];
  sort?: V2SearchSectionsRequestApplicationJsonPropertySortItemResponse[];
  search?: V2SearchSectionsRequestApplicationJsonPropertySearchResponse;
  includes?: V2SearchSectionsRequestApplicationJsonPropertyIncludesItemResponse[];
  [key: string]: unknown;
}
