// This file is auto-generated by oagen. Do not edit.

import type { SearchTicketsRequestApplicationJsonPropertySortItemDirection } from './search-tickets-request-application-json-property-sort-item-direction.interface';

export interface SearchTicketsRequestApplicationJsonPropertySortItem {
  field: string;
  /** @default "asc" */
  direction?: SearchTicketsRequestApplicationJsonPropertySortItemDirection | (string & Record<never, never>);
  [key: string]: unknown;
}

export interface SearchTicketsRequestApplicationJsonPropertySortItemResponse {
  field: string;
  direction?: SearchTicketsRequestApplicationJsonPropertySortItemDirection | (string & Record<never, never>);
  [key: string]: unknown;
}
