// This file is auto-generated by oagen. Do not edit.

import type { SearchGroupsRequestApplicationJsonPropertySearch, SearchGroupsRequestApplicationJsonPropertySearchResponse } from '../../groups/interfaces/search-groups-request-application-json-property-search.interface';

export type SearchTicketsRequestApplicationJsonPropertySearch = SearchGroupsRequestApplicationJsonPropertySearch;
export type SearchTicketsRequestApplicationJsonPropertySearchResponse = SearchGroupsRequestApplicationJsonPropertySearchResponse;
