// This file is auto-generated by oagen. Do not edit.

import type { SearchGroupsRequestApplicationJsonPropertyIncludesItem, SearchGroupsRequestApplicationJsonPropertyIncludesItemResponse } from '../../groups/interfaces/search-groups-request-application-json-property-includes-item.interface';

export type V2SearchTicketsRequestApplicationJsonPropertyIncludesItem = SearchGroupsRequestApplicationJsonPropertyIncludesItem;
export type V2SearchTicketsRequestApplicationJsonPropertyIncludesItemResponse = SearchGroupsRequestApplicationJsonPropertyIncludesItemResponse;
