// This file is auto-generated by oagen. Do not edit.

import type { V2UpdateSectionResponseValue200ApplicationJsonPropertyDataPropertyGroupsItem, V2UpdateSectionResponseValue200ApplicationJsonPropertyDataPropertyGroupsItemResponse } from './v-2-update-section-response-value-200-application-json-property-data-property-groups-item.interface';
import type { V2UpdateSectionResponseValue200ApplicationJsonPropertyDataPropertyProductsItem, V2UpdateSectionResponseValue200ApplicationJsonPropertyDataPropertyProductsItemResponse } from './v-2-update-section-response-value-200-application-json-property-data-property-products-item.interface';

export interface V2UpdateSectionResponseValue200ApplicationJsonPropertyData {
  id: number;
  title: string;
  slug: string | null;
  hidden: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
  storeId: number;
  groupsLinked: number;
  productsLinked: number;
  groups: V2UpdateSectionResponseValue200ApplicationJsonPropertyDataPropertyGroupsItem[];
  products: V2UpdateSectionResponseValue200ApplicationJsonPropertyDataPropertyProductsItem[];
  [key: string]: unknown;
}

export interface V2UpdateSectionResponseValue200ApplicationJsonPropertyDataResponse {
  id: number;
  title: string;
  slug: string | null;
  hidden: boolean;
  order: number;
  created_at: string;
  updated_at: string;
  store_id: number;
  groups_linked: number;
  products_linked: number;
  groups: V2UpdateSectionResponseValue200ApplicationJsonPropertyDataPropertyGroupsItemResponse[];
  products: V2UpdateSectionResponseValue200ApplicationJsonPropertyDataPropertyProductsItemResponse[];
  [key: string]: unknown;
}
