// This file is auto-generated by oagen. Do not edit.

export const V2ListCouponsResponseValue200ApplicationJsonPropertyDataItemType = {
  Percentage: 'PERCENTAGE',
  Amount: 'AMOUNT',
} as const;

export type V2ListCouponsResponseValue200ApplicationJsonPropertyDataItemType =
  | (typeof V2ListCouponsResponseValue200ApplicationJsonPropertyDataItemType)[keyof typeof V2ListCouponsResponseValue200ApplicationJsonPropertyDataItemType]
  | (string & Record<never, never>);
