// This file is auto-generated by oagen. Do not edit.

export const V2SearchSectionsRequestApplicationJsonPropertySortItemDirection = {
  Asc: 'asc',
  Desc: 'desc',
} as const;

export type V2SearchSectionsRequestApplicationJsonPropertySortItemDirection =
  | (typeof V2SearchSectionsRequestApplicationJsonPropertySortItemDirection)[keyof typeof V2SearchSectionsRequestApplicationJsonPropertySortItemDirection]
  | (string & Record<never, never>);
