// This file is auto-generated by oagen. Do not edit.

import type { V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomer, V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerResponse } from './v-2-search-tickets-response-value-200-application-json-property-data-item-property-customer.interface';
import type { V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReference, V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReferenceResponse } from './v-2-search-tickets-response-value-200-application-json-property-data-item-property-reference.interface';
import type { V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReadStatus, V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReadStatusResponse } from './v-2-search-tickets-response-value-200-application-json-property-data-item-property-read-status.interface';

export interface V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItem {
  id: number;
  title: string;
  status: string;
  customer: V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomer;
  reference: V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReference;
  createdAt: Date | null;
  updatedAt: Date | null;
  storeId: number;
  archived: number;
  readStatus: V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReadStatus;
  orderId: number | null;
  reason: string | null;
  messageCount: number;
  [key: string]: unknown;
}

export interface V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemResponse {
  id: number;
  title: string;
  status: string;
  customer: V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerResponse;
  reference: V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReferenceResponse;
  created_at: string | null;
  updated_at: string | null;
  store_id: number;
  archived: number;
  read_status: V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReadStatusResponse;
  order_id: number | null;
  reason: string | null;
  message_count: number;
  [key: string]: unknown;
}
