// This file is auto-generated by oagen. Do not edit.

export const V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType = {
  And: 'and',
  Or: 'or',
} as const;

export type V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType =
  | (typeof V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType)[keyof typeof V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType]
  | (string & Record<never, never>);
