// This file is auto-generated by oagen. Do not edit.

import type { StorePermissions, StorePermissionsResponse } from '../interfaces/store-permissions.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"StorePermissions","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"StorePermissions","required":[],"properties":{},"additionalProperties":true};

export const deserializeStorePermissions = (
  _response: StorePermissionsResponse,
): StorePermissions => {
  assertValidModel(_response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_response, []),
  };
};
