// This file is auto-generated by oagen. Do not edit.

import type { PaginationOptions } from '../../common/interfaces/pagination-options.interface';

export interface ListOrderEventsOptions extends PaginationOptions {
  /** The order identifier. */
  order: number;
  /** Signed cursor bound to this filter set. */
  cursor?: string;
}
