// This file is auto-generated by oagen. Do not edit.

import type { ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemPropertySubject, ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemPropertySubjectResponse } from './list-order-events-response-value-200-application-json-property-data-item-property-subject.interface';
import type { ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemPropertyData, ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemPropertyDataResponse } from './list-order-events-response-value-200-application-json-property-data-item-property-data.interface';

export interface ListOrderEventsResponseValue200ApplicationJsonPropertyDataItem {
  id: string;
  type: string;
  version: number;
  storeId: string;
  occurredAt: Date;
  subject: ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemPropertySubject;
  data: ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemPropertyData;
  [key: string]: unknown;
}

export interface ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemResponse {
  id: string;
  type: string;
  version: number;
  store_id: string;
  occurred_at: string;
  subject: ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemPropertySubjectResponse;
  data: ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemPropertyDataResponse;
  [key: string]: unknown;
}
