// This file is auto-generated by oagen. Do not edit.

import type { GetOptions as RequestOptions } from '../../common/interfaces/get-options.interface';
import type { SdkUpdateBookingConfigurationRequestApplicationJsonConflictScope } from '../../bookings/interfaces/sdk-update-booking-configuration-request-application-json-conflict-scope.interface';
import type { SdkUpdateBookingConfigurationRequestApplicationJsonVideoProvider } from '../../bookings/interfaces/sdk-update-booking-configuration-request-application-json-video-provider.interface';
import type { SdkUpdateBookingConfigurationRequestApplicationJsonReminderOffsetUnit } from '../../bookings/interfaces/sdk-update-booking-configuration-request-application-json-reminder-offset-unit.interface';
import type { UpdateBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem } from '../../bookings/interfaces/update-booking-configuration-request-application-json-property-availability-item.interface';
import type { UpdateBookingConfigurationRequestApplicationJsonPropertyMeta } from '../../bookings/interfaces/update-booking-configuration-request-application-json-property-meta.interface';

export interface UpdateOptions {
  /** Per-call timeout, retry, headers, cancellation, and lifecycle metadata. */
  requestOptions?: RequestOptions;
  /** The booking product ID or slug. */
  product: string;
  /** The variant path parameter. */
  variant: number;
  mode?: 'native';
  conflictScope?: SdkUpdateBookingConfigurationRequestApplicationJsonConflictScope | (string & Record<never, never>);
  timezone?: string;
  durationMinutes?: number;
  capacityPerSlot?: number;
  minNoticeMinutes?: number;
  maxAdvanceDays?: number;
  bufferBeforeMinutes?: number;
  bufferAfterMinutes?: number;
  availability?: UpdateBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem[];
  providerConnectionIds?: number[];
  videoProvider?: SdkUpdateBookingConfigurationRequestApplicationJsonVideoProvider | (string & Record<never, never>);
  videoProviderConnectionId?: number | null;
  remindersEnabled?: boolean;
  reminderOffsetValue?: number;
  reminderOffsetUnit?: SdkUpdateBookingConfigurationRequestApplicationJsonReminderOffsetUnit | (string & Record<never, never>);
  meta?: UpdateBookingConfigurationRequestApplicationJsonPropertyMeta;
}
