// This file is auto-generated by oagen. Do not edit.

export type GetRewardGrantResponseValue200ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayload = Record<string, unknown>;

export type GetRewardGrantResponseValue200ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayloadResponse = Record<string, unknown>;
