// This file is auto-generated by oagen. Do not edit.

export interface IssueEligibleRewardGrantResponseValue200ApplicationJsonPropertyDataPropertyCustomer {
  id?: number;
  email?: string;
  [key: string]: unknown;
}

export interface IssueEligibleRewardGrantResponseValue200ApplicationJsonPropertyDataPropertyCustomerResponse {
  id?: number;
  email?: string;
  [key: string]: unknown;
}
