// This file is auto-generated by oagen. Do not edit.

import type { CreateCustomerResponseValue201ApplicationJsonPropertyDataPropertyWalletStatus } from './create-customer-response-value-201-application-json-property-data-property-wallet-status.interface';

export interface CreateCustomerResponseValue201ApplicationJsonPropertyDataPropertyWallet {
  status: CreateCustomerResponseValue201ApplicationJsonPropertyDataPropertyWalletStatus | (string & Record<never, never>);
  /** Current wallet balance in integer USD minor units. */
  balanceCents: number;
  [key: string]: unknown;
}

export interface CreateCustomerResponseValue201ApplicationJsonPropertyDataPropertyWalletResponse {
  status: CreateCustomerResponseValue201ApplicationJsonPropertyDataPropertyWalletStatus | (string & Record<never, never>);
  balance_cents: number;
  [key: string]: unknown;
}
