// This file is auto-generated by oagen. Do not edit.

export type SdkListCustomersResponseValue200ApplicationJson = Record<string, unknown>;

export type SdkListCustomersResponseValue200ApplicationJsonResponse = Record<string, unknown>;
