// This file is auto-generated by oagen. Do not edit.


export type UpdateCustomerResponseValue200ApplicationJsonPropertyDataPropertyMetadata = Record<string, unknown>;

export type UpdateCustomerResponseValue200ApplicationJsonPropertyDataPropertyMetadataResponse = Record<string, unknown>;
