// This file is auto-generated by oagen. Do not edit.

import type { DeactivateLicenseResponseValue200ApplicationJsonPropertyData, DeactivateLicenseResponseValue200ApplicationJsonPropertyDataResponse } from './deactivate-license-response-value-200-application-json-property-data.interface';

export interface SdkDeactivateLicenseResponseValue200ApplicationJson {
  data: DeactivateLicenseResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkDeactivateLicenseResponseValue200ApplicationJsonResponse {
  data: DeactivateLicenseResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
