// This file is auto-generated by oagen. Do not edit.

import type { SdkReplaceWalletBonusTierRequestApplicationJsonBonusKind } from './sdk-replace-wallet-bonus-tier-request-application-json-bonus-kind.interface';

export interface SdkReplaceWalletBonusTierRequestApplicationJson {
  minimumTopUpCents: number;
  bonusKind: SdkReplaceWalletBonusTierRequestApplicationJsonBonusKind | (string & Record<never, never>);
  fixedBonusCents: number | null;
  percentBasis: number | null;
  maximumBonusCents: number | null;
  priority: number;
  isActive: boolean;
  [key: string]: unknown;
}

export interface SdkReplaceWalletBonusTierRequestApplicationJsonResponse {
  minimum_top_up_cents: number;
  bonus_kind: SdkReplaceWalletBonusTierRequestApplicationJsonBonusKind | (string & Record<never, never>);
  fixed_bonus_cents: number | null;
  percent_basis: number | null;
  maximum_bonus_cents: number | null;
  priority: number;
  is_active: boolean;
  [key: string]: unknown;
}
