// This file is auto-generated by oagen. Do not edit.

import type { SdkUpdateRewardCouponTemplateResponseValue200ApplicationJson, SdkUpdateRewardCouponTemplateResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-update-reward-coupon-template-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeUpdateRewardCouponTemplateResponseValue200ApplicationJsonPropertyData } from './update-reward-coupon-template-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkUpdateRewardCouponTemplateResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkUpdateRewardCouponTemplateResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkUpdateRewardCouponTemplateResponseValue200ApplicationJson = (
  response: SdkUpdateRewardCouponTemplateResponseValue200ApplicationJsonResponse,
): SdkUpdateRewardCouponTemplateResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeUpdateRewardCouponTemplateResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
