// This file is auto-generated by oagen. Do not edit.

import type { PaginationOptions } from '../../common/interfaces/pagination-options.interface';
import type { AffiliateReferralsStatus } from './affiliate-referrals-status.interface';

export interface AffiliateReferralsListOptions extends PaginationOptions {
  /** Filter by store affiliate ID. */
  affiliateId?: number;
  /** Filter by attributed Order ID. */
  orderId?: number;
  /** Filter by referral status. */
  status?: AffiliateReferralsStatus | (string & Record<never, never>);
  /** Page number to return. */
  page?: number;
}
