// This file is auto-generated by oagen. Do not edit.

export const ListAffiliateReferralsResponseValue200ApplicationJsonPropertyDataItemStatus = {
  Created: 'created',
  Accepted: 'accepted',
  InReview: 'in_review',
  Pending: 'pending',
  Paid: 'paid',
  Rejected: 'rejected',
  Void: 'void',
  Expired: 'expired',
} as const;

export type ListAffiliateReferralsResponseValue200ApplicationJsonPropertyDataItemStatus =
  | (typeof ListAffiliateReferralsResponseValue200ApplicationJsonPropertyDataItemStatus)[keyof typeof ListAffiliateReferralsResponseValue200ApplicationJsonPropertyDataItemStatus]
  | (string & Record<never, never>);
