// This file is auto-generated by oagen. Do not edit.

export const SdkUpdateReferralStatusRequestApplicationJsonStatus = {
  Accepted: 'accepted',
  InReview: 'in_review',
  Rejected: 'rejected',
} as const;

export type SdkUpdateReferralStatusRequestApplicationJsonStatus =
  | (typeof SdkUpdateReferralStatusRequestApplicationJsonStatus)[keyof typeof SdkUpdateReferralStatusRequestApplicationJsonStatus]
  | (string & Record<never, never>);
