// This file is auto-generated by oagen. Do not edit.

import type { SellApp } from '../sellapp';
import type { GetOptions as RequestOptions } from '../common/interfaces/get-options.interface';
import type { CreateOptions } from './interfaces/create-options.interface';
import type { GetOptions } from './interfaces/get-options.interface';
import type { ReplaceOptions } from './interfaces/replace-options.interface';
import type { UpdateOptions } from './interfaces/update-options.interface';
import type { DeleteOptions } from './interfaces/delete-options.interface';
import type { SdkListNotificationChannelsResponseValue200ApplicationJson, SdkListNotificationChannelsResponseValue200ApplicationJsonResponse } from '../store-settings/interfaces/sdk-list-notification-channels-response-value-200-application-json.interface';
import type { SdkCreateNotificationChannelResponseValue201ApplicationJson, SdkCreateNotificationChannelResponseValue201ApplicationJsonResponse } from '../store-settings/interfaces/sdk-create-notification-channel-response-value-201-application-json.interface';
import type { SdkGetNotificationChannelResponseValue200ApplicationJson, SdkGetNotificationChannelResponseValue200ApplicationJsonResponse } from '../store-settings/interfaces/sdk-get-notification-channel-response-value-200-application-json.interface';
import type { SdkReplaceNotificationChannelResponseValue200ApplicationJson, SdkReplaceNotificationChannelResponseValue200ApplicationJsonResponse } from '../store-settings/interfaces/sdk-replace-notification-channel-response-value-200-application-json.interface';
import type { SdkUpdateNotificationChannelResponseValue200ApplicationJson, SdkUpdateNotificationChannelResponseValue200ApplicationJsonResponse } from '../store-settings/interfaces/sdk-update-notification-channel-response-value-200-application-json.interface';
import type { SdkCreateNotificationChannelRequestApplicationJsonResponse } from '../store-settings/interfaces/sdk-create-notification-channel-request-application-json.interface';
import type { SdkReplaceNotificationChannelRequestApplicationJsonResponse } from '../store-settings/interfaces/sdk-replace-notification-channel-request-application-json.interface';
import type { SdkUpdateNotificationChannelRequestApplicationJsonResponse } from '../store-settings/interfaces/sdk-update-notification-channel-request-application-json.interface';
import { deserializeSdkListNotificationChannelsResponseValue200ApplicationJson } from '../store-settings/serializers/sdk-list-notification-channels-response-value-200-application-json.serializer';
import { deserializeSdkCreateNotificationChannelResponseValue201ApplicationJson } from '../store-settings/serializers/sdk-create-notification-channel-response-value-201-application-json.serializer';
import { deserializeSdkGetNotificationChannelResponseValue200ApplicationJson } from '../store-settings/serializers/sdk-get-notification-channel-response-value-200-application-json.serializer';
import { deserializeSdkReplaceNotificationChannelResponseValue200ApplicationJson } from '../store-settings/serializers/sdk-replace-notification-channel-response-value-200-application-json.serializer';
import { deserializeSdkUpdateNotificationChannelResponseValue200ApplicationJson } from '../store-settings/serializers/sdk-update-notification-channel-response-value-200-application-json.serializer';
import { serializeSdkCreateNotificationChannelRequestApplicationJson } from '../store-settings/serializers/sdk-create-notification-channel-request-application-json.serializer';
import { serializeSdkReplaceNotificationChannelRequestApplicationJson } from '../store-settings/serializers/sdk-replace-notification-channel-request-application-json.serializer';
import { serializeSdkUpdateNotificationChannelRequestApplicationJson } from '../store-settings/serializers/sdk-update-notification-channel-request-application-json.serializer';

interface SellAppResponseEnvelope<T> { data: T; status: number; headers: Headers; requestId?: string }
type SellAppWithResponse<T extends object> = {
  [K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never]:
    T[K] extends (...args: infer A) => Promise<infer R> ? (...args: A) => Promise<SellAppResponseEnvelope<R>> : never;
};
function createResourceWithResponse<T extends object>(resource: T, client: SellApp): SellAppWithResponse<T> {
  return new Proxy({} as SellAppWithResponse<T>, {
    get: (_target, property) => (...args: unknown[]) => client.captureResponse(
      () => (resource[property as keyof T] as (...values: unknown[]) => Promise<unknown>).apply(resource, args),
    ),
  }) as SellAppWithResponse<T>;
}

export class StoreNotificationChannels {
  constructor(private readonly sellApp: SellApp) {}
  get withResponse(): SellAppWithResponse<this> { return createResourceWithResponse(this, this.sellApp); }

  /**
   * List notification channels
   *
   * List dashboard notification destinations without exposing Discord webhook URLs. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @returns {Promise<SdkListNotificationChannelsResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async list(requestOptions: RequestOptions = {}): Promise<SdkListNotificationChannelsResponseValue200ApplicationJson> {
    const { data } = await this.sellApp.get<SdkListNotificationChannelsResponseValue200ApplicationJsonResponse>('/v2/store/notification-channels', requestOptions);
    return deserializeSdkListNotificationChannelsResponseValue200ApplicationJson(data);
  }

  /**
   * Create a notification channel
   *
   * Create an email or Discord notification destination. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @returns {Promise<SdkCreateNotificationChannelResponseValue201ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async create(options: CreateOptions): Promise<SdkCreateNotificationChannelResponseValue201ApplicationJson> {
    const { requestOptions, ...payload } = options;
    const { data } = await this.sellApp.post<SdkCreateNotificationChannelResponseValue201ApplicationJsonResponse, SdkCreateNotificationChannelRequestApplicationJsonResponse>(
      '/v2/store/notification-channels',
      serializeSdkCreateNotificationChannelRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'createNotificationChannel' },
    );
    return deserializeSdkCreateNotificationChannelResponseValue201ApplicationJson(data);
  }

  /**
   * Retrieve a notification channel
   *
   * Manage one store-scoped notification channel by its identifier. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.notificationChannel - The UUID of the notification channel.
   * @returns {Promise<SdkGetNotificationChannelResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async get(options: GetOptions): Promise<SdkGetNotificationChannelResponseValue200ApplicationJson> {
    const { notificationChannel } = options;
    const { data } = await this.sellApp.get<SdkGetNotificationChannelResponseValue200ApplicationJsonResponse>(`/v2/store/notification-channels/${encodeURIComponent(notificationChannel)}`, { ...options.requestOptions, operationId: 'getNotificationChannel' });
    return deserializeSdkGetNotificationChannelResponseValue200ApplicationJson(data);
  }

  /**
   * Update a notification channel
   *
   * Manage one store-scoped notification channel by its identifier. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.notificationChannel - The UUID of the notification channel.
   * @returns {Promise<SdkReplaceNotificationChannelResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async replace(options: ReplaceOptions): Promise<SdkReplaceNotificationChannelResponseValue200ApplicationJson> {
    const { notificationChannel, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.put<SdkReplaceNotificationChannelResponseValue200ApplicationJsonResponse, SdkReplaceNotificationChannelRequestApplicationJsonResponse>(
      `/v2/store/notification-channels/${encodeURIComponent(notificationChannel)}`,
      serializeSdkReplaceNotificationChannelRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'replaceNotificationChannel' },
    );
    return deserializeSdkReplaceNotificationChannelResponseValue200ApplicationJson(data);
  }

  /**
   * Update a notification channel
   *
   * Manage one store-scoped notification channel by its identifier. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.notificationChannel - The UUID of the notification channel.
   * @returns {Promise<SdkUpdateNotificationChannelResponseValue200ApplicationJson>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async update(options: UpdateOptions): Promise<SdkUpdateNotificationChannelResponseValue200ApplicationJson> {
    const { notificationChannel, requestOptions, ...payload } = options;
    const { data } = await this.sellApp.patch<SdkUpdateNotificationChannelResponseValue200ApplicationJsonResponse, SdkUpdateNotificationChannelRequestApplicationJsonResponse>(
      `/v2/store/notification-channels/${encodeURIComponent(notificationChannel)}`,
      serializeSdkUpdateNotificationChannelRequestApplicationJson(payload), { ...options.requestOptions, operationId: 'updateNotificationChannel' },
    );
    return deserializeSdkUpdateNotificationChannelResponseValue200ApplicationJson(data);
  }

  /**
   * Delete a notification channel
   *
   * Manage one store-scoped notification channel by its identifier. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
   * @param options - The request options.
   * @param options.notificationChannel - The UUID of the notification channel.
   * @returns {Promise<void>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async delete(options: DeleteOptions): Promise<void> {
    const { notificationChannel } = options;
    await this.sellApp.delete(`/v2/store/notification-channels/${encodeURIComponent(notificationChannel)}`, { ...options.requestOptions, operationId: 'deleteNotificationChannel' });
  }
}
