// This file is auto-generated by oagen. Do not edit.

export const CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideoSource = {
  Mux: 'mux',
  External: 'external',
} as const;

export type CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideoSource =
  | (typeof CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideoSource)[keyof typeof CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideoSource]
  | (string & Record<never, never>);
