// This file is auto-generated by oagen. Do not edit.

export const DeleteCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideoSource = {
  Mux: 'mux',
  External: 'external',
} as const;

export type DeleteCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideoSource =
  | (typeof DeleteCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideoSource)[keyof typeof DeleteCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideoSource]
  | (string & Record<never, never>);
