// This file is auto-generated by oagen. Do not edit.

export const ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyVideoSource = {
  Mux: 'mux',
  External: 'external',
} as const;

export type ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyVideoSource =
  | (typeof ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyVideoSource)[keyof typeof ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyVideoSource]
  | (string & Record<never, never>);
