// This file is auto-generated by oagen. Do not edit.

import type { ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideoSource } from './replace-course-lesson-response-value-200-application-json-property-data-property-video-source.interface';

export interface ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideo {
  source: ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideoSource | (string & Record<never, never>);
  externalUrl: string | null;
  muxPlaybackId: string | null;
  muxStatus: string | null;
  durationSeconds: number | null;
  [key: string]: unknown;
}

export interface ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideoResponse {
  source: ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyVideoSource | (string & Record<never, never>);
  external_url: string | null;
  mux_playback_id: string | null;
  mux_status: string | null;
  duration_seconds: number | null;
  [key: string]: unknown;
}
