// This file is auto-generated by oagen. Do not edit.

export const UpdateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType = {
  Text: 'text',
  SingleChoice: 'single_choice',
  MultipleChoice: 'multiple_choice',
} as const;

export type UpdateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType =
  | (typeof UpdateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType)[keyof typeof UpdateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType]
  | (string & Record<never, never>);
