// This file is auto-generated by oagen. Do not edit.


export type ConfirmCustomerSubscriptionPlanChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata = Record<string, unknown>;

export type ConfirmCustomerSubscriptionPlanChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadataResponse = Record<string, unknown>;
