// This file is auto-generated by oagen. Do not edit.

import type { ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject, ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubjectResponse } from './list-customer-portal-entitlements-response-value-200-application-json-property-data-item-property-subject.interface';
import type { ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemKind } from './list-customer-portal-entitlements-response-value-200-application-json-property-data-item-kind.interface';
import type { ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemState } from './list-customer-portal-entitlements-response-value-200-application-json-property-data-item-state.interface';

export interface ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItem {
  id: string;
  kind: ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemKind | (string & Record<never, never>);
  state: ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemState | (string & Record<never, never>);
  customerId: number;
  subject: ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject;
  [key: string]: unknown;
}

export interface ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemResponse {
  id: string;
  kind: ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemKind | (string & Record<never, never>);
  state: ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemState | (string & Record<never, never>);
  customer_id: number;
  subject: ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubjectResponse;
  [key: string]: unknown;
}
