// This file is auto-generated by oagen. Do not edit.

import type { ResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata, ResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadataResponse } from './resume-customer-subscription-response-value-200-application-json-property-data-property-customer-property-metadata.interface';

export interface ResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomer {
  id: number;
  email: string;
  externalId: string | null;
  name: string | null;
  locale: string | null;
  metadata: ResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata;
  [key: string]: unknown;
}

export interface ResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomerResponse {
  id: number;
  email: string;
  external_id: string | null;
  name: string | null;
  locale: string | null;
  metadata: ResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadataResponse;
  [key: string]: unknown;
}
