// This file is auto-generated by oagen. Do not edit.

import type { PauseCustomerSubscriptionResponseValue200ApplicationJsonPropertyData, PauseCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataResponse } from './pause-customer-subscription-response-value-200-application-json-property-data.interface';

export interface SdkPauseCustomerSubscriptionResponseValue200ApplicationJson {
  data: PauseCustomerSubscriptionResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkPauseCustomerSubscriptionResponseValue200ApplicationJsonResponse {
  data: PauseCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
