// This file is auto-generated by oagen. Do not edit.

import type { GetOptions as RequestOptions } from '../../common/interfaces/get-options.interface';

export interface UpdateOptions {
  /** Per-call timeout, retry, headers, cancellation, and lifecycle metadata. */
  requestOptions?: RequestOptions;
  /** The highlight path parameter. */
  highlight: number;
  /** The media path parameter. */
  media: number;
  ctaTitle?: string;
  productId?: number | null;
}
