// This file is auto-generated by oagen. Do not edit.

import type { GetWebhookChannelResponseValue200ApplicationJsonPropertyData, GetWebhookChannelResponseValue200ApplicationJsonPropertyDataResponse } from './get-webhook-channel-response-value-200-application-json-property-data.interface';

export interface SdkGetWebhookChannelResponseValue200ApplicationJson {
  data: GetWebhookChannelResponseValue200ApplicationJsonPropertyData;
  [key: string]: unknown;
}

export interface SdkGetWebhookChannelResponseValue200ApplicationJsonResponse {
  data: GetWebhookChannelResponseValue200ApplicationJsonPropertyDataResponse;
  [key: string]: unknown;
}
