// This file is auto-generated by oagen. Do not edit.

import type { SearchWebhookChannelsRequestApplicationJsonPropertySearch, SearchWebhookChannelsRequestApplicationJsonPropertySearchResponse } from './search-webhook-channels-request-application-json-property-search.interface';
import type { Event } from './event.interface';

export interface SdkSearchWebhookChannelsRequestApplicationJson {
  search?: SearchWebhookChannelsRequestApplicationJsonPropertySearch;
  /** Public event name delivered in webhook payloads. SellApp maps it to the corresponding allowed_notifications filter. */
  event?: Event | (string & Record<never, never>) | null;
  /** @default 1 */
  page?: number;
  /** @default 15 */
  limit?: number;
  [key: string]: unknown;
}

export interface SdkSearchWebhookChannelsRequestApplicationJsonResponse {
  search?: SearchWebhookChannelsRequestApplicationJsonPropertySearchResponse;
  event?: Event | (string & Record<never, never>) | null;
  page?: number;
  limit?: number;
  [key: string]: unknown;
}
