// This file is auto-generated by oagen. Do not edit.

import type { SearchWebhookChannelsResponseValue200ApplicationJsonPropertyDataItemAllowedNotifications } from './search-webhook-channels-response-value-200-application-json-property-data-item-allowed-notifications.interface';

/** A seller-configured outbound webhook destination. IDs are stable UUIDs and are not reused when another channel is deleted. */
export interface SearchWebhookChannelsResponseValue200ApplicationJsonPropertyDataItem {
  /** Stable identifier for this webhook channel. */
  id: string;
  /** Optional seller-facing reference name. */
  name: string | null;
  /** Public HTTP or HTTPS destination. Local, private, reserved, link-local, metadata, credential-bearing, and Discord webhook URLs are rejected. Delivery resolves and pins a public address and does not follow redirects. */
  url: string;
  /** Complete set of public webhook event names enabled for this destination. Updating this field replaces the previous filter. */
  allowedNotifications: (SearchWebhookChannelsResponseValue200ApplicationJsonPropertyDataItemAllowedNotifications | (string & Record<never, never>))[];
  /**
   * Whether the store has an outbound webhook signing secret. The stored secret is never returned.
   * @readonly
   */
  readonly signingSecretConfigured: boolean;
  [key: string]: unknown;
}

export interface SearchWebhookChannelsResponseValue200ApplicationJsonPropertyDataItemResponse {
  id: string;
  name: string | null;
  url: string;
  allowed_notifications: (SearchWebhookChannelsResponseValue200ApplicationJsonPropertyDataItemAllowedNotifications | (string & Record<never, never>))[];
  signing_secret_configured: boolean;
  [key: string]: unknown;
}
