// This file is auto-generated by oagen. Do not edit.

export { serializeCreateCreditsProductRequestApplicationJsonPropertyRateTiersItem as serializeReplaceCreditsProductRequestApplicationJsonPropertyRateTiersItem } from './create-credits-product-request-application-json-property-rate-tiers-item.serializer';
