// This file is auto-generated by oagen. Do not edit.

import type { SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson, SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-replace-variant-deliverable-file-settings-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJsonPropertyData } from './replace-variant-deliverable-file-settings-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson = (
  response: SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJsonResponse,
): SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
