// This file is auto-generated by oagen. Do not edit.

export { deserializeListCustomPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemPropertyModifier as deserializeGetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyModifier } from './list-custom-payment-methods-response-value-200-application-json-property-data-item-property-modifier.serializer';
