// This file is auto-generated by oagen. Do not edit.

import type { SdkListCustomPaymentMethodsResponseValue200ApplicationJson, SdkListCustomPaymentMethodsResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-list-custom-payment-methods-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeListCustomPaymentMethodsResponseValue200ApplicationJsonPropertyDataItem } from './list-custom-payment-methods-response-value-200-application-json-property-data-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkListCustomPaymentMethodsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkListCustomPaymentMethodsResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const deserializeSdkListCustomPaymentMethodsResponseValue200ApplicationJson = (
  response: SdkListCustomPaymentMethodsResponseValue200ApplicationJsonResponse,
): SdkListCustomPaymentMethodsResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: response.data.map(deserializeListCustomPaymentMethodsResponseValue200ApplicationJsonPropertyDataItem),
  };
};
