// This file is auto-generated by oagen. Do not edit.

import type { SdkEnableOrDisablePaymentMethodRequestApplicationJson, SdkEnableOrDisablePaymentMethodRequestApplicationJsonResponse } from '../interfaces/sdk-enable-or-disable-payment-method-request-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkEnableOrDisablePaymentMethodRequestApplicationJson","required":["enabled"],"properties":{"enabled":{"kind":"primitive","type":"boolean"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkEnableOrDisablePaymentMethodRequestApplicationJson","required":["enabled"],"properties":{"enabled":{"kind":"primitive","type":"boolean"}},"additionalProperties":true};

export const serializeSdkEnableOrDisablePaymentMethodRequestApplicationJson = (
  model: SdkEnableOrDisablePaymentMethodRequestApplicationJson,
): SdkEnableOrDisablePaymentMethodRequestApplicationJsonResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["enabled"]),
    enabled: model.enabled,
  };
};
