// This file is auto-generated by oagen. Do not edit.

import type { SdkReplaceCustomPaymentMethodResponseValue200ApplicationJson, SdkReplaceCustomPaymentMethodResponseValue200ApplicationJsonResponse } from '../interfaces/sdk-replace-custom-payment-method-response-value-200-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeReplaceCustomPaymentMethodResponseValue200ApplicationJsonPropertyData } from './replace-custom-payment-method-response-value-200-application-json-property-data.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceCustomPaymentMethodResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkReplaceCustomPaymentMethodResponseValue200ApplicationJson","required":["data"],"properties":{"data":{"kind":"any"}},"additionalProperties":true};

export const deserializeSdkReplaceCustomPaymentMethodResponseValue200ApplicationJson = (
  response: SdkReplaceCustomPaymentMethodResponseValue200ApplicationJsonResponse,
): SdkReplaceCustomPaymentMethodResponseValue200ApplicationJson => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["data"]),
    data: deserializeReplaceCustomPaymentMethodResponseValue200ApplicationJsonPropertyData(response.data),
  };
};
