// This file is auto-generated by oagen. Do not edit.

import type { ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject, ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubjectResponse } from '../interfaces/list-customer-entitlements-response-value-200-application-json-property-data-item-property-subject.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject","required":["type","id","name"],"properties":{"type":{"kind":"primitive","type":"string"},"id":{"kind":"union","variants":[{"kind":"primitive","type":"integer"},{"kind":"primitive","type":"string"}]},"name":{"kind":"primitive","type":"string"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject","required":["type","id","name"],"properties":{"type":{"kind":"primitive","type":"string"},"id":{"kind":"union","variants":[{"kind":"primitive","type":"integer"},{"kind":"primitive","type":"string"}]},"name":{"kind":"primitive","type":"string"}},"additionalProperties":true};

export const deserializeListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject = (
  response: ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubjectResponse,
): ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["type","id","name"]),
    type: response.type,
    id: response.id,
    name: response.name,
  };
};
