// This file is auto-generated by oagen. Do not edit.

export interface ListPendingAffiliateInvitationsResponseValue200ApplicationJsonPropertyDataItem {
  id: number;
  email: string;
  status: 'pending';
  invitedAt: Date | null;
  applicationSubmittedAt: Date | null;
  createdAt: Date | null;
  [key: string]: unknown;
}

export interface ListPendingAffiliateInvitationsResponseValue200ApplicationJsonPropertyDataItemResponse {
  id: number;
  email: string;
  status: 'pending';
  invited_at: string | null;
  application_submitted_at: string | null;
  created_at: string | null;
  [key: string]: unknown;
}
