// This file is auto-generated by oagen. Do not edit.

import type { CreateProductRequestApplicationJsonPropertyVariantsItemPropertyPricingPropertyPrice, CreateProductRequestApplicationJsonPropertyVariantsItemPropertyPricingPropertyPriceResponse } from '../interfaces/create-product-request-application-json-property-variants-item-property-pricing-property-price.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"CreateProductRequestApplicationJsonPropertyVariantsItemPropertyPricingPropertyPrice","required":["price","currency"],"properties":{"price":{"kind":"primitive","type":"integer"},"currency":{"kind":"primitive","type":"string"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"CreateProductRequestApplicationJsonPropertyVariantsItemPropertyPricingPropertyPrice","required":["price","currency"],"properties":{"price":{"kind":"primitive","type":"integer"},"currency":{"kind":"primitive","type":"string"}},"additionalProperties":true};

export const serializeCreateProductRequestApplicationJsonPropertyVariantsItemPropertyPricingPropertyPrice = (
  model: CreateProductRequestApplicationJsonPropertyVariantsItemPropertyPricingPropertyPrice,
): CreateProductRequestApplicationJsonPropertyVariantsItemPropertyPricingPropertyPriceResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["price","currency"]),
    price: model.price,
    currency: model.currency,
  };
};
