// This file is auto-generated by oagen. Do not edit.

import type { CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyData, CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataResponse } from '../interfaces/create-product-request-application-json-property-variants-item-property-deliverable-property-data.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { serializeCreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBooking } from './create-product-request-application-json-property-variants-item-property-deliverable-property-data-property-booking.serializer';
import { serializeCreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyCreditRateTiersItem } from './create-product-request-application-json-property-variants-item-property-deliverable-property-data-property-credit-rate-tiers-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyData","required":[],"properties":{"stock":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"serials":{"kind":"array","items":{"kind":"primitive","type":"string"}},"removeDuplicate":{"kind":"primitive","type":"boolean"},"parsingMode":{"kind":"enum","values":["COMMA","NEW_LINE","SPACE","CUSTOM"]},"comment":{"kind":"primitive","type":"string"},"webhook":{"kind":"primitive","type":"string","format":"uri"},"booking":{"kind":"any"},"creditRateTiers":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyData","required":[],"properties":{"stock":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"serials":{"kind":"array","items":{"kind":"primitive","type":"string"}},"remove_duplicate":{"kind":"primitive","type":"boolean"},"parsing_mode":{"kind":"enum","values":["COMMA","NEW_LINE","SPACE","CUSTOM"]},"comment":{"kind":"primitive","type":"string"},"webhook":{"kind":"primitive","type":"string","format":"uri"},"booking":{"kind":"any"},"credit_rate_tiers":{"kind":"array","items":{"kind":"any"}}},"additionalProperties":true};

export const serializeCreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyData = (
  model: CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyData,
): CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["stock","serials","removeDuplicate","parsingMode","comment","webhook","booking","creditRateTiers"]),
    stock: model.stock,
    serials: model.serials,
    remove_duplicate: model.removeDuplicate,
    parsing_mode: model.parsingMode,
    comment: model.comment,
    webhook: model.webhook,
    booking: model.booking != null ? serializeCreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBooking(model.booking) : undefined,
    credit_rate_tiers: model.creditRateTiers != null ? model.creditRateTiers.map(serializeCreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyCreditRateTiersItem) : undefined,
  };
};
