// This file is auto-generated by oagen. Do not edit.

import type { CreateProductResponseValue201ApplicationJsonPropertyData, CreateProductResponseValue201ApplicationJsonPropertyDataResponse } from '../interfaces/create-product-response-value-201-application-json-property-data.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { deserializeCreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItem } from './create-product-response-value-201-application-json-property-data-property-images-item.serializer';
import { deserializeCreateProductResponseValue201ApplicationJsonPropertyDataPropertyAdditionalInformationItem } from './create-product-response-value-201-application-json-property-data-property-additional-information-item.serializer';
import { deserializeCreateProductResponseValue201ApplicationJsonPropertyDataPropertyOtherSettings } from './create-product-response-value-201-application-json-property-data-property-other-settings.serializer';
import { deserializeCreateProductResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem } from './create-product-response-value-201-application-json-property-data-property-variants-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"CreateProductResponseValue201ApplicationJsonPropertyData","required":["id","title","slug","description","images","order","visibility","deliveryText","additionalInformation","otherSettings","deletedAt","createdAt","updatedAt","storeId","sectionId","sectionOrder","isDiscoverable","variants","url"],"properties":{"id":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"slug":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"images":{"kind":"array","items":{"kind":"any"}},"order":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"visibility":{"kind":"primitive","type":"string"},"deliveryText":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"additionalInformation":{"kind":"array","items":{"kind":"any"}},"otherSettings":{"kind":"any"},"deletedAt":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"createdAt":{"kind":"primitive","type":"string","format":"date-time"},"updatedAt":{"kind":"primitive","type":"string","format":"date-time"},"storeId":{"kind":"primitive","type":"integer"},"sectionId":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"sectionOrder":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"isDiscoverable":{"kind":"primitive","type":"boolean"},"variants":{"kind":"array","items":{"kind":"any"}},"url":{"kind":"primitive","type":"string"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"CreateProductResponseValue201ApplicationJsonPropertyData","required":["id","title","slug","description","images","order","visibility","delivery_text","additional_information","other_settings","deleted_at","created_at","updated_at","store_id","section_id","section_order","is_discoverable","variants","url"],"properties":{"id":{"kind":"primitive","type":"integer"},"title":{"kind":"primitive","type":"string"},"slug":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"images":{"kind":"array","items":{"kind":"any"}},"order":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"visibility":{"kind":"primitive","type":"string"},"delivery_text":{"kind":"nullable","inner":{"kind":"primitive","type":"string"}},"additional_information":{"kind":"array","items":{"kind":"any"}},"other_settings":{"kind":"any"},"deleted_at":{"kind":"nullable","inner":{"kind":"primitive","type":"string","format":"date-time"}},"created_at":{"kind":"primitive","type":"string","format":"date-time"},"updated_at":{"kind":"primitive","type":"string","format":"date-time"},"store_id":{"kind":"primitive","type":"integer"},"section_id":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"section_order":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"is_discoverable":{"kind":"primitive","type":"boolean"},"variants":{"kind":"array","items":{"kind":"any"}},"url":{"kind":"primitive","type":"string"}},"additionalProperties":true};

export const deserializeCreateProductResponseValue201ApplicationJsonPropertyData = (
  response: CreateProductResponseValue201ApplicationJsonPropertyDataResponse,
): CreateProductResponseValue201ApplicationJsonPropertyData => {
  assertValidModel(response, wireRuntimeSchema, { direction: 'response', allowUnknownEnums: true, allowUnknownUnionVariants: true, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(response, ["id","title","slug","description","images","order","visibility","delivery_text","additional_information","other_settings","deleted_at","created_at","updated_at","store_id","section_id","section_order","is_discoverable","variants","url"]),
    id: response.id,
    title: response.title,
    slug: response.slug,
    description: response.description,
    images: response.images.map(deserializeCreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItem),
    order: response.order ?? null,
    visibility: response.visibility,
    deliveryText: response.delivery_text ?? null,
    additionalInformation: response.additional_information.map(deserializeCreateProductResponseValue201ApplicationJsonPropertyDataPropertyAdditionalInformationItem),
    otherSettings: deserializeCreateProductResponseValue201ApplicationJsonPropertyDataPropertyOtherSettings(response.other_settings),
    deletedAt: response.deleted_at != null ? new Date(response.deleted_at) : null,
    createdAt: new Date(response.created_at),
    updatedAt: new Date(response.updated_at),
    storeId: response.store_id,
    sectionId: response.section_id ?? null,
    sectionOrder: response.section_order ?? null,
    isDiscoverable: response.is_discoverable,
    variants: response.variants.map(deserializeCreateProductResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem),
    url: response.url,
  };
};
