// This file is auto-generated by oagen. Do not edit.

export { deserializeListProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem as deserializeGetProductResponseValue200ApplicationJsonPropertyDataPropertyAdditionalInformationItem } from './list-products-response-value-200-application-json-property-data-item-property-additional-information-item.serializer';
