// This file is auto-generated by oagen. Do not edit.

export { deserializeListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings as deserializeGetProductResponseValue200ApplicationJsonPropertyDataPropertyOtherSettings } from '../../groups/serializers/list-products-within-group-response-value-200-application-json-property-data-item-property-other-settings.serializer';
