// This file is auto-generated by oagen. Do not edit.

export { deserializeListProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem as deserializeGetProductResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem } from './list-products-response-value-200-application-json-property-data-item-property-variants-item.serializer';
