// This file is auto-generated by oagen. Do not edit.

import type { ProductFaqInput, ProductFaqInputResponse } from '../interfaces/product-faq-input.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"ProductFaqInput","required":["question","answer"],"properties":{"question":{"kind":"primitive","type":"string"},"answer":{"kind":"primitive","type":"string"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"ProductFaqInput","required":["question","answer"],"properties":{"question":{"kind":"primitive","type":"string"},"answer":{"kind":"primitive","type":"string"}},"additionalProperties":true};

export const serializeProductFaqInput = (
  model: ProductFaqInput,
): ProductFaqInputResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["question","answer"]),
    question: model.question,
    answer: model.answer,
  };
};
