// This file is auto-generated by oagen. Do not edit.

import type { SdkUpdateProductRequestApplicationJson, SdkUpdateProductRequestApplicationJsonResponse } from '../interfaces/sdk-update-product-request-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { serializeUpdateProductRequestApplicationJsonPropertyAdditionalInformationItem } from './update-product-request-application-json-property-additional-information-item.serializer';
import { serializeUpdateProductRequestApplicationJsonPropertyOtherSettings } from './update-product-request-application-json-property-other-settings.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkUpdateProductRequestApplicationJson","required":[],"properties":{"title":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"visibility":{"kind":"enum","values":["PUBLIC","ON_HOLD","HIDDEN","PRIVATE"]},"slug":{"kind":"primitive","type":"string"},"section":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"additionalInformation":{"kind":"array","items":{"kind":"any"}},"otherSettings":{"kind":"any"},"expectedUpdatedAt":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkUpdateProductRequestApplicationJson","required":[],"properties":{"title":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"visibility":{"kind":"enum","values":["PUBLIC","ON_HOLD","HIDDEN","PRIVATE"]},"slug":{"kind":"primitive","type":"string"},"section":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"additional_information":{"kind":"array","items":{"kind":"any"}},"other_settings":{"kind":"any"},"expected_updated_at":{"kind":"primitive","type":"string","format":"date-time"}},"additionalProperties":true};

export const serializeSdkUpdateProductRequestApplicationJson = (
  model: SdkUpdateProductRequestApplicationJson,
): SdkUpdateProductRequestApplicationJsonResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["title","description","visibility","slug","section","additionalInformation","otherSettings","expectedUpdatedAt"]),
    title: model.title,
    description: model.description,
    visibility: model.visibility,
    slug: model.slug,
    section: model.section,
    additional_information: model.additionalInformation != null ? model.additionalInformation.map(serializeUpdateProductRequestApplicationJsonPropertyAdditionalInformationItem) : undefined,
    other_settings: model.otherSettings != null ? serializeUpdateProductRequestApplicationJsonPropertyOtherSettings(model.otherSettings) : undefined,
    expected_updated_at: model.expectedUpdatedAt != null ? model.expectedUpdatedAt.toISOString() : undefined,
  };
};
