// This file is auto-generated by oagen. Do not edit.

import type { SdkCreateProductRequestApplicationJson, SdkCreateProductRequestApplicationJsonResponse } from '../interfaces/sdk-create-product-request-application-json.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';
import { serializeCreateProductRequestApplicationJsonPropertyAdditionalInformationItem } from './create-product-request-application-json-property-additional-information-item.serializer';
import { serializeCreateProductRequestApplicationJsonPropertyOtherSettings } from './create-product-request-application-json-property-other-settings.serializer';
import { serializeCreateProductRequestApplicationJsonPropertyVariantsItem } from './create-product-request-application-json-property-variants-item.serializer';
import { serializeCreateProductRequestApplicationJsonPropertyBundleItemsItem } from './create-product-request-application-json-property-bundle-items-item.serializer';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SdkCreateProductRequestApplicationJson","required":["title","description","visibility"],"properties":{"title":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"visibility":{"kind":"enum","values":["PUBLIC","ON_HOLD","HIDDEN","PRIVATE"]},"slug":{"kind":"primitive","type":"string"},"type":{"kind":"enum","values":["product","bundle"]},"section":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"additionalInformation":{"kind":"array","items":{"kind":"any"}},"otherSettings":{"kind":"any"},"variants":{"kind":"array","items":{"kind":"any"},"constraints":{"minItems":1,"maxItems":100}},"bundleItems":{"kind":"array","items":{"kind":"any"},"constraints":{"minItems":1,"maxItems":50}}},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SdkCreateProductRequestApplicationJson","required":["title","description","visibility"],"properties":{"title":{"kind":"primitive","type":"string"},"description":{"kind":"primitive","type":"string"},"visibility":{"kind":"enum","values":["PUBLIC","ON_HOLD","HIDDEN","PRIVATE"]},"slug":{"kind":"primitive","type":"string"},"type":{"kind":"enum","values":["product","bundle"]},"section":{"kind":"nullable","inner":{"kind":"primitive","type":"integer"}},"additional_information":{"kind":"array","items":{"kind":"any"}},"other_settings":{"kind":"any"},"variants":{"kind":"array","items":{"kind":"any"},"constraints":{"minItems":1,"maxItems":100}},"bundle_items":{"kind":"array","items":{"kind":"any"},"constraints":{"minItems":1,"maxItems":50}}},"additionalProperties":true};

export const serializeSdkCreateProductRequestApplicationJson = (
  model: SdkCreateProductRequestApplicationJson,
): SdkCreateProductRequestApplicationJsonResponse => {
  assertValidModel(model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(model, ["title","description","visibility","slug","type","section","additionalInformation","otherSettings","variants","bundleItems"]),
    title: model.title,
    description: model.description,
    visibility: model.visibility,
    slug: model.slug,
    type: model.type,
    section: model.section,
    additional_information: model.additionalInformation != null ? model.additionalInformation.map(serializeCreateProductRequestApplicationJsonPropertyAdditionalInformationItem) : undefined,
    other_settings: model.otherSettings != null ? serializeCreateProductRequestApplicationJsonPropertyOtherSettings(model.otherSettings) : undefined,
    variants: model.variants != null ? model.variants.map(serializeCreateProductRequestApplicationJsonPropertyVariantsItem) : undefined,
    bundle_items: model.bundleItems != null ? model.bundleItems.map(serializeCreateProductRequestApplicationJsonPropertyBundleItemsItem) : undefined,
  };
};
