// This file is auto-generated by oagen. Do not edit.

import type { SearchProductsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem, SearchProductsRequestApplicationJsonPropertyFiltersItemPropertyNestedItemResponse } from '../interfaces/search-products-request-application-json-property-filters-item-property-nested-item.interface';
import { assertValidModel, preserveUnknownFields } from '../../common/utils/schema-validation';

const domainRuntimeSchema: RuntimeModelSchema = {"name":"SearchProductsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem","required":[],"properties":{},"additionalProperties":true};
const wireRuntimeSchema: RuntimeModelSchema = {"name":"SearchProductsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem","required":[],"properties":{},"additionalProperties":true};

export const serializeSearchProductsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem = (
  _model: SearchProductsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem,
): SearchProductsRequestApplicationJsonPropertyFiltersItemPropertyNestedItemResponse => {
  assertValidModel(_model, domainRuntimeSchema, { direction: 'request', allowUnknownEnums: false, allowUnknownUnionVariants: false, allowUnknownFields: true });
  return {
    ...preserveUnknownFields(_model, []),
  };
};
