// This file is auto-generated by oagen. Do not edit.

export interface CreateExportResponseValue201ApplicationJsonPropertyMeta {
  pollAfterSeconds: number;
  [key: string]: unknown;
}

export interface CreateExportResponseValue201ApplicationJsonPropertyMetaResponse {
  poll_after_seconds: number;
  [key: string]: unknown;
}
