// This file is auto-generated by oagen. Do not edit.

import type { GetExportResponseValue200ApplicationJsonPropertyDataPropertyParametersReportType } from './get-export-response-value-200-application-json-property-data-property-parameters-report-type.interface';

export interface GetExportResponseValue200ApplicationJsonPropertyDataPropertyParameters {
  /** Inclusive start date. Omitted or null uses 365 days before to. */
  from?: string | null;
  /** Inclusive end date. Omitted or null uses today. The range may span at most 366 calendar days. */
  to?: string | null;
  reportType?: GetExportResponseValue200ApplicationJsonPropertyDataPropertyParametersReportType | (string & Record<never, never>);
  [key: string]: unknown;
}

export interface GetExportResponseValue200ApplicationJsonPropertyDataPropertyParametersResponse {
  from?: string | null;
  to?: string | null;
  report_type?: GetExportResponseValue200ApplicationJsonPropertyDataPropertyParametersReportType | (string & Record<never, never>);
  [key: string]: unknown;
}
