// This file is auto-generated by oagen. Do not edit.

import type { GetExportResponseValue200ApplicationJsonPropertyDataPropertyParameters, GetExportResponseValue200ApplicationJsonPropertyDataPropertyParametersResponse } from './get-export-response-value-200-application-json-property-data-property-parameters.interface';
import type { GetExportResponseValue200ApplicationJsonPropertyDataType } from './get-export-response-value-200-application-json-property-data-type.interface';
import type { GetExportResponseValue200ApplicationJsonPropertyDataFormat } from './get-export-response-value-200-application-json-property-data-format.interface';
import type { GetExportResponseValue200ApplicationJsonPropertyDataStatus } from './get-export-response-value-200-application-json-property-data-status.interface';

export interface GetExportResponseValue200ApplicationJsonPropertyData {
  id: string;
  type: GetExportResponseValue200ApplicationJsonPropertyDataType | (string & Record<never, never>);
  format: GetExportResponseValue200ApplicationJsonPropertyDataFormat | (string & Record<never, never>);
  status: GetExportResponseValue200ApplicationJsonPropertyDataStatus | (string & Record<never, never>);
  parameters: GetExportResponseValue200ApplicationJsonPropertyDataPropertyParameters;
  /** Present only for a completed export with an unexpired artifact. This signed URL requires authentication and store authorization, and expires after five minutes. */
  downloadUrl?: string;
  filename: string | null;
  contentType: string | null;
  size: number | null;
  failureMessage: string | null;
  startedAt: Date | null;
  completedAt: Date | null;
  failedAt: Date | null;
  expiresAt: Date | null;
  createdAt: Date;
  updatedAt: Date | null;
  [key: string]: unknown;
}

export interface GetExportResponseValue200ApplicationJsonPropertyDataResponse {
  id: string;
  type: GetExportResponseValue200ApplicationJsonPropertyDataType | (string & Record<never, never>);
  format: GetExportResponseValue200ApplicationJsonPropertyDataFormat | (string & Record<never, never>);
  status: GetExportResponseValue200ApplicationJsonPropertyDataStatus | (string & Record<never, never>);
  parameters: GetExportResponseValue200ApplicationJsonPropertyDataPropertyParametersResponse;
  download_url?: string;
  filename: string | null;
  content_type: string | null;
  size: number | null;
  failure_message: string | null;
  started_at: string | null;
  completed_at: string | null;
  failed_at: string | null;
  expires_at: string | null;
  created_at: string;
  updated_at: string | null;
  [key: string]: unknown;
}
